///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyAuthSuccess = 'success';
const String _jsonKeyAuthMessage = 'message';
const String _jsonKeyAuthData = 'data';
const String _jsonKeyAuthDataToken = 'token';
const String _jsonKeyAuthDataUser = 'user';
const String _jsonKeyAuthDataUserId = 'id';
const String _jsonKeyAuthDataUserEmail = 'email';
const String _jsonKeyAuthDataUserPhone = 'phone';
const String _jsonKeyAuthDataUserFirstName = 'first_name';
const String _jsonKeyAuthDataUserLastName = 'last_name';
const String _jsonKeyAuthDataUserUserType = 'user_type';
const String _jsonKeyAuthDataUserGender = 'gender';
const String _jsonKeyAuthDataUserDateOfBirth = 'date_of_birth';
const String _jsonKeyAuthDataUserStatus = 'status';
const String _jsonKeyAuthDataUserIsUserBanned = 'is_user_banned';
const String _jsonKeyAuthDataUserNewsletterEnable = 'newsletter_enable';
const String _jsonKeyAuthDataUserOtp = 'otp';
const String _jsonKeyAuthDataUserFirebaseAuthId = 'firebase_auth_id';
const String _jsonKeyAuthDataUserIsPasswordSet = 'is_password_set';
const String _jsonKeyAuthDataUserImages = 'images';
const String _jsonKeyAuthDataUserLastLogin = 'last_login';
const String _jsonKeyAuthDataUserLastIp = 'last_ip';
const String _jsonKeyAuthDataUserLastPasswordChange = 'last_password_change';
const String _jsonKeyAuthDataUserImageId = 'image_id';
const String _jsonKeyAuthDataUserRoleId = 'role_id';
const String _jsonKeyAuthDataUserPickupHubId = 'pickup_hub_id';
const String _jsonKeyAuthDataUserBalance = 'balance';
const String _jsonKeyAuthDataUserCreatedAt = 'created_at';
const String _jsonKeyAuthDataUserUpdatedAt = 'updated_at';
const String _jsonKeyAuthDataUserProfileImage = 'profile_image';
const String _jsonKeyAuthDataUserUserProfileImage = 'user_profile_image';
const String _jsonKeyAuthDataUserFullName = 'full_name';
const String _jsonKeyAuthDataUserShippingAddress = 'shipping_address';
const String _jsonKeyAuthDataUserBillingAddress = 'billing_address';
const String _jsonKeyAuthDataUserLastRecharge = 'last_recharge';
const String _jsonKeyAuthDataUserSellerProfile = 'seller_profile';
const String _jsonKeyAuthDataUserSellerProfileId = 'id';
const String _jsonKeyAuthDataUserSellerProfileUserId = 'user_id';
const String _jsonKeyAuthDataUserSellerProfileShopName = 'shop_name';
const String _jsonKeyAuthDataUserSellerProfileSlug = 'slug';
const String _jsonKeyAuthDataUserSellerProfileVerifiedAt = 'verified_at';
const String _jsonKeyAuthDataUserSellerProfileLicenseNo = 'license_no';
const String _jsonKeyAuthDataUserSellerProfileTaxPaper = 'tax_paper';
const String _jsonKeyAuthDataUserSellerProfileLogo = 'logo';
const String _jsonKeyAuthDataUserSellerProfileBanner = 'banner';
const String _jsonKeyAuthDataUserSellerProfileShopPageContents = 'shop_page_contents';
const String _jsonKeyAuthDataUserSellerProfileShopBannerId = 'shop_banner_id';
const String _jsonKeyAuthDataUserSellerProfileShopBanner = 'shop_banner';
const String _jsonKeyAuthDataUserSellerProfileShopTagline = 'shop_tagline';
const String _jsonKeyAuthDataUserSellerProfilePhoneNo = 'phone_no';
const String _jsonKeyAuthDataUserSellerProfileShopEmail = 'shop_email';
const String _jsonKeyAuthDataUserSellerProfileWebsite = 'website';
const String _jsonKeyAuthDataUserSellerProfileAddress = 'address';
const String _jsonKeyAuthDataUserSellerProfileRatingCount = 'rating_count';
const String _jsonKeyAuthDataUserSellerProfileReviewsCount = 'reviews_count';
const String _jsonKeyAuthDataUserSellerProfileFacebook = 'facebook';
const String _jsonKeyAuthDataUserSellerProfileGoogle = 'google';
const String _jsonKeyAuthDataUserSellerProfileTwitter = 'twitter';
const String _jsonKeyAuthDataUserSellerProfileYoutube = 'youtube';
const String _jsonKeyAuthDataUserSellerProfileMetaTitle = 'meta_title';
const String _jsonKeyAuthDataUserSellerProfileMetaDescription = 'meta_description';
const String _jsonKeyAuthDataUserSellerProfileStateId = 'state_id';
const String _jsonKeyAuthDataUserSellerProfileCityId = 'city_id';
const String _jsonKeyAuthDataUserSellerProfileTownId = 'town_id';
const String _jsonKeyAuthDataUserSellerProfileLatitude = 'latitude';
const String _jsonKeyAuthDataUserSellerProfileLongitude = 'longitude';
const String _jsonKeyAuthDataUserSellerProfileScheduleId = 'schedule_id';
const String _jsonKeyAuthDataUserSellerProfileAccountType = 'account_type';
const String _jsonKeyAuthDataUserSellerProfileShopTypeId = 'shop_type_id';
const String _jsonKeyAuthDataUserSellerProfileCreatedAt = 'created_at';
const String _jsonKeyAuthDataUserSellerProfileUpdatedAt = 'updated_at';
const String _jsonKeyAuthDataUserSellerProfileImage_105x75 = 'image_105x75';
const String _jsonKeyAuthDataUserSellerProfileImage_197x152 = 'image_197x152';
const String _jsonKeyAuthDataUserSellerProfileImage_1905x350 = 'image_1905x350';
const String _jsonKeyAuthDataUserSellerProfileImage_90x60 = 'image_90x60';
const String _jsonKeyAuthDataUserSellerProfileImage_82x82 = 'image_82x82';
const String _jsonKeyAuthDataUserSellerProfileImage_120x80 = 'image_120x80';
const String _jsonKeyAuthDataUserSellerProfileImage_297x146 = 'image_297x146';
const String _jsonKeyAuthDataUserSellerProfileImage_617x145 = 'image_617x145';
const String _jsonKeyAuthDataUserSellerProfileStartDate = 'start_date';
const String _jsonKeyAuthDataUserSellerProfileImage_1920x412 = 'image_1920x412';
const String _jsonKeyAuthDataUserSellerProfileShopBannerStorage = 'storage';
const String _jsonKeyAuthDataUserSellerProfileShopBannerOriginalImage = 'original_image';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImage_40x40 = 'image_40x40';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImage_72x72 = 'image_72x72';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImage_190x230 = 'image_190x230';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImage_110x122 = 'image_110x122';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImage_320x320 = 'image_320x320';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImageThumbnail = 'image_thumbnail';
const String _jsonKeyAuthDataUserSellerProfileShopBannerImage_1905x350 = 'image_1905x350';
class AuthDataUserSellerProfileShopBanner {
/*
{
  "storage": "local",
  "original_image": "images/20220609120453_original__media_39.jpg",
  "image_40x40": "images/20220609120453image_40x40_media_243.png",
  "image_72x72": "images/20220609120453image_72x72_media_99.png",
  "image_190x230": "images/20220609120537image_190x230-63.png",
  "image_110x122": "images/20220609120453image_110x122_media_85.png",
  "image_320x320": "images/20220609120453image_300x200_media_50.png",
  "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
  "image_1905x350": "images/20220609124152image_1905x350-71.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;
  String? image_1905x350;

  AuthDataUserSellerProfileShopBanner({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
    this.image_1905x350,
  });
  AuthDataUserSellerProfileShopBanner.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyAuthDataUserSellerProfileShopBannerStorage]?.toString();
    originalImage = json[_jsonKeyAuthDataUserSellerProfileShopBannerOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyAuthDataUserSellerProfileShopBannerImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyAuthDataUserSellerProfileShopBannerImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyAuthDataUserSellerProfileShopBannerImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyAuthDataUserSellerProfileShopBannerImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyAuthDataUserSellerProfileShopBannerImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyAuthDataUserSellerProfileShopBannerImageThumbnail]?.toString();
    image_1905x350 = json[_jsonKeyAuthDataUserSellerProfileShopBannerImage_1905x350]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserSellerProfileShopBannerStorage] = storage;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerOriginalImage] = originalImage;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImage_40x40] = image_40x40;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImage_72x72] = image_72x72;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImage_190x230] = image_190x230;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImage_110x122] = image_110x122;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImage_320x320] = image_320x320;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImageThumbnail] = imageThumbnail;
    data[_jsonKeyAuthDataUserSellerProfileShopBannerImage_1905x350] = image_1905x350;
    return data;
  }
}

const String _jsonKeyAuthDataUserSellerProfileShopPageContentsNewArrival = 'new_arrival';
class AuthDataUserSellerProfileShopPageContents {
/*
{
  "new_arrival": "1"
}
*/

  String? newArrival;

  AuthDataUserSellerProfileShopPageContents({
    this.newArrival,
  });
  AuthDataUserSellerProfileShopPageContents.fromJson(Map<String, dynamic> json) {
    newArrival = json[_jsonKeyAuthDataUserSellerProfileShopPageContentsNewArrival]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserSellerProfileShopPageContentsNewArrival] = newArrival;
    return data;
  }
}

const String _jsonKeyAuthDataUserSellerProfileBannerStorage = 'storage';
const String _jsonKeyAuthDataUserSellerProfileBannerOriginalImage = 'original_image';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_100x38 = 'image_100x38';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_89x33 = 'image_89x33';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_118x45 = 'image_118x45';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_48x25 = 'image_48x25';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_40x40 = 'image_40x40';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_197x152 = 'image_197x152';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_120x80 = 'image_120x80';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_82x82 = 'image_82x82';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_617x145 = 'image_617x145';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_297x146 = 'image_297x146';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_72x72 = 'image_72x72';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_270x260 = 'image_270x260';
const String _jsonKeyAuthDataUserSellerProfileBannerImage_320x320 = 'image_320x320';
class AuthDataUserSellerProfileBanner {
/*
{
  "storage": "local",
  "original_image": "images/seller/20220609124152-seller_banner4.jpg",
  "image_100x38": "",
  "image_89x33": "",
  "image_118x45": "",
  "image_48x25": "",
  "image_40x40": "",
  "image_197x152": "",
  "image_120x80": "",
  "image_82x82": "",
  "image_617x145": "images/seller/20220609124152-seller_banner-617x14521.png",
  "image_297x146": "images/seller/20220609124152-seller_banner-297x14650.png",
  "image_72x72": "images/seller/20220609124152image_small_twoseller_banner250.jpg",
  "image_270x260": "",
  "image_320x320": ""
}
*/

  String? storage;
  String? originalImage;
  String? image_100x38;
  String? image_89x33;
  String? image_118x45;
  String? image_48x25;
  String? image_40x40;
  String? image_197x152;
  String? image_120x80;
  String? image_82x82;
  String? image_617x145;
  String? image_297x146;
  String? image_72x72;
  String? image_270x260;
  String? image_320x320;

  AuthDataUserSellerProfileBanner({
    this.storage,
    this.originalImage,
    this.image_100x38,
    this.image_89x33,
    this.image_118x45,
    this.image_48x25,
    this.image_40x40,
    this.image_197x152,
    this.image_120x80,
    this.image_82x82,
    this.image_617x145,
    this.image_297x146,
    this.image_72x72,
    this.image_270x260,
    this.image_320x320,
  });
  AuthDataUserSellerProfileBanner.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyAuthDataUserSellerProfileBannerStorage]?.toString();
    originalImage = json[_jsonKeyAuthDataUserSellerProfileBannerOriginalImage]?.toString();
    image_100x38 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_100x38]?.toString();
    image_89x33 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_89x33]?.toString();
    image_118x45 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_118x45]?.toString();
    image_48x25 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_48x25]?.toString();
    image_40x40 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_40x40]?.toString();
    image_197x152 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_197x152]?.toString();
    image_120x80 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_120x80]?.toString();
    image_82x82 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_82x82]?.toString();
    image_617x145 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_617x145]?.toString();
    image_297x146 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_297x146]?.toString();
    image_72x72 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_72x72]?.toString();
    image_270x260 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_270x260]?.toString();
    image_320x320 = json[_jsonKeyAuthDataUserSellerProfileBannerImage_320x320]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserSellerProfileBannerStorage] = storage;
    data[_jsonKeyAuthDataUserSellerProfileBannerOriginalImage] = originalImage;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_100x38] = image_100x38;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_89x33] = image_89x33;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_118x45] = image_118x45;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_48x25] = image_48x25;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_40x40] = image_40x40;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_197x152] = image_197x152;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_120x80] = image_120x80;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_82x82] = image_82x82;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_617x145] = image_617x145;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_297x146] = image_297x146;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_72x72] = image_72x72;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_270x260] = image_270x260;
    data[_jsonKeyAuthDataUserSellerProfileBannerImage_320x320] = image_320x320;
    return data;
  }
}

const String _jsonKeyAuthDataUserSellerProfileLogoStorage = 'storage';
const String _jsonKeyAuthDataUserSellerProfileLogoOriginalImage = 'original_image';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_100x38 = 'image_100x38';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_89x33 = 'image_89x33';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_118x45 = 'image_118x45';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_48x25 = 'image_48x25';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_40x40 = 'image_40x40';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_197x152 = 'image_197x152';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_120x80 = 'image_120x80';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_82x82 = 'image_82x82';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_617x145 = 'image_617x145';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_297x146 = 'image_297x146';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_72x72 = 'image_72x72';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_270x260 = 'image_270x260';
const String _jsonKeyAuthDataUserSellerProfileLogoImage_320x320 = 'image_320x320';
class AuthDataUserSellerProfileLogo {
/*
{
  "storage": "local",
  "original_image": "images/seller/20220609124152-seller_logo304.jpg",
  "image_100x38": "",
  "image_89x33": "",
  "image_118x45": "",
  "image_48x25": "",
  "image_40x40": "",
  "image_197x152": "images/seller/20220609124152-seller_logo-197x15215.jpg",
  "image_120x80": "images/seller/20220609124152-seller_logo-120x809.jpg",
  "image_82x82": "images/seller/20220609124152-seller_logo-79x7948.jpg",
  "image_617x145": "",
  "image_297x146": "",
  "image_72x72": "images/seller/20220609124152image_small_twoseller_logo250.jpg",
  "image_270x260": "",
  "image_320x320": "images/seller/20220609124152-seller_logo-320x32043.jpg"
}
*/

  String? storage;
  String? originalImage;
  String? image_100x38;
  String? image_89x33;
  String? image_118x45;
  String? image_48x25;
  String? image_40x40;
  String? image_197x152;
  String? image_120x80;
  String? image_82x82;
  String? image_617x145;
  String? image_297x146;
  String? image_72x72;
  String? image_270x260;
  String? image_320x320;

  AuthDataUserSellerProfileLogo({
    this.storage,
    this.originalImage,
    this.image_100x38,
    this.image_89x33,
    this.image_118x45,
    this.image_48x25,
    this.image_40x40,
    this.image_197x152,
    this.image_120x80,
    this.image_82x82,
    this.image_617x145,
    this.image_297x146,
    this.image_72x72,
    this.image_270x260,
    this.image_320x320,
  });
  AuthDataUserSellerProfileLogo.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyAuthDataUserSellerProfileLogoStorage]?.toString();
    originalImage = json[_jsonKeyAuthDataUserSellerProfileLogoOriginalImage]?.toString();
    image_100x38 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_100x38]?.toString();
    image_89x33 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_89x33]?.toString();
    image_118x45 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_118x45]?.toString();
    image_48x25 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_48x25]?.toString();
    image_40x40 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_40x40]?.toString();
    image_197x152 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_197x152]?.toString();
    image_120x80 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_120x80]?.toString();
    image_82x82 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_82x82]?.toString();
    image_617x145 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_617x145]?.toString();
    image_297x146 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_297x146]?.toString();
    image_72x72 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_72x72]?.toString();
    image_270x260 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_270x260]?.toString();
    image_320x320 = json[_jsonKeyAuthDataUserSellerProfileLogoImage_320x320]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserSellerProfileLogoStorage] = storage;
    data[_jsonKeyAuthDataUserSellerProfileLogoOriginalImage] = originalImage;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_100x38] = image_100x38;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_89x33] = image_89x33;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_118x45] = image_118x45;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_48x25] = image_48x25;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_40x40] = image_40x40;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_197x152] = image_197x152;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_120x80] = image_120x80;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_82x82] = image_82x82;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_617x145] = image_617x145;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_297x146] = image_297x146;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_72x72] = image_72x72;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_270x260] = image_270x260;
    data[_jsonKeyAuthDataUserSellerProfileLogoImage_320x320] = image_320x320;
    return data;
  }
}

const String _jsonKeyAuthDataUserSellerProfileTaxPaperStorage = 'storage';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperOriginalImage = 'original_image';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperImage_40x40 = 'image_40x40';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperImage_72x72 = 'image_72x72';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperImage_190x230 = 'image_190x230';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperImage_110x122 = 'image_110x122';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperImage_320x320 = 'image_320x320';
const String _jsonKeyAuthDataUserSellerProfileTaxPaperImageThumbnail = 'image_thumbnail';
class AuthDataUserSellerProfileTaxPaper {
/*
{
  "storage": "local",
  "original_image": "images/20220609124152_original__shop_40.jpg",
  "image_40x40": "images/20220609124152image_40x40_shop_308.png",
  "image_72x72": "images/20220609124152image_72x72_shop_27.png",
  "image_190x230": "images/20220609124152image_190x230_shop_102.png",
  "image_110x122": "images/20220609124152image_110x122_shop_76.png",
  "image_320x320": "images/20220609124152image_300x200_shop_484.png",
  "image_thumbnail": "images/20220609124152image_thumbnail_shop_311.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;

  AuthDataUserSellerProfileTaxPaper({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
  });
  AuthDataUserSellerProfileTaxPaper.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyAuthDataUserSellerProfileTaxPaperStorage]?.toString();
    originalImage = json[_jsonKeyAuthDataUserSellerProfileTaxPaperOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyAuthDataUserSellerProfileTaxPaperImageThumbnail]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperStorage] = storage;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperOriginalImage] = originalImage;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_40x40] = image_40x40;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_72x72] = image_72x72;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_190x230] = image_190x230;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_110x122] = image_110x122;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperImage_320x320] = image_320x320;
    data[_jsonKeyAuthDataUserSellerProfileTaxPaperImageThumbnail] = imageThumbnail;
    return data;
  }
}

class AuthDataUserSellerProfile {
/*
{
  "id": 20,
  "user_id": "38",
  "shop_name": "Wallace Norman",
  "slug": "incididunt-eum-conse",
  "verified_at": "2022-05-28 09:04:37",
  "license_no": "Aliquid deleniti rem",
  "tax_paper": {
    "storage": "local",
    "original_image": "images/20220609124152_original__shop_40.jpg",
    "image_40x40": "images/20220609124152image_40x40_shop_308.png",
    "image_72x72": "images/20220609124152image_72x72_shop_27.png",
    "image_190x230": "images/20220609124152image_190x230_shop_102.png",
    "image_110x122": "images/20220609124152image_110x122_shop_76.png",
    "image_320x320": "images/20220609124152image_300x200_shop_484.png",
    "image_thumbnail": "images/20220609124152image_thumbnail_shop_311.png"
  },
  "logo": {
    "storage": "local",
    "original_image": "images/seller/20220609124152-seller_logo304.jpg",
    "image_100x38": "",
    "image_89x33": "",
    "image_118x45": "",
    "image_48x25": "",
    "image_40x40": "",
    "image_197x152": "images/seller/20220609124152-seller_logo-197x15215.jpg",
    "image_120x80": "images/seller/20220609124152-seller_logo-120x809.jpg",
    "image_82x82": "images/seller/20220609124152-seller_logo-79x7948.jpg",
    "image_617x145": "",
    "image_297x146": "",
    "image_72x72": "images/seller/20220609124152image_small_twoseller_logo250.jpg",
    "image_270x260": "",
    "image_320x320": "images/seller/20220609124152-seller_logo-320x32043.jpg"
  },
  "banner": {
    "storage": "local",
    "original_image": "images/seller/20220609124152-seller_banner4.jpg",
    "image_100x38": "",
    "image_89x33": "",
    "image_118x45": "",
    "image_48x25": "",
    "image_40x40": "",
    "image_197x152": "",
    "image_120x80": "",
    "image_82x82": "",
    "image_617x145": "images/seller/20220609124152-seller_banner-617x14521.png",
    "image_297x146": "images/seller/20220609124152-seller_banner-297x14650.png",
    "image_72x72": "images/seller/20220609124152image_small_twoseller_banner250.jpg",
    "image_270x260": "",
    "image_320x320": ""
  },
  "shop_page_contents": [
    {
      "new_arrival": "1"
    }
  ],
  "shop_banner_id": "151",
  "shop_banner": {
    "storage": "local",
    "original_image": "images/20220609120453_original__media_39.jpg",
    "image_40x40": "images/20220609120453image_40x40_media_243.png",
    "image_72x72": "images/20220609120453image_72x72_media_99.png",
    "image_190x230": "images/20220609120537image_190x230-63.png",
    "image_110x122": "images/20220609120453image_110x122_media_85.png",
    "image_320x320": "images/20220609120453image_300x200_media_50.png",
    "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
    "image_1905x350": "images/20220609124152image_1905x350-71.png"
  },
  "shop_tagline": "shop demo tagline",
  "phone_no": "+1 (631) 788-2122",
  "shop_email": "demo@gmail.com",
  "website": "",
  "address": "Consectetur facere",
  "rating_count": "0",
  "reviews_count": "0",
  "facebook": "https://facebook.com/0xNajmul",
  "google": "https://facebook.com/0xNajmul",
  "twitter": "https://facebook.com/0xNajmul",
  "youtube": "https://facebook.com/0xNajmul",
  "meta_title": "Ut eiusmod consectet",
  "meta_description": "Maxime voluptatem N",
  "state_id": "3",
  "city_id": "1",
  "town_id": "3",
  "latitude": "51.51301544839645",
  "longitude": "-0.013046655273429852",
  "schedule_id": "5",
  "account_type": "Ultimate",
  "shop_type_id": "1",
  "created_at": "2022-05-28T02:44:04.000000Z",
  "updated_at": "2022-06-09T06:41:52.000000Z",
  "image_105x75": "https://hurrybuzz.com/public/images/default/105x75_no_bg.png",
  "image_197x152": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-197x15215.jpg",
  "image_1905x350": "https://hurrybuzz.com/public/images/20220609124152image_1905x350-71.png",
  "image_90x60": "https://hurrybuzz.com/public/images/seller/20220609124152image_small_twoseller_logo250.jpg",
  "image_82x82": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-79x7948.jpg",
  "image_120x80": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-120x809.jpg",
  "image_297x146": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-297x14650.png",
  "image_617x145": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-617x14521.png",
  "start_date": "28 May 2022",
  "image_1920x412": "https://hurrybuzz.com/public/images/default/default-image-1920x412.png"
}
*/

  int? id;
  String? userId;
  String? shopName;
  String? slug;
  String? verifiedAt;
  String? licenseNo;
  AuthDataUserSellerProfileTaxPaper? taxPaper;
  AuthDataUserSellerProfileLogo? logo;
  AuthDataUserSellerProfileBanner? banner;
  List<AuthDataUserSellerProfileShopPageContents?>? shopPageContents;
  String? shopBannerId;
  AuthDataUserSellerProfileShopBanner? shopBanner;
  String? shopTagline;
  String? phoneNo;
  String? shopEmail;
  String? website;
  String? address;
  String? ratingCount;
  String? reviewsCount;
  String? facebook;
  String? google;
  String? twitter;
  String? youtube;
  String? metaTitle;
  String? metaDescription;
  String? stateId;
  String? cityId;
  String? townId;
  String? latitude;
  String? longitude;
  String? scheduleId;
  String? accountType;
  String? shopTypeId;
  String? createdAt;
  String? updatedAt;
  String? image_105x75;
  String? image_197x152;
  String? image_1905x350;
  String? image_90x60;
  String? image_82x82;
  String? image_120x80;
  String? image_297x146;
  String? image_617x145;
  String? startDate;
  String? image_1920x412;

  AuthDataUserSellerProfile({
    this.id,
    this.userId,
    this.shopName,
    this.slug,
    this.verifiedAt,
    this.licenseNo,
    this.taxPaper,
    this.logo,
    this.banner,
    this.shopPageContents,
    this.shopBannerId,
    this.shopBanner,
    this.shopTagline,
    this.phoneNo,
    this.shopEmail,
    this.website,
    this.address,
    this.ratingCount,
    this.reviewsCount,
    this.facebook,
    this.google,
    this.twitter,
    this.youtube,
    this.metaTitle,
    this.metaDescription,
    this.stateId,
    this.cityId,
    this.townId,
    this.latitude,
    this.longitude,
    this.scheduleId,
    this.accountType,
    this.shopTypeId,
    this.createdAt,
    this.updatedAt,
    this.image_105x75,
    this.image_197x152,
    this.image_1905x350,
    this.image_90x60,
    this.image_82x82,
    this.image_120x80,
    this.image_297x146,
    this.image_617x145,
    this.startDate,
    this.image_1920x412,
  });
  AuthDataUserSellerProfile.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyAuthDataUserSellerProfileId]?.toInt();
    userId = json[_jsonKeyAuthDataUserSellerProfileUserId]?.toString();
    shopName = json[_jsonKeyAuthDataUserSellerProfileShopName]?.toString();
    slug = json[_jsonKeyAuthDataUserSellerProfileSlug]?.toString();
    verifiedAt = json[_jsonKeyAuthDataUserSellerProfileVerifiedAt]?.toString();
    licenseNo = json[_jsonKeyAuthDataUserSellerProfileLicenseNo]?.toString();
    taxPaper = (json[_jsonKeyAuthDataUserSellerProfileTaxPaper] != null) ? AuthDataUserSellerProfileTaxPaper.fromJson(json[_jsonKeyAuthDataUserSellerProfileTaxPaper]) : null;
    logo = (json[_jsonKeyAuthDataUserSellerProfileLogo] != null) ? AuthDataUserSellerProfileLogo.fromJson(json[_jsonKeyAuthDataUserSellerProfileLogo]) : null;
    banner = (json[_jsonKeyAuthDataUserSellerProfileBanner] != null) ? AuthDataUserSellerProfileBanner.fromJson(json[_jsonKeyAuthDataUserSellerProfileBanner]) : null;
    if (json[_jsonKeyAuthDataUserSellerProfileShopPageContents] != null) {
      final v = json[_jsonKeyAuthDataUserSellerProfileShopPageContents];
      final arr0 = <AuthDataUserSellerProfileShopPageContents>[];
      v.forEach((v) {
        arr0.add(AuthDataUserSellerProfileShopPageContents.fromJson(v));
      });
      shopPageContents = arr0;
    }
    shopBannerId = json[_jsonKeyAuthDataUserSellerProfileShopBannerId]?.toString();
    shopBanner = (json[_jsonKeyAuthDataUserSellerProfileShopBanner] != null) ? AuthDataUserSellerProfileShopBanner.fromJson(json[_jsonKeyAuthDataUserSellerProfileShopBanner]) : null;
    shopTagline = json[_jsonKeyAuthDataUserSellerProfileShopTagline]?.toString();
    phoneNo = json[_jsonKeyAuthDataUserSellerProfilePhoneNo]?.toString();
    shopEmail = json[_jsonKeyAuthDataUserSellerProfileShopEmail]?.toString();
    website = json[_jsonKeyAuthDataUserSellerProfileWebsite]?.toString();
    address = json[_jsonKeyAuthDataUserSellerProfileAddress]?.toString();
    ratingCount = json[_jsonKeyAuthDataUserSellerProfileRatingCount]?.toString();
    reviewsCount = json[_jsonKeyAuthDataUserSellerProfileReviewsCount]?.toString();
    facebook = json[_jsonKeyAuthDataUserSellerProfileFacebook]?.toString();
    google = json[_jsonKeyAuthDataUserSellerProfileGoogle]?.toString();
    twitter = json[_jsonKeyAuthDataUserSellerProfileTwitter]?.toString();
    youtube = json[_jsonKeyAuthDataUserSellerProfileYoutube]?.toString();
    metaTitle = json[_jsonKeyAuthDataUserSellerProfileMetaTitle]?.toString();
    metaDescription = json[_jsonKeyAuthDataUserSellerProfileMetaDescription]?.toString();
    stateId = json[_jsonKeyAuthDataUserSellerProfileStateId]?.toString();
    cityId = json[_jsonKeyAuthDataUserSellerProfileCityId]?.toString();
    townId = json[_jsonKeyAuthDataUserSellerProfileTownId]?.toString();
    latitude = json[_jsonKeyAuthDataUserSellerProfileLatitude]?.toString();
    longitude = json[_jsonKeyAuthDataUserSellerProfileLongitude]?.toString();
    scheduleId = json[_jsonKeyAuthDataUserSellerProfileScheduleId]?.toString();
    accountType = json[_jsonKeyAuthDataUserSellerProfileAccountType]?.toString();
    shopTypeId = json[_jsonKeyAuthDataUserSellerProfileShopTypeId]?.toString();
    createdAt = json[_jsonKeyAuthDataUserSellerProfileCreatedAt]?.toString();
    updatedAt = json[_jsonKeyAuthDataUserSellerProfileUpdatedAt]?.toString();
    image_105x75 = json[_jsonKeyAuthDataUserSellerProfileImage_105x75]?.toString();
    image_197x152 = json[_jsonKeyAuthDataUserSellerProfileImage_197x152]?.toString();
    image_1905x350 = json[_jsonKeyAuthDataUserSellerProfileImage_1905x350]?.toString();
    image_90x60 = json[_jsonKeyAuthDataUserSellerProfileImage_90x60]?.toString();
    image_82x82 = json[_jsonKeyAuthDataUserSellerProfileImage_82x82]?.toString();
    image_120x80 = json[_jsonKeyAuthDataUserSellerProfileImage_120x80]?.toString();
    image_297x146 = json[_jsonKeyAuthDataUserSellerProfileImage_297x146]?.toString();
    image_617x145 = json[_jsonKeyAuthDataUserSellerProfileImage_617x145]?.toString();
    startDate = json[_jsonKeyAuthDataUserSellerProfileStartDate]?.toString();
    image_1920x412 = json[_jsonKeyAuthDataUserSellerProfileImage_1920x412]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserSellerProfileId] = id;
    data[_jsonKeyAuthDataUserSellerProfileUserId] = userId;
    data[_jsonKeyAuthDataUserSellerProfileShopName] = shopName;
    data[_jsonKeyAuthDataUserSellerProfileSlug] = slug;
    data[_jsonKeyAuthDataUserSellerProfileVerifiedAt] = verifiedAt;
    data[_jsonKeyAuthDataUserSellerProfileLicenseNo] = licenseNo;
    if (taxPaper != null) {
      data[_jsonKeyAuthDataUserSellerProfileTaxPaper] = taxPaper!.toJson();
    }
    if (logo != null) {
      data[_jsonKeyAuthDataUserSellerProfileLogo] = logo!.toJson();
    }
    if (banner != null) {
      data[_jsonKeyAuthDataUserSellerProfileBanner] = banner!.toJson();
    }
    if (shopPageContents != null) {
      final v = shopPageContents;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyAuthDataUserSellerProfileShopPageContents] = arr0;
    }
    data[_jsonKeyAuthDataUserSellerProfileShopBannerId] = shopBannerId;
    if (shopBanner != null) {
      data[_jsonKeyAuthDataUserSellerProfileShopBanner] = shopBanner!.toJson();
    }
    data[_jsonKeyAuthDataUserSellerProfileShopTagline] = shopTagline;
    data[_jsonKeyAuthDataUserSellerProfilePhoneNo] = phoneNo;
    data[_jsonKeyAuthDataUserSellerProfileShopEmail] = shopEmail;
    data[_jsonKeyAuthDataUserSellerProfileWebsite] = website;
    data[_jsonKeyAuthDataUserSellerProfileAddress] = address;
    data[_jsonKeyAuthDataUserSellerProfileRatingCount] = ratingCount;
    data[_jsonKeyAuthDataUserSellerProfileReviewsCount] = reviewsCount;
    data[_jsonKeyAuthDataUserSellerProfileFacebook] = facebook;
    data[_jsonKeyAuthDataUserSellerProfileGoogle] = google;
    data[_jsonKeyAuthDataUserSellerProfileTwitter] = twitter;
    data[_jsonKeyAuthDataUserSellerProfileYoutube] = youtube;
    data[_jsonKeyAuthDataUserSellerProfileMetaTitle] = metaTitle;
    data[_jsonKeyAuthDataUserSellerProfileMetaDescription] = metaDescription;
    data[_jsonKeyAuthDataUserSellerProfileStateId] = stateId;
    data[_jsonKeyAuthDataUserSellerProfileCityId] = cityId;
    data[_jsonKeyAuthDataUserSellerProfileTownId] = townId;
    data[_jsonKeyAuthDataUserSellerProfileLatitude] = latitude;
    data[_jsonKeyAuthDataUserSellerProfileLongitude] = longitude;
    data[_jsonKeyAuthDataUserSellerProfileScheduleId] = scheduleId;
    data[_jsonKeyAuthDataUserSellerProfileAccountType] = accountType;
    data[_jsonKeyAuthDataUserSellerProfileShopTypeId] = shopTypeId;
    data[_jsonKeyAuthDataUserSellerProfileCreatedAt] = createdAt;
    data[_jsonKeyAuthDataUserSellerProfileUpdatedAt] = updatedAt;
    data[_jsonKeyAuthDataUserSellerProfileImage_105x75] = image_105x75;
    data[_jsonKeyAuthDataUserSellerProfileImage_197x152] = image_197x152;
    data[_jsonKeyAuthDataUserSellerProfileImage_1905x350] = image_1905x350;
    data[_jsonKeyAuthDataUserSellerProfileImage_90x60] = image_90x60;
    data[_jsonKeyAuthDataUserSellerProfileImage_82x82] = image_82x82;
    data[_jsonKeyAuthDataUserSellerProfileImage_120x80] = image_120x80;
    data[_jsonKeyAuthDataUserSellerProfileImage_297x146] = image_297x146;
    data[_jsonKeyAuthDataUserSellerProfileImage_617x145] = image_617x145;
    data[_jsonKeyAuthDataUserSellerProfileStartDate] = startDate;
    data[_jsonKeyAuthDataUserSellerProfileImage_1920x412] = image_1920x412;
    return data;
  }
}

const String _jsonKeyAuthDataUserBillingAddressId = 'id';
const String _jsonKeyAuthDataUserBillingAddressUserId = 'user_id';
const String _jsonKeyAuthDataUserBillingAddressName = 'name';
const String _jsonKeyAuthDataUserBillingAddressEmail = 'email';
const String _jsonKeyAuthDataUserBillingAddressPhoneNo = 'phone_no';
const String _jsonKeyAuthDataUserBillingAddressAddress = 'address';
const String _jsonKeyAuthDataUserBillingAddressAddressIds = 'address_ids';
const String _jsonKeyAuthDataUserBillingAddressCountry = 'country';
const String _jsonKeyAuthDataUserBillingAddressState = 'state';
const String _jsonKeyAuthDataUserBillingAddressCity = 'city';
const String _jsonKeyAuthDataUserBillingAddressLatitude = 'latitude';
const String _jsonKeyAuthDataUserBillingAddressLongitude = 'longitude';
const String _jsonKeyAuthDataUserBillingAddressPostalCode = 'postal_code';
const String _jsonKeyAuthDataUserBillingAddressDefaultShipping = 'default_shipping';
const String _jsonKeyAuthDataUserBillingAddressDefaultBilling = 'default_billing';
const String _jsonKeyAuthDataUserBillingAddressCreatedAt = 'created_at';
const String _jsonKeyAuthDataUserBillingAddressUpdatedAt = 'updated_at';
const String _jsonKeyAuthDataUserBillingAddressAddressIdsCountryId = 'country_id';
const String _jsonKeyAuthDataUserBillingAddressAddressIdsStateId = 'state_id';
const String _jsonKeyAuthDataUserBillingAddressAddressIdsCityId = 'city_id';
class AuthDataUserBillingAddressAddressIds {
/*
{
  "country_id": "19",
  "state_id": "3",
  "city_id": "1"
}
*/

  String? countryId;
  String? stateId;
  String? cityId;

  AuthDataUserBillingAddressAddressIds({
    this.countryId,
    this.stateId,
    this.cityId,
  });
  AuthDataUserBillingAddressAddressIds.fromJson(Map<String, dynamic> json) {
    countryId = json[_jsonKeyAuthDataUserBillingAddressAddressIdsCountryId]?.toString();
    stateId = json[_jsonKeyAuthDataUserBillingAddressAddressIdsStateId]?.toString();
    cityId = json[_jsonKeyAuthDataUserBillingAddressAddressIdsCityId]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserBillingAddressAddressIdsCountryId] = countryId;
    data[_jsonKeyAuthDataUserBillingAddressAddressIdsStateId] = stateId;
    data[_jsonKeyAuthDataUserBillingAddressAddressIdsCityId] = cityId;
    return data;
  }
}

class AuthDataUserBillingAddress {
/*
{
  "id": 4,
  "user_id": "38",
  "name": "Plan Outs",
  "email": "planouts24@gmail.com",
  "phone_no": "+880 3535 353",
  "address": "Muhammadpur , Dhaka\nDhaka",
  "address_ids": {
    "country_id": "19",
    "state_id": "3",
    "city_id": "1"
  },
  "country": "Bangladesh",
  "state": "Dhaka",
  "city": "Dhaka",
  "latitude": null,
  "longitude": null,
  "postal_code": "1207",
  "default_shipping": "1",
  "default_billing": "1",
  "created_at": "2022-06-09T06:11:11.000000Z",
  "updated_at": "2022-06-09T06:11:11.000000Z"
}
*/

  int? id;
  String? userId;
  String? name;
  String? email;
  String? phoneNo;
  String? address;
  AuthDataUserBillingAddressAddressIds? addressIds;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? postalCode;
  String? defaultShipping;
  String? defaultBilling;
  String? createdAt;
  String? updatedAt;

  AuthDataUserBillingAddress({
    this.id,
    this.userId,
    this.name,
    this.email,
    this.phoneNo,
    this.address,
    this.addressIds,
    this.country,
    this.state,
    this.city,
    this.latitude,
    this.longitude,
    this.postalCode,
    this.defaultShipping,
    this.defaultBilling,
    this.createdAt,
    this.updatedAt,
  });
  AuthDataUserBillingAddress.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyAuthDataUserBillingAddressId]?.toInt();
    userId = json[_jsonKeyAuthDataUserBillingAddressUserId]?.toString();
    name = json[_jsonKeyAuthDataUserBillingAddressName]?.toString();
    email = json[_jsonKeyAuthDataUserBillingAddressEmail]?.toString();
    phoneNo = json[_jsonKeyAuthDataUserBillingAddressPhoneNo]?.toString();
    address = json[_jsonKeyAuthDataUserBillingAddressAddress]?.toString();
    addressIds = (json[_jsonKeyAuthDataUserBillingAddressAddressIds] != null) ? AuthDataUserBillingAddressAddressIds.fromJson(json[_jsonKeyAuthDataUserBillingAddressAddressIds]) : null;
    country = json[_jsonKeyAuthDataUserBillingAddressCountry]?.toString();
    state = json[_jsonKeyAuthDataUserBillingAddressState]?.toString();
    city = json[_jsonKeyAuthDataUserBillingAddressCity]?.toString();
    latitude = json[_jsonKeyAuthDataUserBillingAddressLatitude]?.toString();
    longitude = json[_jsonKeyAuthDataUserBillingAddressLongitude]?.toString();
    postalCode = json[_jsonKeyAuthDataUserBillingAddressPostalCode]?.toString();
    defaultShipping = json[_jsonKeyAuthDataUserBillingAddressDefaultShipping]?.toString();
    defaultBilling = json[_jsonKeyAuthDataUserBillingAddressDefaultBilling]?.toString();
    createdAt = json[_jsonKeyAuthDataUserBillingAddressCreatedAt]?.toString();
    updatedAt = json[_jsonKeyAuthDataUserBillingAddressUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserBillingAddressId] = id;
    data[_jsonKeyAuthDataUserBillingAddressUserId] = userId;
    data[_jsonKeyAuthDataUserBillingAddressName] = name;
    data[_jsonKeyAuthDataUserBillingAddressEmail] = email;
    data[_jsonKeyAuthDataUserBillingAddressPhoneNo] = phoneNo;
    data[_jsonKeyAuthDataUserBillingAddressAddress] = address;
    if (addressIds != null) {
      data[_jsonKeyAuthDataUserBillingAddressAddressIds] = addressIds!.toJson();
    }
    data[_jsonKeyAuthDataUserBillingAddressCountry] = country;
    data[_jsonKeyAuthDataUserBillingAddressState] = state;
    data[_jsonKeyAuthDataUserBillingAddressCity] = city;
    data[_jsonKeyAuthDataUserBillingAddressLatitude] = latitude;
    data[_jsonKeyAuthDataUserBillingAddressLongitude] = longitude;
    data[_jsonKeyAuthDataUserBillingAddressPostalCode] = postalCode;
    data[_jsonKeyAuthDataUserBillingAddressDefaultShipping] = defaultShipping;
    data[_jsonKeyAuthDataUserBillingAddressDefaultBilling] = defaultBilling;
    data[_jsonKeyAuthDataUserBillingAddressCreatedAt] = createdAt;
    data[_jsonKeyAuthDataUserBillingAddressUpdatedAt] = updatedAt;
    return data;
  }
}

const String _jsonKeyAuthDataUserShippingAddressId = 'id';
const String _jsonKeyAuthDataUserShippingAddressUserId = 'user_id';
const String _jsonKeyAuthDataUserShippingAddressName = 'name';
const String _jsonKeyAuthDataUserShippingAddressEmail = 'email';
const String _jsonKeyAuthDataUserShippingAddressPhoneNo = 'phone_no';
const String _jsonKeyAuthDataUserShippingAddressAddress = 'address';
const String _jsonKeyAuthDataUserShippingAddressAddressIds = 'address_ids';
const String _jsonKeyAuthDataUserShippingAddressCountry = 'country';
const String _jsonKeyAuthDataUserShippingAddressState = 'state';
const String _jsonKeyAuthDataUserShippingAddressCity = 'city';
const String _jsonKeyAuthDataUserShippingAddressLatitude = 'latitude';
const String _jsonKeyAuthDataUserShippingAddressLongitude = 'longitude';
const String _jsonKeyAuthDataUserShippingAddressPostalCode = 'postal_code';
const String _jsonKeyAuthDataUserShippingAddressDefaultShipping = 'default_shipping';
const String _jsonKeyAuthDataUserShippingAddressDefaultBilling = 'default_billing';
const String _jsonKeyAuthDataUserShippingAddressCreatedAt = 'created_at';
const String _jsonKeyAuthDataUserShippingAddressUpdatedAt = 'updated_at';
const String _jsonKeyAuthDataUserShippingAddressAddressIdsCountryId = 'country_id';
const String _jsonKeyAuthDataUserShippingAddressAddressIdsStateId = 'state_id';
const String _jsonKeyAuthDataUserShippingAddressAddressIdsCityId = 'city_id';
class AuthDataUserShippingAddressAddressIds {
/*
{
  "country_id": "19",
  "state_id": "3",
  "city_id": "1"
}
*/

  String? countryId;
  String? stateId;
  String? cityId;

  AuthDataUserShippingAddressAddressIds({
    this.countryId,
    this.stateId,
    this.cityId,
  });
  AuthDataUserShippingAddressAddressIds.fromJson(Map<String, dynamic> json) {
    countryId = json[_jsonKeyAuthDataUserShippingAddressAddressIdsCountryId]?.toString();
    stateId = json[_jsonKeyAuthDataUserShippingAddressAddressIdsStateId]?.toString();
    cityId = json[_jsonKeyAuthDataUserShippingAddressAddressIdsCityId]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserShippingAddressAddressIdsCountryId] = countryId;
    data[_jsonKeyAuthDataUserShippingAddressAddressIdsStateId] = stateId;
    data[_jsonKeyAuthDataUserShippingAddressAddressIdsCityId] = cityId;
    return data;
  }
}

class AuthDataUserShippingAddress {
/*
{
  "id": 4,
  "user_id": "38",
  "name": "Plan Outs",
  "email": "planouts24@gmail.com",
  "phone_no": "+880 3535 353",
  "address": "Muhammadpur , Dhaka\nDhaka",
  "address_ids": {
    "country_id": "19",
    "state_id": "3",
    "city_id": "1"
  },
  "country": "Bangladesh",
  "state": "Dhaka",
  "city": "Dhaka",
  "latitude": null,
  "longitude": null,
  "postal_code": "1207",
  "default_shipping": "1",
  "default_billing": "1",
  "created_at": "2022-06-09T06:11:11.000000Z",
  "updated_at": "2022-06-09T06:11:11.000000Z"
}
*/

  int? id;
  String? userId;
  String? name;
  String? email;
  String? phoneNo;
  String? address;
  AuthDataUserShippingAddressAddressIds? addressIds;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? postalCode;
  String? defaultShipping;
  String? defaultBilling;
  String? createdAt;
  String? updatedAt;

  AuthDataUserShippingAddress({
    this.id,
    this.userId,
    this.name,
    this.email,
    this.phoneNo,
    this.address,
    this.addressIds,
    this.country,
    this.state,
    this.city,
    this.latitude,
    this.longitude,
    this.postalCode,
    this.defaultShipping,
    this.defaultBilling,
    this.createdAt,
    this.updatedAt,
  });
  AuthDataUserShippingAddress.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyAuthDataUserShippingAddressId]?.toInt();
    userId = json[_jsonKeyAuthDataUserShippingAddressUserId]?.toString();
    name = json[_jsonKeyAuthDataUserShippingAddressName]?.toString();
    email = json[_jsonKeyAuthDataUserShippingAddressEmail]?.toString();
    phoneNo = json[_jsonKeyAuthDataUserShippingAddressPhoneNo]?.toString();
    address = json[_jsonKeyAuthDataUserShippingAddressAddress]?.toString();
    addressIds = (json[_jsonKeyAuthDataUserShippingAddressAddressIds] != null) ? AuthDataUserShippingAddressAddressIds.fromJson(json[_jsonKeyAuthDataUserShippingAddressAddressIds]) : null;
    country = json[_jsonKeyAuthDataUserShippingAddressCountry]?.toString();
    state = json[_jsonKeyAuthDataUserShippingAddressState]?.toString();
    city = json[_jsonKeyAuthDataUserShippingAddressCity]?.toString();
    latitude = json[_jsonKeyAuthDataUserShippingAddressLatitude]?.toString();
    longitude = json[_jsonKeyAuthDataUserShippingAddressLongitude]?.toString();
    postalCode = json[_jsonKeyAuthDataUserShippingAddressPostalCode]?.toString();
    defaultShipping = json[_jsonKeyAuthDataUserShippingAddressDefaultShipping]?.toString();
    defaultBilling = json[_jsonKeyAuthDataUserShippingAddressDefaultBilling]?.toString();
    createdAt = json[_jsonKeyAuthDataUserShippingAddressCreatedAt]?.toString();
    updatedAt = json[_jsonKeyAuthDataUserShippingAddressUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserShippingAddressId] = id;
    data[_jsonKeyAuthDataUserShippingAddressUserId] = userId;
    data[_jsonKeyAuthDataUserShippingAddressName] = name;
    data[_jsonKeyAuthDataUserShippingAddressEmail] = email;
    data[_jsonKeyAuthDataUserShippingAddressPhoneNo] = phoneNo;
    data[_jsonKeyAuthDataUserShippingAddressAddress] = address;
    if (addressIds != null) {
      data[_jsonKeyAuthDataUserShippingAddressAddressIds] = addressIds!.toJson();
    }
    data[_jsonKeyAuthDataUserShippingAddressCountry] = country;
    data[_jsonKeyAuthDataUserShippingAddressState] = state;
    data[_jsonKeyAuthDataUserShippingAddressCity] = city;
    data[_jsonKeyAuthDataUserShippingAddressLatitude] = latitude;
    data[_jsonKeyAuthDataUserShippingAddressLongitude] = longitude;
    data[_jsonKeyAuthDataUserShippingAddressPostalCode] = postalCode;
    data[_jsonKeyAuthDataUserShippingAddressDefaultShipping] = defaultShipping;
    data[_jsonKeyAuthDataUserShippingAddressDefaultBilling] = defaultBilling;
    data[_jsonKeyAuthDataUserShippingAddressCreatedAt] = createdAt;
    data[_jsonKeyAuthDataUserShippingAddressUpdatedAt] = updatedAt;
    return data;
  }
}

const String _jsonKeyAuthDataUserImagesStorage = 'storage';
const String _jsonKeyAuthDataUserImagesOriginalImage = 'original_image';
const String _jsonKeyAuthDataUserImagesImage_40x40 = 'image_40x40';
const String _jsonKeyAuthDataUserImagesImage_128x128 = 'image_128x128';
const String _jsonKeyAuthDataUserImagesImage_20x20 = 'image_20x20';
class AuthDataUserImages {
/*
{
  "storage": "local",
  "original_image": "images/20220609124026-_staff_17.jpg",
  "image_40x40": "images/20220609124026image_40X40_staff_105.png",
  "image_128x128": "images/20220609124026image_thumbnail_staff_183.png",
  "image_20x20": "images/20220609124026image_20X20_staff_319.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_128x128;
  String? image_20x20;

  AuthDataUserImages({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_128x128,
    this.image_20x20,
  });
  AuthDataUserImages.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyAuthDataUserImagesStorage]?.toString();
    originalImage = json[_jsonKeyAuthDataUserImagesOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyAuthDataUserImagesImage_40x40]?.toString();
    image_128x128 = json[_jsonKeyAuthDataUserImagesImage_128x128]?.toString();
    image_20x20 = json[_jsonKeyAuthDataUserImagesImage_20x20]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserImagesStorage] = storage;
    data[_jsonKeyAuthDataUserImagesOriginalImage] = originalImage;
    data[_jsonKeyAuthDataUserImagesImage_40x40] = image_40x40;
    data[_jsonKeyAuthDataUserImagesImage_128x128] = image_128x128;
    data[_jsonKeyAuthDataUserImagesImage_20x20] = image_20x20;
    return data;
  }
}

class AuthDataUser {

  int? id;
  String? email;
  String? phone;
  String? firstName;
  String? lastName;
  String? userType;
  String? gender;
  String? dateOfBirth;
  String? status;
  String? isUserBanned;
  String? newsletterEnable;
  String? otp;
  String? firebaseAuthId;
  String? isPasswordSet;
  AuthDataUserImages? images;
  String? lastLogin;
  String? lastIp;
  String? lastPasswordChange;
  String? imageId;
  String? roleId;
  String? pickupHubId;
  String? balance;
  String? createdAt;
  String? updatedAt;
  String? profileImage;
  String? userProfileImage;
  String? fullName;
  AuthDataUserShippingAddress? shippingAddress;
  AuthDataUserBillingAddress? billingAddress;
  int? lastRecharge;
  AuthDataUserSellerProfile? sellerProfile;

  AuthDataUser({
    this.id,
    this.email,
    this.phone,
    this.firstName,
    this.lastName,
    this.userType,
    this.gender,
    this.dateOfBirth,
    this.status,
    this.isUserBanned,
    this.newsletterEnable,
    this.otp,
    this.firebaseAuthId,
    this.isPasswordSet,
    this.images,
    this.lastLogin,
    this.lastIp,
    this.lastPasswordChange,
    this.imageId,
    this.roleId,
    this.pickupHubId,
    this.balance,
    this.createdAt,
    this.updatedAt,
    this.profileImage,
    this.userProfileImage,
    this.fullName,
    this.shippingAddress,
    this.billingAddress,
    this.lastRecharge,
    this.sellerProfile,
  });
  AuthDataUser.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyAuthDataUserId]?.toInt();
    email = json[_jsonKeyAuthDataUserEmail]?.toString();
    phone = json[_jsonKeyAuthDataUserPhone]?.toString();
    firstName = json[_jsonKeyAuthDataUserFirstName]?.toString();
    lastName = json[_jsonKeyAuthDataUserLastName]?.toString();
    userType = json[_jsonKeyAuthDataUserUserType]?.toString();
    gender = json[_jsonKeyAuthDataUserGender]?.toString();
    dateOfBirth = json[_jsonKeyAuthDataUserDateOfBirth]?.toString();
    status = json[_jsonKeyAuthDataUserStatus]?.toString();
    isUserBanned = json[_jsonKeyAuthDataUserIsUserBanned]?.toString();
    newsletterEnable = json[_jsonKeyAuthDataUserNewsletterEnable]?.toString();
    otp = json[_jsonKeyAuthDataUserOtp]?.toString();
    firebaseAuthId = json[_jsonKeyAuthDataUserFirebaseAuthId]?.toString();
    isPasswordSet = json[_jsonKeyAuthDataUserIsPasswordSet]?.toString();
    images = (json[_jsonKeyAuthDataUserImages] != null) ? AuthDataUserImages.fromJson(json[_jsonKeyAuthDataUserImages]) : null;
    lastLogin = json[_jsonKeyAuthDataUserLastLogin]?.toString();
    lastIp = json[_jsonKeyAuthDataUserLastIp]?.toString();
    lastPasswordChange = json[_jsonKeyAuthDataUserLastPasswordChange]?.toString();
    imageId = json[_jsonKeyAuthDataUserImageId]?.toString();
    roleId = json[_jsonKeyAuthDataUserRoleId]?.toString();
    pickupHubId = json[_jsonKeyAuthDataUserPickupHubId]?.toString();
    balance = json[_jsonKeyAuthDataUserBalance]?.toString();
    createdAt = json[_jsonKeyAuthDataUserCreatedAt]?.toString();
    updatedAt = json[_jsonKeyAuthDataUserUpdatedAt]?.toString();
    profileImage = json[_jsonKeyAuthDataUserProfileImage]?.toString();
    userProfileImage = json[_jsonKeyAuthDataUserUserProfileImage]?.toString();
    fullName = json[_jsonKeyAuthDataUserFullName]?.toString();
    shippingAddress = (json[_jsonKeyAuthDataUserShippingAddress] != null) ? AuthDataUserShippingAddress.fromJson(json[_jsonKeyAuthDataUserShippingAddress]) : null;
    billingAddress = (json[_jsonKeyAuthDataUserBillingAddress] != null) ? AuthDataUserBillingAddress.fromJson(json[_jsonKeyAuthDataUserBillingAddress]) : null;
    lastRecharge = json[_jsonKeyAuthDataUserLastRecharge]?.toInt();
    sellerProfile = (json[_jsonKeyAuthDataUserSellerProfile] != null) ? AuthDataUserSellerProfile.fromJson(json[_jsonKeyAuthDataUserSellerProfile]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataUserId] = id;
    data[_jsonKeyAuthDataUserEmail] = email;
    data[_jsonKeyAuthDataUserPhone] = phone;
    data[_jsonKeyAuthDataUserFirstName] = firstName;
    data[_jsonKeyAuthDataUserLastName] = lastName;
    data[_jsonKeyAuthDataUserUserType] = userType;
    data[_jsonKeyAuthDataUserGender] = gender;
    data[_jsonKeyAuthDataUserDateOfBirth] = dateOfBirth;
    data[_jsonKeyAuthDataUserStatus] = status;
    data[_jsonKeyAuthDataUserIsUserBanned] = isUserBanned;
    data[_jsonKeyAuthDataUserNewsletterEnable] = newsletterEnable;
    data[_jsonKeyAuthDataUserOtp] = otp;
    data[_jsonKeyAuthDataUserFirebaseAuthId] = firebaseAuthId;
    data[_jsonKeyAuthDataUserIsPasswordSet] = isPasswordSet;
    if (images != null) {
      data[_jsonKeyAuthDataUserImages] = images!.toJson();
    }
    data[_jsonKeyAuthDataUserLastLogin] = lastLogin;
    data[_jsonKeyAuthDataUserLastIp] = lastIp;
    data[_jsonKeyAuthDataUserLastPasswordChange] = lastPasswordChange;
    data[_jsonKeyAuthDataUserImageId] = imageId;
    data[_jsonKeyAuthDataUserRoleId] = roleId;
    data[_jsonKeyAuthDataUserPickupHubId] = pickupHubId;
    data[_jsonKeyAuthDataUserBalance] = balance;
    data[_jsonKeyAuthDataUserCreatedAt] = createdAt;
    data[_jsonKeyAuthDataUserUpdatedAt] = updatedAt;
    data[_jsonKeyAuthDataUserProfileImage] = profileImage;
    data[_jsonKeyAuthDataUserUserProfileImage] = userProfileImage;
    data[_jsonKeyAuthDataUserFullName] = fullName;
    if (shippingAddress != null) {
      data[_jsonKeyAuthDataUserShippingAddress] = shippingAddress!.toJson();
    }
    if (billingAddress != null) {
      data[_jsonKeyAuthDataUserBillingAddress] = billingAddress!.toJson();
    }
    data[_jsonKeyAuthDataUserLastRecharge] = lastRecharge;
    if (sellerProfile != null) {
      data[_jsonKeyAuthDataUserSellerProfile] = sellerProfile!.toJson();
    }
    return data;
  }
}

class AuthData {

  String? token;
  AuthDataUser? user;

  AuthData({
    this.token,
    this.user,
  });
  AuthData.fromJson(Map<String, dynamic> json) {
    token = json[_jsonKeyAuthDataToken]?.toString();
    user = (json[_jsonKeyAuthDataUser] != null) ? AuthDataUser.fromJson(json[_jsonKeyAuthDataUser]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthDataToken] = token;
    if (user != null) {
      data[_jsonKeyAuthDataUser] = user!.toJson();
    }
    return data;
  }
}

class Auth {

  bool? success;
  String? message;
  AuthData? data;

  Auth({
    this.success,
    this.message,
    this.data,
  });
  Auth.fromJson(Map<String, dynamic> json) {
    success = json[_jsonKeyAuthSuccess]!;
    message = json[_jsonKeyAuthMessage]?.toString();
    data = (json[_jsonKeyAuthData] != null) ? AuthData.fromJson(json[_jsonKeyAuthData]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyAuthSuccess] = success;
    data[_jsonKeyAuthMessage] = message;
    if (data != null) {
      data[_jsonKeyAuthData] = this.data!.toJson();
    }
    return data;
  }
}
