///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyDashboardUser = 'user';
const String _jsonKeyDashboardTotalOrders = 'total_orders';
const String _jsonKeyDashboardTotalSales = 'total_sales';
const String _jsonKeyDashboardTotalProducts = 'total_products';
const String _jsonKeyDashboardTotalCampaign = 'total_campaign';
const String _jsonKeyDashboardPendingOrders = 'pending_orders';
const String _jsonKeyDashboardProcessingOrders = 'processing_orders';
const String _jsonKeyDashboardDeliveredOrders = 'delivered_orders';
const String _jsonKeyDashboardUserId = 'id';
const String _jsonKeyDashboardUserEmail = 'email';
const String _jsonKeyDashboardUserPhone = 'phone';
const String _jsonKeyDashboardUserFirstName = 'first_name';
const String _jsonKeyDashboardUserLastName = 'last_name';
const String _jsonKeyDashboardUserUserType = 'user_type';
const String _jsonKeyDashboardUserGender = 'gender';
const String _jsonKeyDashboardUserDateOfBirth = 'date_of_birth';
const String _jsonKeyDashboardUserStatus = 'status';
const String _jsonKeyDashboardUserIsUserBanned = 'is_user_banned';
const String _jsonKeyDashboardUserNewsletterEnable = 'newsletter_enable';
const String _jsonKeyDashboardUserOtp = 'otp';
const String _jsonKeyDashboardUserFirebaseAuthId = 'firebase_auth_id';
const String _jsonKeyDashboardUserIsPasswordSet = 'is_password_set';
const String _jsonKeyDashboardUserImages = 'images';
const String _jsonKeyDashboardUserLastLogin = 'last_login';
const String _jsonKeyDashboardUserLastIp = 'last_ip';
const String _jsonKeyDashboardUserLastPasswordChange = 'last_password_change';
const String _jsonKeyDashboardUserImageId = 'image_id';
const String _jsonKeyDashboardUserRoleId = 'role_id';
const String _jsonKeyDashboardUserPickupHubId = 'pickup_hub_id';
const String _jsonKeyDashboardUserBalance = 'balance';
const String _jsonKeyDashboardUserCreatedAt = 'created_at';
const String _jsonKeyDashboardUserUpdatedAt = 'updated_at';
const String _jsonKeyDashboardUserProfileImage = 'profile_image';
const String _jsonKeyDashboardUserUserProfileImage = 'user_profile_image';
const String _jsonKeyDashboardUserFullName = 'full_name';
const String _jsonKeyDashboardUserShippingAddress = 'shipping_address';
const String _jsonKeyDashboardUserBillingAddress = 'billing_address';
const String _jsonKeyDashboardUserLastRecharge = 'last_recharge';
const String _jsonKeyDashboardUserSellerProfile = 'seller_profile';
const String _jsonKeyDashboardUserSellerProfileId = 'id';
const String _jsonKeyDashboardUserSellerProfileUserId = 'user_id';
const String _jsonKeyDashboardUserSellerProfileShopName = 'shop_name';
const String _jsonKeyDashboardUserSellerProfileSlug = 'slug';
const String _jsonKeyDashboardUserSellerProfileVerifiedAt = 'verified_at';
const String _jsonKeyDashboardUserSellerProfileLicenseNo = 'license_no';
const String _jsonKeyDashboardUserSellerProfileTaxPaper = 'tax_paper';
const String _jsonKeyDashboardUserSellerProfileLogo = 'logo';
const String _jsonKeyDashboardUserSellerProfileBanner = 'banner';
const String _jsonKeyDashboardUserSellerProfileShopPageContents = 'shop_page_contents';
const String _jsonKeyDashboardUserSellerProfileShopBannerId = 'shop_banner_id';
const String _jsonKeyDashboardUserSellerProfileShopBanner = 'shop_banner';
const String _jsonKeyDashboardUserSellerProfileShopTagline = 'shop_tagline';
const String _jsonKeyDashboardUserSellerProfilePhoneNo = 'phone_no';
const String _jsonKeyDashboardUserSellerProfileShopEmail = 'shop_email';
const String _jsonKeyDashboardUserSellerProfileWebsite = 'website';
const String _jsonKeyDashboardUserSellerProfileAddress = 'address';
const String _jsonKeyDashboardUserSellerProfileRatingCount = 'rating_count';
const String _jsonKeyDashboardUserSellerProfileReviewsCount = 'reviews_count';
const String _jsonKeyDashboardUserSellerProfileFacebook = 'facebook';
const String _jsonKeyDashboardUserSellerProfileGoogle = 'google';
const String _jsonKeyDashboardUserSellerProfileTwitter = 'twitter';
const String _jsonKeyDashboardUserSellerProfileYoutube = 'youtube';
const String _jsonKeyDashboardUserSellerProfileMetaTitle = 'meta_title';
const String _jsonKeyDashboardUserSellerProfileMetaDescription = 'meta_description';
const String _jsonKeyDashboardUserSellerProfileStateId = 'state_id';
const String _jsonKeyDashboardUserSellerProfileCityId = 'city_id';
const String _jsonKeyDashboardUserSellerProfileTownId = 'town_id';
const String _jsonKeyDashboardUserSellerProfileLatitude = 'latitude';
const String _jsonKeyDashboardUserSellerProfileLongitude = 'longitude';
const String _jsonKeyDashboardUserSellerProfileScheduleId = 'schedule_id';
const String _jsonKeyDashboardUserSellerProfileAccountType = 'account_type';
const String _jsonKeyDashboardUserSellerProfileShopTypeId = 'shop_type_id';
const String _jsonKeyDashboardUserSellerProfileCreatedAt = 'created_at';
const String _jsonKeyDashboardUserSellerProfileUpdatedAt = 'updated_at';
const String _jsonKeyDashboardUserSellerProfileImage_105x75 = 'image_105x75';
const String _jsonKeyDashboardUserSellerProfileImage_197x152 = 'image_197x152';
const String _jsonKeyDashboardUserSellerProfileImage_1905x350 = 'image_1905x350';
const String _jsonKeyDashboardUserSellerProfileImage_90x60 = 'image_90x60';
const String _jsonKeyDashboardUserSellerProfileImage_82x82 = 'image_82x82';
const String _jsonKeyDashboardUserSellerProfileImage_120x80 = 'image_120x80';
const String _jsonKeyDashboardUserSellerProfileImage_297x146 = 'image_297x146';
const String _jsonKeyDashboardUserSellerProfileImage_617x145 = 'image_617x145';
const String _jsonKeyDashboardUserSellerProfileStartDate = 'start_date';
const String _jsonKeyDashboardUserSellerProfileImage_1920x412 = 'image_1920x412';
const String _jsonKeyDashboardUserSellerProfileShopBannerStorage = 'storage';
const String _jsonKeyDashboardUserSellerProfileShopBannerOriginalImage = 'original_image';
const String _jsonKeyDashboardUserSellerProfileShopBannerImage_40x40 = 'image_40x40';
const String _jsonKeyDashboardUserSellerProfileShopBannerImage_72x72 = 'image_72x72';
const String _jsonKeyDashboardUserSellerProfileShopBannerImage_190x230 = 'image_190x230';
const String _jsonKeyDashboardUserSellerProfileShopBannerImage_110x122 = 'image_110x122';
const String _jsonKeyDashboardUserSellerProfileShopBannerImage_320x320 = 'image_320x320';
const String _jsonKeyDashboardUserSellerProfileShopBannerImageThumbnail = 'image_thumbnail';
const String _jsonKeyDashboardUserSellerProfileShopBannerImage_1905x350 = 'image_1905x350';
class DashboardUserSellerProfileShopBanner {
/*
{
  "storage": "local",
  "original_image": "images/20220609120453_original__media_39.jpg",
  "image_40x40": "images/20220609120453image_40x40_media_243.png",
  "image_72x72": "images/20220609120453image_72x72_media_99.png",
  "image_190x230": "images/20220609120537image_190x230-63.png",
  "image_110x122": "images/20220609120453image_110x122_media_85.png",
  "image_320x320": "images/20220609120453image_300x200_media_50.png",
  "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
  "image_1905x350": "images/20220609124152image_1905x350-71.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;
  String? image_1905x350;

  DashboardUserSellerProfileShopBanner({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
    this.image_1905x350,
  });
  DashboardUserSellerProfileShopBanner.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyDashboardUserSellerProfileShopBannerStorage]?.toString();
    originalImage = json[_jsonKeyDashboardUserSellerProfileShopBannerOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyDashboardUserSellerProfileShopBannerImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyDashboardUserSellerProfileShopBannerImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyDashboardUserSellerProfileShopBannerImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyDashboardUserSellerProfileShopBannerImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyDashboardUserSellerProfileShopBannerImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyDashboardUserSellerProfileShopBannerImageThumbnail]?.toString();
    image_1905x350 = json[_jsonKeyDashboardUserSellerProfileShopBannerImage_1905x350]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserSellerProfileShopBannerStorage] = storage;
    data[_jsonKeyDashboardUserSellerProfileShopBannerOriginalImage] = originalImage;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImage_40x40] = image_40x40;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImage_72x72] = image_72x72;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImage_190x230] = image_190x230;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImage_110x122] = image_110x122;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImage_320x320] = image_320x320;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImageThumbnail] = imageThumbnail;
    data[_jsonKeyDashboardUserSellerProfileShopBannerImage_1905x350] = image_1905x350;
    return data;
  }
}

const String _jsonKeyDashboardUserSellerProfileShopPageContentsNewArrival = 'new_arrival';
class DashboardUserSellerProfileShopPageContents {
/*
{
  "new_arrival": "1"
}
*/

  String? newArrival;

  DashboardUserSellerProfileShopPageContents({
    this.newArrival,
  });
  DashboardUserSellerProfileShopPageContents.fromJson(Map<String, dynamic> json) {
    newArrival = json[_jsonKeyDashboardUserSellerProfileShopPageContentsNewArrival]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserSellerProfileShopPageContentsNewArrival] = newArrival;
    return data;
  }
}

const String _jsonKeyDashboardUserSellerProfileBannerStorage = 'storage';
const String _jsonKeyDashboardUserSellerProfileBannerOriginalImage = 'original_image';
const String _jsonKeyDashboardUserSellerProfileBannerImage_100x38 = 'image_100x38';
const String _jsonKeyDashboardUserSellerProfileBannerImage_89x33 = 'image_89x33';
const String _jsonKeyDashboardUserSellerProfileBannerImage_118x45 = 'image_118x45';
const String _jsonKeyDashboardUserSellerProfileBannerImage_48x25 = 'image_48x25';
const String _jsonKeyDashboardUserSellerProfileBannerImage_40x40 = 'image_40x40';
const String _jsonKeyDashboardUserSellerProfileBannerImage_197x152 = 'image_197x152';
const String _jsonKeyDashboardUserSellerProfileBannerImage_120x80 = 'image_120x80';
const String _jsonKeyDashboardUserSellerProfileBannerImage_82x82 = 'image_82x82';
const String _jsonKeyDashboardUserSellerProfileBannerImage_617x145 = 'image_617x145';
const String _jsonKeyDashboardUserSellerProfileBannerImage_297x146 = 'image_297x146';
const String _jsonKeyDashboardUserSellerProfileBannerImage_72x72 = 'image_72x72';
const String _jsonKeyDashboardUserSellerProfileBannerImage_270x260 = 'image_270x260';
const String _jsonKeyDashboardUserSellerProfileBannerImage_320x320 = 'image_320x320';
class DashboardUserSellerProfileBanner {
/*
{
  "storage": "local",
  "original_image": "images/seller/20220609124152-seller_banner4.jpg",
  "image_100x38": "",
  "image_89x33": "",
  "image_118x45": "",
  "image_48x25": "",
  "image_40x40": "",
  "image_197x152": "",
  "image_120x80": "",
  "image_82x82": "",
  "image_617x145": "images/seller/20220609124152-seller_banner-617x14521.png",
  "image_297x146": "images/seller/20220609124152-seller_banner-297x14650.png",
  "image_72x72": "images/seller/20220609124152image_small_twoseller_banner250.jpg",
  "image_270x260": "",
  "image_320x320": ""
}
*/

  String? storage;
  String? originalImage;
  String? image_100x38;
  String? image_89x33;
  String? image_118x45;
  String? image_48x25;
  String? image_40x40;
  String? image_197x152;
  String? image_120x80;
  String? image_82x82;
  String? image_617x145;
  String? image_297x146;
  String? image_72x72;
  String? image_270x260;
  String? image_320x320;

  DashboardUserSellerProfileBanner({
    this.storage,
    this.originalImage,
    this.image_100x38,
    this.image_89x33,
    this.image_118x45,
    this.image_48x25,
    this.image_40x40,
    this.image_197x152,
    this.image_120x80,
    this.image_82x82,
    this.image_617x145,
    this.image_297x146,
    this.image_72x72,
    this.image_270x260,
    this.image_320x320,
  });
  DashboardUserSellerProfileBanner.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyDashboardUserSellerProfileBannerStorage]?.toString();
    originalImage = json[_jsonKeyDashboardUserSellerProfileBannerOriginalImage]?.toString();
    image_100x38 = json[_jsonKeyDashboardUserSellerProfileBannerImage_100x38]?.toString();
    image_89x33 = json[_jsonKeyDashboardUserSellerProfileBannerImage_89x33]?.toString();
    image_118x45 = json[_jsonKeyDashboardUserSellerProfileBannerImage_118x45]?.toString();
    image_48x25 = json[_jsonKeyDashboardUserSellerProfileBannerImage_48x25]?.toString();
    image_40x40 = json[_jsonKeyDashboardUserSellerProfileBannerImage_40x40]?.toString();
    image_197x152 = json[_jsonKeyDashboardUserSellerProfileBannerImage_197x152]?.toString();
    image_120x80 = json[_jsonKeyDashboardUserSellerProfileBannerImage_120x80]?.toString();
    image_82x82 = json[_jsonKeyDashboardUserSellerProfileBannerImage_82x82]?.toString();
    image_617x145 = json[_jsonKeyDashboardUserSellerProfileBannerImage_617x145]?.toString();
    image_297x146 = json[_jsonKeyDashboardUserSellerProfileBannerImage_297x146]?.toString();
    image_72x72 = json[_jsonKeyDashboardUserSellerProfileBannerImage_72x72]?.toString();
    image_270x260 = json[_jsonKeyDashboardUserSellerProfileBannerImage_270x260]?.toString();
    image_320x320 = json[_jsonKeyDashboardUserSellerProfileBannerImage_320x320]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserSellerProfileBannerStorage] = storage;
    data[_jsonKeyDashboardUserSellerProfileBannerOriginalImage] = originalImage;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_100x38] = image_100x38;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_89x33] = image_89x33;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_118x45] = image_118x45;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_48x25] = image_48x25;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_40x40] = image_40x40;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_197x152] = image_197x152;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_120x80] = image_120x80;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_82x82] = image_82x82;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_617x145] = image_617x145;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_297x146] = image_297x146;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_72x72] = image_72x72;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_270x260] = image_270x260;
    data[_jsonKeyDashboardUserSellerProfileBannerImage_320x320] = image_320x320;
    return data;
  }
}

const String _jsonKeyDashboardUserSellerProfileLogoStorage = 'storage';
const String _jsonKeyDashboardUserSellerProfileLogoOriginalImage = 'original_image';
const String _jsonKeyDashboardUserSellerProfileLogoImage_100x38 = 'image_100x38';
const String _jsonKeyDashboardUserSellerProfileLogoImage_89x33 = 'image_89x33';
const String _jsonKeyDashboardUserSellerProfileLogoImage_118x45 = 'image_118x45';
const String _jsonKeyDashboardUserSellerProfileLogoImage_48x25 = 'image_48x25';
const String _jsonKeyDashboardUserSellerProfileLogoImage_40x40 = 'image_40x40';
const String _jsonKeyDashboardUserSellerProfileLogoImage_197x152 = 'image_197x152';
const String _jsonKeyDashboardUserSellerProfileLogoImage_120x80 = 'image_120x80';
const String _jsonKeyDashboardUserSellerProfileLogoImage_82x82 = 'image_82x82';
const String _jsonKeyDashboardUserSellerProfileLogoImage_617x145 = 'image_617x145';
const String _jsonKeyDashboardUserSellerProfileLogoImage_297x146 = 'image_297x146';
const String _jsonKeyDashboardUserSellerProfileLogoImage_72x72 = 'image_72x72';
const String _jsonKeyDashboardUserSellerProfileLogoImage_270x260 = 'image_270x260';
const String _jsonKeyDashboardUserSellerProfileLogoImage_320x320 = 'image_320x320';
class DashboardUserSellerProfileLogo {
/*
{
  "storage": "local",
  "original_image": "images/seller/20220609124152-seller_logo304.jpg",
  "image_100x38": "",
  "image_89x33": "",
  "image_118x45": "",
  "image_48x25": "",
  "image_40x40": "",
  "image_197x152": "images/seller/20220609124152-seller_logo-197x15215.jpg",
  "image_120x80": "images/seller/20220609124152-seller_logo-120x809.jpg",
  "image_82x82": "images/seller/20220609124152-seller_logo-79x7948.jpg",
  "image_617x145": "",
  "image_297x146": "",
  "image_72x72": "images/seller/20220609124152image_small_twoseller_logo250.jpg",
  "image_270x260": "",
  "image_320x320": "images/seller/20220609124152-seller_logo-320x32043.jpg"
}
*/

  String? storage;
  String? originalImage;
  String? image_100x38;
  String? image_89x33;
  String? image_118x45;
  String? image_48x25;
  String? image_40x40;
  String? image_197x152;
  String? image_120x80;
  String? image_82x82;
  String? image_617x145;
  String? image_297x146;
  String? image_72x72;
  String? image_270x260;
  String? image_320x320;

  DashboardUserSellerProfileLogo({
    this.storage,
    this.originalImage,
    this.image_100x38,
    this.image_89x33,
    this.image_118x45,
    this.image_48x25,
    this.image_40x40,
    this.image_197x152,
    this.image_120x80,
    this.image_82x82,
    this.image_617x145,
    this.image_297x146,
    this.image_72x72,
    this.image_270x260,
    this.image_320x320,
  });
  DashboardUserSellerProfileLogo.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyDashboardUserSellerProfileLogoStorage]?.toString();
    originalImage = json[_jsonKeyDashboardUserSellerProfileLogoOriginalImage]?.toString();
    image_100x38 = json[_jsonKeyDashboardUserSellerProfileLogoImage_100x38]?.toString();
    image_89x33 = json[_jsonKeyDashboardUserSellerProfileLogoImage_89x33]?.toString();
    image_118x45 = json[_jsonKeyDashboardUserSellerProfileLogoImage_118x45]?.toString();
    image_48x25 = json[_jsonKeyDashboardUserSellerProfileLogoImage_48x25]?.toString();
    image_40x40 = json[_jsonKeyDashboardUserSellerProfileLogoImage_40x40]?.toString();
    image_197x152 = json[_jsonKeyDashboardUserSellerProfileLogoImage_197x152]?.toString();
    image_120x80 = json[_jsonKeyDashboardUserSellerProfileLogoImage_120x80]?.toString();
    image_82x82 = json[_jsonKeyDashboardUserSellerProfileLogoImage_82x82]?.toString();
    image_617x145 = json[_jsonKeyDashboardUserSellerProfileLogoImage_617x145]?.toString();
    image_297x146 = json[_jsonKeyDashboardUserSellerProfileLogoImage_297x146]?.toString();
    image_72x72 = json[_jsonKeyDashboardUserSellerProfileLogoImage_72x72]?.toString();
    image_270x260 = json[_jsonKeyDashboardUserSellerProfileLogoImage_270x260]?.toString();
    image_320x320 = json[_jsonKeyDashboardUserSellerProfileLogoImage_320x320]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserSellerProfileLogoStorage] = storage;
    data[_jsonKeyDashboardUserSellerProfileLogoOriginalImage] = originalImage;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_100x38] = image_100x38;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_89x33] = image_89x33;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_118x45] = image_118x45;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_48x25] = image_48x25;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_40x40] = image_40x40;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_197x152] = image_197x152;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_120x80] = image_120x80;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_82x82] = image_82x82;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_617x145] = image_617x145;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_297x146] = image_297x146;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_72x72] = image_72x72;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_270x260] = image_270x260;
    data[_jsonKeyDashboardUserSellerProfileLogoImage_320x320] = image_320x320;
    return data;
  }
}

const String _jsonKeyDashboardUserSellerProfileTaxPaperStorage = 'storage';
const String _jsonKeyDashboardUserSellerProfileTaxPaperOriginalImage = 'original_image';
const String _jsonKeyDashboardUserSellerProfileTaxPaperImage_40x40 = 'image_40x40';
const String _jsonKeyDashboardUserSellerProfileTaxPaperImage_72x72 = 'image_72x72';
const String _jsonKeyDashboardUserSellerProfileTaxPaperImage_190x230 = 'image_190x230';
const String _jsonKeyDashboardUserSellerProfileTaxPaperImage_110x122 = 'image_110x122';
const String _jsonKeyDashboardUserSellerProfileTaxPaperImage_320x320 = 'image_320x320';
const String _jsonKeyDashboardUserSellerProfileTaxPaperImageThumbnail = 'image_thumbnail';
class DashboardUserSellerProfileTaxPaper {
/*
{
  "storage": "local",
  "original_image": "images/20220609124152_original__shop_40.jpg",
  "image_40x40": "images/20220609124152image_40x40_shop_308.png",
  "image_72x72": "images/20220609124152image_72x72_shop_27.png",
  "image_190x230": "images/20220609124152image_190x230_shop_102.png",
  "image_110x122": "images/20220609124152image_110x122_shop_76.png",
  "image_320x320": "images/20220609124152image_300x200_shop_484.png",
  "image_thumbnail": "images/20220609124152image_thumbnail_shop_311.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;

  DashboardUserSellerProfileTaxPaper({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
  });
  DashboardUserSellerProfileTaxPaper.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyDashboardUserSellerProfileTaxPaperStorage]?.toString();
    originalImage = json[_jsonKeyDashboardUserSellerProfileTaxPaperOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyDashboardUserSellerProfileTaxPaperImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyDashboardUserSellerProfileTaxPaperImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyDashboardUserSellerProfileTaxPaperImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyDashboardUserSellerProfileTaxPaperImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyDashboardUserSellerProfileTaxPaperImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyDashboardUserSellerProfileTaxPaperImageThumbnail]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserSellerProfileTaxPaperStorage] = storage;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperOriginalImage] = originalImage;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperImage_40x40] = image_40x40;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperImage_72x72] = image_72x72;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperImage_190x230] = image_190x230;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperImage_110x122] = image_110x122;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperImage_320x320] = image_320x320;
    data[_jsonKeyDashboardUserSellerProfileTaxPaperImageThumbnail] = imageThumbnail;
    return data;
  }
}

class DashboardUserSellerProfile {
/*
{
  "id": 20,
  "user_id": "38",
  "shop_name": "Wallace Norman",
  "slug": "incididunt-eum-conse",
  "verified_at": "2022-05-28 09:04:37",
  "license_no": "Aliquid deleniti rem",
  "tax_paper": {
    "storage": "local",
    "original_image": "images/20220609124152_original__shop_40.jpg",
    "image_40x40": "images/20220609124152image_40x40_shop_308.png",
    "image_72x72": "images/20220609124152image_72x72_shop_27.png",
    "image_190x230": "images/20220609124152image_190x230_shop_102.png",
    "image_110x122": "images/20220609124152image_110x122_shop_76.png",
    "image_320x320": "images/20220609124152image_300x200_shop_484.png",
    "image_thumbnail": "images/20220609124152image_thumbnail_shop_311.png"
  },
  "logo": {
    "storage": "local",
    "original_image": "images/seller/20220609124152-seller_logo304.jpg",
    "image_100x38": "",
    "image_89x33": "",
    "image_118x45": "",
    "image_48x25": "",
    "image_40x40": "",
    "image_197x152": "images/seller/20220609124152-seller_logo-197x15215.jpg",
    "image_120x80": "images/seller/20220609124152-seller_logo-120x809.jpg",
    "image_82x82": "images/seller/20220609124152-seller_logo-79x7948.jpg",
    "image_617x145": "",
    "image_297x146": "",
    "image_72x72": "images/seller/20220609124152image_small_twoseller_logo250.jpg",
    "image_270x260": "",
    "image_320x320": "images/seller/20220609124152-seller_logo-320x32043.jpg"
  },
  "banner": {
    "storage": "local",
    "original_image": "images/seller/20220609124152-seller_banner4.jpg",
    "image_100x38": "",
    "image_89x33": "",
    "image_118x45": "",
    "image_48x25": "",
    "image_40x40": "",
    "image_197x152": "",
    "image_120x80": "",
    "image_82x82": "",
    "image_617x145": "images/seller/20220609124152-seller_banner-617x14521.png",
    "image_297x146": "images/seller/20220609124152-seller_banner-297x14650.png",
    "image_72x72": "images/seller/20220609124152image_small_twoseller_banner250.jpg",
    "image_270x260": "",
    "image_320x320": ""
  },
  "shop_page_contents": [
    {
      "new_arrival": "1"
    }
  ],
  "shop_banner_id": "151",
  "shop_banner": {
    "storage": "local",
    "original_image": "images/20220609120453_original__media_39.jpg",
    "image_40x40": "images/20220609120453image_40x40_media_243.png",
    "image_72x72": "images/20220609120453image_72x72_media_99.png",
    "image_190x230": "images/20220609120537image_190x230-63.png",
    "image_110x122": "images/20220609120453image_110x122_media_85.png",
    "image_320x320": "images/20220609120453image_300x200_media_50.png",
    "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
    "image_1905x350": "images/20220609124152image_1905x350-71.png"
  },
  "shop_tagline": "shop demo tagline",
  "phone_no": "+1 (631) 788-2122",
  "shop_email": "demo@gmail.com",
  "website": "",
  "address": "Consectetur facere",
  "rating_count": "0",
  "reviews_count": "0",
  "facebook": "https://facebook.com/0xNajmul",
  "google": "https://facebook.com/0xNajmul",
  "twitter": "https://facebook.com/0xNajmul",
  "youtube": "https://facebook.com/0xNajmul",
  "meta_title": "Ut eiusmod consectet",
  "meta_description": "Maxime voluptatem N",
  "state_id": "3",
  "city_id": "1",
  "town_id": "3",
  "latitude": "51.51301544839645",
  "longitude": "-0.013046655273429852",
  "schedule_id": "5",
  "account_type": "Ultimate",
  "shop_type_id": "1",
  "created_at": "2022-05-28T02:44:04.000000Z",
  "updated_at": "2022-06-09T06:41:52.000000Z",
  "image_105x75": "https://hurrybuzz.com/public/images/default/105x75_no_bg.png",
  "image_197x152": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-197x15215.jpg",
  "image_1905x350": "https://hurrybuzz.com/public/images/20220609124152image_1905x350-71.png",
  "image_90x60": "https://hurrybuzz.com/public/images/seller/20220609124152image_small_twoseller_logo250.jpg",
  "image_82x82": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-79x7948.jpg",
  "image_120x80": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-120x809.jpg",
  "image_297x146": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-297x14650.png",
  "image_617x145": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-617x14521.png",
  "start_date": "28 May 2022",
  "image_1920x412": "https://hurrybuzz.com/public/images/default/default-image-1920x412.png"
}
*/

  int? id;
  String? userId;
  String? shopName;
  String? slug;
  String? verifiedAt;
  String? licenseNo;
  DashboardUserSellerProfileTaxPaper? taxPaper;
  DashboardUserSellerProfileLogo? logo;
  DashboardUserSellerProfileBanner? banner;
  List<DashboardUserSellerProfileShopPageContents?>? shopPageContents;
  String? shopBannerId;
  DashboardUserSellerProfileShopBanner? shopBanner;
  String? shopTagline;
  String? phoneNo;
  String? shopEmail;
  String? website;
  String? address;
  String? ratingCount;
  String? reviewsCount;
  String? facebook;
  String? google;
  String? twitter;
  String? youtube;
  String? metaTitle;
  String? metaDescription;
  String? stateId;
  String? cityId;
  String? townId;
  String? latitude;
  String? longitude;
  String? scheduleId;
  String? accountType;
  String? shopTypeId;
  String? createdAt;
  String? updatedAt;
  String? image_105x75;
  String? image_197x152;
  String? image_1905x350;
  String? image_90x60;
  String? image_82x82;
  String? image_120x80;
  String? image_297x146;
  String? image_617x145;
  String? startDate;
  String? image_1920x412;

  DashboardUserSellerProfile({
    this.id,
    this.userId,
    this.shopName,
    this.slug,
    this.verifiedAt,
    this.licenseNo,
    this.taxPaper,
    this.logo,
    this.banner,
    this.shopPageContents,
    this.shopBannerId,
    this.shopBanner,
    this.shopTagline,
    this.phoneNo,
    this.shopEmail,
    this.website,
    this.address,
    this.ratingCount,
    this.reviewsCount,
    this.facebook,
    this.google,
    this.twitter,
    this.youtube,
    this.metaTitle,
    this.metaDescription,
    this.stateId,
    this.cityId,
    this.townId,
    this.latitude,
    this.longitude,
    this.scheduleId,
    this.accountType,
    this.shopTypeId,
    this.createdAt,
    this.updatedAt,
    this.image_105x75,
    this.image_197x152,
    this.image_1905x350,
    this.image_90x60,
    this.image_82x82,
    this.image_120x80,
    this.image_297x146,
    this.image_617x145,
    this.startDate,
    this.image_1920x412,
  });
  DashboardUserSellerProfile.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyDashboardUserSellerProfileId]?.toInt();
    userId = json[_jsonKeyDashboardUserSellerProfileUserId]?.toString();
    shopName = json[_jsonKeyDashboardUserSellerProfileShopName]?.toString();
    slug = json[_jsonKeyDashboardUserSellerProfileSlug]?.toString();
    verifiedAt = json[_jsonKeyDashboardUserSellerProfileVerifiedAt]?.toString();
    licenseNo = json[_jsonKeyDashboardUserSellerProfileLicenseNo]?.toString();
    taxPaper = (json[_jsonKeyDashboardUserSellerProfileTaxPaper] != null) ? DashboardUserSellerProfileTaxPaper.fromJson(json[_jsonKeyDashboardUserSellerProfileTaxPaper]) : null;
    logo = (json[_jsonKeyDashboardUserSellerProfileLogo] != null) ? DashboardUserSellerProfileLogo.fromJson(json[_jsonKeyDashboardUserSellerProfileLogo]) : null;
    banner = (json[_jsonKeyDashboardUserSellerProfileBanner] != null) ? DashboardUserSellerProfileBanner.fromJson(json[_jsonKeyDashboardUserSellerProfileBanner]) : null;
    if (json[_jsonKeyDashboardUserSellerProfileShopPageContents] != null) {
      final v = json[_jsonKeyDashboardUserSellerProfileShopPageContents];
      final arr0 = <DashboardUserSellerProfileShopPageContents>[];
      v.forEach((v) {
        arr0.add(DashboardUserSellerProfileShopPageContents.fromJson(v));
      });
      shopPageContents = arr0;
    }
    shopBannerId = json[_jsonKeyDashboardUserSellerProfileShopBannerId]?.toString();
    shopBanner = (json[_jsonKeyDashboardUserSellerProfileShopBanner] != null) ? DashboardUserSellerProfileShopBanner.fromJson(json[_jsonKeyDashboardUserSellerProfileShopBanner]) : null;
    shopTagline = json[_jsonKeyDashboardUserSellerProfileShopTagline]?.toString();
    phoneNo = json[_jsonKeyDashboardUserSellerProfilePhoneNo]?.toString();
    shopEmail = json[_jsonKeyDashboardUserSellerProfileShopEmail]?.toString();
    website = json[_jsonKeyDashboardUserSellerProfileWebsite]?.toString();
    address = json[_jsonKeyDashboardUserSellerProfileAddress]?.toString();
    ratingCount = json[_jsonKeyDashboardUserSellerProfileRatingCount]?.toString();
    reviewsCount = json[_jsonKeyDashboardUserSellerProfileReviewsCount]?.toString();
    facebook = json[_jsonKeyDashboardUserSellerProfileFacebook]?.toString();
    google = json[_jsonKeyDashboardUserSellerProfileGoogle]?.toString();
    twitter = json[_jsonKeyDashboardUserSellerProfileTwitter]?.toString();
    youtube = json[_jsonKeyDashboardUserSellerProfileYoutube]?.toString();
    metaTitle = json[_jsonKeyDashboardUserSellerProfileMetaTitle]?.toString();
    metaDescription = json[_jsonKeyDashboardUserSellerProfileMetaDescription]?.toString();
    stateId = json[_jsonKeyDashboardUserSellerProfileStateId]?.toString();
    cityId = json[_jsonKeyDashboardUserSellerProfileCityId]?.toString();
    townId = json[_jsonKeyDashboardUserSellerProfileTownId]?.toString();
    latitude = json[_jsonKeyDashboardUserSellerProfileLatitude]?.toString();
    longitude = json[_jsonKeyDashboardUserSellerProfileLongitude]?.toString();
    scheduleId = json[_jsonKeyDashboardUserSellerProfileScheduleId]?.toString();
    accountType = json[_jsonKeyDashboardUserSellerProfileAccountType]?.toString();
    shopTypeId = json[_jsonKeyDashboardUserSellerProfileShopTypeId]?.toString();
    createdAt = json[_jsonKeyDashboardUserSellerProfileCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDashboardUserSellerProfileUpdatedAt]?.toString();
    image_105x75 = json[_jsonKeyDashboardUserSellerProfileImage_105x75]?.toString();
    image_197x152 = json[_jsonKeyDashboardUserSellerProfileImage_197x152]?.toString();
    image_1905x350 = json[_jsonKeyDashboardUserSellerProfileImage_1905x350]?.toString();
    image_90x60 = json[_jsonKeyDashboardUserSellerProfileImage_90x60]?.toString();
    image_82x82 = json[_jsonKeyDashboardUserSellerProfileImage_82x82]?.toString();
    image_120x80 = json[_jsonKeyDashboardUserSellerProfileImage_120x80]?.toString();
    image_297x146 = json[_jsonKeyDashboardUserSellerProfileImage_297x146]?.toString();
    image_617x145 = json[_jsonKeyDashboardUserSellerProfileImage_617x145]?.toString();
    startDate = json[_jsonKeyDashboardUserSellerProfileStartDate]?.toString();
    image_1920x412 = json[_jsonKeyDashboardUserSellerProfileImage_1920x412]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserSellerProfileId] = id;
    data[_jsonKeyDashboardUserSellerProfileUserId] = userId;
    data[_jsonKeyDashboardUserSellerProfileShopName] = shopName;
    data[_jsonKeyDashboardUserSellerProfileSlug] = slug;
    data[_jsonKeyDashboardUserSellerProfileVerifiedAt] = verifiedAt;
    data[_jsonKeyDashboardUserSellerProfileLicenseNo] = licenseNo;
    if (taxPaper != null) {
      data[_jsonKeyDashboardUserSellerProfileTaxPaper] = taxPaper!.toJson();
    }
    if (logo != null) {
      data[_jsonKeyDashboardUserSellerProfileLogo] = logo!.toJson();
    }
    if (banner != null) {
      data[_jsonKeyDashboardUserSellerProfileBanner] = banner!.toJson();
    }
    if (shopPageContents != null) {
      final v = shopPageContents;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDashboardUserSellerProfileShopPageContents] = arr0;
    }
    data[_jsonKeyDashboardUserSellerProfileShopBannerId] = shopBannerId;
    if (shopBanner != null) {
      data[_jsonKeyDashboardUserSellerProfileShopBanner] = shopBanner!.toJson();
    }
    data[_jsonKeyDashboardUserSellerProfileShopTagline] = shopTagline;
    data[_jsonKeyDashboardUserSellerProfilePhoneNo] = phoneNo;
    data[_jsonKeyDashboardUserSellerProfileShopEmail] = shopEmail;
    data[_jsonKeyDashboardUserSellerProfileWebsite] = website;
    data[_jsonKeyDashboardUserSellerProfileAddress] = address;
    data[_jsonKeyDashboardUserSellerProfileRatingCount] = ratingCount;
    data[_jsonKeyDashboardUserSellerProfileReviewsCount] = reviewsCount;
    data[_jsonKeyDashboardUserSellerProfileFacebook] = facebook;
    data[_jsonKeyDashboardUserSellerProfileGoogle] = google;
    data[_jsonKeyDashboardUserSellerProfileTwitter] = twitter;
    data[_jsonKeyDashboardUserSellerProfileYoutube] = youtube;
    data[_jsonKeyDashboardUserSellerProfileMetaTitle] = metaTitle;
    data[_jsonKeyDashboardUserSellerProfileMetaDescription] = metaDescription;
    data[_jsonKeyDashboardUserSellerProfileStateId] = stateId;
    data[_jsonKeyDashboardUserSellerProfileCityId] = cityId;
    data[_jsonKeyDashboardUserSellerProfileTownId] = townId;
    data[_jsonKeyDashboardUserSellerProfileLatitude] = latitude;
    data[_jsonKeyDashboardUserSellerProfileLongitude] = longitude;
    data[_jsonKeyDashboardUserSellerProfileScheduleId] = scheduleId;
    data[_jsonKeyDashboardUserSellerProfileAccountType] = accountType;
    data[_jsonKeyDashboardUserSellerProfileShopTypeId] = shopTypeId;
    data[_jsonKeyDashboardUserSellerProfileCreatedAt] = createdAt;
    data[_jsonKeyDashboardUserSellerProfileUpdatedAt] = updatedAt;
    data[_jsonKeyDashboardUserSellerProfileImage_105x75] = image_105x75;
    data[_jsonKeyDashboardUserSellerProfileImage_197x152] = image_197x152;
    data[_jsonKeyDashboardUserSellerProfileImage_1905x350] = image_1905x350;
    data[_jsonKeyDashboardUserSellerProfileImage_90x60] = image_90x60;
    data[_jsonKeyDashboardUserSellerProfileImage_82x82] = image_82x82;
    data[_jsonKeyDashboardUserSellerProfileImage_120x80] = image_120x80;
    data[_jsonKeyDashboardUserSellerProfileImage_297x146] = image_297x146;
    data[_jsonKeyDashboardUserSellerProfileImage_617x145] = image_617x145;
    data[_jsonKeyDashboardUserSellerProfileStartDate] = startDate;
    data[_jsonKeyDashboardUserSellerProfileImage_1920x412] = image_1920x412;
    return data;
  }
}

const String _jsonKeyDashboardUserBillingAddressId = 'id';
const String _jsonKeyDashboardUserBillingAddressUserId = 'user_id';
const String _jsonKeyDashboardUserBillingAddressName = 'name';
const String _jsonKeyDashboardUserBillingAddressEmail = 'email';
const String _jsonKeyDashboardUserBillingAddressPhoneNo = 'phone_no';
const String _jsonKeyDashboardUserBillingAddressAddress = 'address';
const String _jsonKeyDashboardUserBillingAddressAddressIds = 'address_ids';
const String _jsonKeyDashboardUserBillingAddressCountry = 'country';
const String _jsonKeyDashboardUserBillingAddressState = 'state';
const String _jsonKeyDashboardUserBillingAddressCity = 'city';
const String _jsonKeyDashboardUserBillingAddressLatitude = 'latitude';
const String _jsonKeyDashboardUserBillingAddressLongitude = 'longitude';
const String _jsonKeyDashboardUserBillingAddressPostalCode = 'postal_code';
const String _jsonKeyDashboardUserBillingAddressDefaultShipping = 'default_shipping';
const String _jsonKeyDashboardUserBillingAddressDefaultBilling = 'default_billing';
const String _jsonKeyDashboardUserBillingAddressCreatedAt = 'created_at';
const String _jsonKeyDashboardUserBillingAddressUpdatedAt = 'updated_at';
const String _jsonKeyDashboardUserBillingAddressAddressIdsCountryId = 'country_id';
const String _jsonKeyDashboardUserBillingAddressAddressIdsStateId = 'state_id';
const String _jsonKeyDashboardUserBillingAddressAddressIdsCityId = 'city_id';
class DashboardUserBillingAddressAddressIds {
/*
{
  "country_id": "19",
  "state_id": "3",
  "city_id": "1"
}
*/

  String? countryId;
  String? stateId;
  String? cityId;

  DashboardUserBillingAddressAddressIds({
    this.countryId,
    this.stateId,
    this.cityId,
  });
  DashboardUserBillingAddressAddressIds.fromJson(Map<String, dynamic> json) {
    countryId = json[_jsonKeyDashboardUserBillingAddressAddressIdsCountryId]?.toString();
    stateId = json[_jsonKeyDashboardUserBillingAddressAddressIdsStateId]?.toString();
    cityId = json[_jsonKeyDashboardUserBillingAddressAddressIdsCityId]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserBillingAddressAddressIdsCountryId] = countryId;
    data[_jsonKeyDashboardUserBillingAddressAddressIdsStateId] = stateId;
    data[_jsonKeyDashboardUserBillingAddressAddressIdsCityId] = cityId;
    return data;
  }
}

class DashboardUserBillingAddress {
/*
{
  "id": 4,
  "user_id": "38",
  "name": "Plan Outs",
  "email": "planouts24@gmail.com",
  "phone_no": "+880 3535 353",
  "address": "Muhammadpur , Dhaka\nDhaka",
  "address_ids": {
    "country_id": "19",
    "state_id": "3",
    "city_id": "1"
  },
  "country": "Bangladesh",
  "state": "Dhaka",
  "city": "Dhaka",
  "latitude": null,
  "longitude": null,
  "postal_code": "1207",
  "default_shipping": "1",
  "default_billing": "1",
  "created_at": "2022-06-09T06:11:11.000000Z",
  "updated_at": "2022-06-09T06:11:11.000000Z"
}
*/

  int? id;
  String? userId;
  String? name;
  String? email;
  String? phoneNo;
  String? address;
  DashboardUserBillingAddressAddressIds? addressIds;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? postalCode;
  String? defaultShipping;
  String? defaultBilling;
  String? createdAt;
  String? updatedAt;

  DashboardUserBillingAddress({
    this.id,
    this.userId,
    this.name,
    this.email,
    this.phoneNo,
    this.address,
    this.addressIds,
    this.country,
    this.state,
    this.city,
    this.latitude,
    this.longitude,
    this.postalCode,
    this.defaultShipping,
    this.defaultBilling,
    this.createdAt,
    this.updatedAt,
  });
  DashboardUserBillingAddress.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyDashboardUserBillingAddressId]?.toInt();
    userId = json[_jsonKeyDashboardUserBillingAddressUserId]?.toString();
    name = json[_jsonKeyDashboardUserBillingAddressName]?.toString();
    email = json[_jsonKeyDashboardUserBillingAddressEmail]?.toString();
    phoneNo = json[_jsonKeyDashboardUserBillingAddressPhoneNo]?.toString();
    address = json[_jsonKeyDashboardUserBillingAddressAddress]?.toString();
    addressIds = (json[_jsonKeyDashboardUserBillingAddressAddressIds] != null) ? DashboardUserBillingAddressAddressIds.fromJson(json[_jsonKeyDashboardUserBillingAddressAddressIds]) : null;
    country = json[_jsonKeyDashboardUserBillingAddressCountry]?.toString();
    state = json[_jsonKeyDashboardUserBillingAddressState]?.toString();
    city = json[_jsonKeyDashboardUserBillingAddressCity]?.toString();
    latitude = json[_jsonKeyDashboardUserBillingAddressLatitude]?.toString();
    longitude = json[_jsonKeyDashboardUserBillingAddressLongitude]?.toString();
    postalCode = json[_jsonKeyDashboardUserBillingAddressPostalCode]?.toString();
    defaultShipping = json[_jsonKeyDashboardUserBillingAddressDefaultShipping]?.toString();
    defaultBilling = json[_jsonKeyDashboardUserBillingAddressDefaultBilling]?.toString();
    createdAt = json[_jsonKeyDashboardUserBillingAddressCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDashboardUserBillingAddressUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserBillingAddressId] = id;
    data[_jsonKeyDashboardUserBillingAddressUserId] = userId;
    data[_jsonKeyDashboardUserBillingAddressName] = name;
    data[_jsonKeyDashboardUserBillingAddressEmail] = email;
    data[_jsonKeyDashboardUserBillingAddressPhoneNo] = phoneNo;
    data[_jsonKeyDashboardUserBillingAddressAddress] = address;
    if (addressIds != null) {
      data[_jsonKeyDashboardUserBillingAddressAddressIds] = addressIds!.toJson();
    }
    data[_jsonKeyDashboardUserBillingAddressCountry] = country;
    data[_jsonKeyDashboardUserBillingAddressState] = state;
    data[_jsonKeyDashboardUserBillingAddressCity] = city;
    data[_jsonKeyDashboardUserBillingAddressLatitude] = latitude;
    data[_jsonKeyDashboardUserBillingAddressLongitude] = longitude;
    data[_jsonKeyDashboardUserBillingAddressPostalCode] = postalCode;
    data[_jsonKeyDashboardUserBillingAddressDefaultShipping] = defaultShipping;
    data[_jsonKeyDashboardUserBillingAddressDefaultBilling] = defaultBilling;
    data[_jsonKeyDashboardUserBillingAddressCreatedAt] = createdAt;
    data[_jsonKeyDashboardUserBillingAddressUpdatedAt] = updatedAt;
    return data;
  }
}

const String _jsonKeyDashboardUserShippingAddressId = 'id';
const String _jsonKeyDashboardUserShippingAddressUserId = 'user_id';
const String _jsonKeyDashboardUserShippingAddressName = 'name';
const String _jsonKeyDashboardUserShippingAddressEmail = 'email';
const String _jsonKeyDashboardUserShippingAddressPhoneNo = 'phone_no';
const String _jsonKeyDashboardUserShippingAddressAddress = 'address';
const String _jsonKeyDashboardUserShippingAddressAddressIds = 'address_ids';
const String _jsonKeyDashboardUserShippingAddressCountry = 'country';
const String _jsonKeyDashboardUserShippingAddressState = 'state';
const String _jsonKeyDashboardUserShippingAddressCity = 'city';
const String _jsonKeyDashboardUserShippingAddressLatitude = 'latitude';
const String _jsonKeyDashboardUserShippingAddressLongitude = 'longitude';
const String _jsonKeyDashboardUserShippingAddressPostalCode = 'postal_code';
const String _jsonKeyDashboardUserShippingAddressDefaultShipping = 'default_shipping';
const String _jsonKeyDashboardUserShippingAddressDefaultBilling = 'default_billing';
const String _jsonKeyDashboardUserShippingAddressCreatedAt = 'created_at';
const String _jsonKeyDashboardUserShippingAddressUpdatedAt = 'updated_at';
const String _jsonKeyDashboardUserShippingAddressAddressIdsCountryId = 'country_id';
const String _jsonKeyDashboardUserShippingAddressAddressIdsStateId = 'state_id';
const String _jsonKeyDashboardUserShippingAddressAddressIdsCityId = 'city_id';
class DashboardUserShippingAddressAddressIds {
/*
{
  "country_id": "19",
  "state_id": "3",
  "city_id": "1"
}
*/

  String? countryId;
  String? stateId;
  String? cityId;

  DashboardUserShippingAddressAddressIds({
    this.countryId,
    this.stateId,
    this.cityId,
  });
  DashboardUserShippingAddressAddressIds.fromJson(Map<String, dynamic> json) {
    countryId = json[_jsonKeyDashboardUserShippingAddressAddressIdsCountryId]?.toString();
    stateId = json[_jsonKeyDashboardUserShippingAddressAddressIdsStateId]?.toString();
    cityId = json[_jsonKeyDashboardUserShippingAddressAddressIdsCityId]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserShippingAddressAddressIdsCountryId] = countryId;
    data[_jsonKeyDashboardUserShippingAddressAddressIdsStateId] = stateId;
    data[_jsonKeyDashboardUserShippingAddressAddressIdsCityId] = cityId;
    return data;
  }
}

class DashboardUserShippingAddress {
/*
{
  "id": 4,
  "user_id": "38",
  "name": "Plan Outs",
  "email": "planouts24@gmail.com",
  "phone_no": "+880 3535 353",
  "address": "Muhammadpur , Dhaka\nDhaka",
  "address_ids": {
    "country_id": "19",
    "state_id": "3",
    "city_id": "1"
  },
  "country": "Bangladesh",
  "state": "Dhaka",
  "city": "Dhaka",
  "latitude": null,
  "longitude": null,
  "postal_code": "1207",
  "default_shipping": "1",
  "default_billing": "1",
  "created_at": "2022-06-09T06:11:11.000000Z",
  "updated_at": "2022-06-09T06:11:11.000000Z"
}
*/

  int? id;
  String? userId;
  String? name;
  String? email;
  String? phoneNo;
  String? address;
  DashboardUserShippingAddressAddressIds? addressIds;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? postalCode;
  String? defaultShipping;
  String? defaultBilling;
  String? createdAt;
  String? updatedAt;

  DashboardUserShippingAddress({
    this.id,
    this.userId,
    this.name,
    this.email,
    this.phoneNo,
    this.address,
    this.addressIds,
    this.country,
    this.state,
    this.city,
    this.latitude,
    this.longitude,
    this.postalCode,
    this.defaultShipping,
    this.defaultBilling,
    this.createdAt,
    this.updatedAt,
  });
  DashboardUserShippingAddress.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyDashboardUserShippingAddressId]?.toInt();
    userId = json[_jsonKeyDashboardUserShippingAddressUserId]?.toString();
    name = json[_jsonKeyDashboardUserShippingAddressName]?.toString();
    email = json[_jsonKeyDashboardUserShippingAddressEmail]?.toString();
    phoneNo = json[_jsonKeyDashboardUserShippingAddressPhoneNo]?.toString();
    address = json[_jsonKeyDashboardUserShippingAddressAddress]?.toString();
    addressIds = (json[_jsonKeyDashboardUserShippingAddressAddressIds] != null) ? DashboardUserShippingAddressAddressIds.fromJson(json[_jsonKeyDashboardUserShippingAddressAddressIds]) : null;
    country = json[_jsonKeyDashboardUserShippingAddressCountry]?.toString();
    state = json[_jsonKeyDashboardUserShippingAddressState]?.toString();
    city = json[_jsonKeyDashboardUserShippingAddressCity]?.toString();
    latitude = json[_jsonKeyDashboardUserShippingAddressLatitude]?.toString();
    longitude = json[_jsonKeyDashboardUserShippingAddressLongitude]?.toString();
    postalCode = json[_jsonKeyDashboardUserShippingAddressPostalCode]?.toString();
    defaultShipping = json[_jsonKeyDashboardUserShippingAddressDefaultShipping]?.toString();
    defaultBilling = json[_jsonKeyDashboardUserShippingAddressDefaultBilling]?.toString();
    createdAt = json[_jsonKeyDashboardUserShippingAddressCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDashboardUserShippingAddressUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserShippingAddressId] = id;
    data[_jsonKeyDashboardUserShippingAddressUserId] = userId;
    data[_jsonKeyDashboardUserShippingAddressName] = name;
    data[_jsonKeyDashboardUserShippingAddressEmail] = email;
    data[_jsonKeyDashboardUserShippingAddressPhoneNo] = phoneNo;
    data[_jsonKeyDashboardUserShippingAddressAddress] = address;
    if (addressIds != null) {
      data[_jsonKeyDashboardUserShippingAddressAddressIds] = addressIds!.toJson();
    }
    data[_jsonKeyDashboardUserShippingAddressCountry] = country;
    data[_jsonKeyDashboardUserShippingAddressState] = state;
    data[_jsonKeyDashboardUserShippingAddressCity] = city;
    data[_jsonKeyDashboardUserShippingAddressLatitude] = latitude;
    data[_jsonKeyDashboardUserShippingAddressLongitude] = longitude;
    data[_jsonKeyDashboardUserShippingAddressPostalCode] = postalCode;
    data[_jsonKeyDashboardUserShippingAddressDefaultShipping] = defaultShipping;
    data[_jsonKeyDashboardUserShippingAddressDefaultBilling] = defaultBilling;
    data[_jsonKeyDashboardUserShippingAddressCreatedAt] = createdAt;
    data[_jsonKeyDashboardUserShippingAddressUpdatedAt] = updatedAt;
    return data;
  }
}

const String _jsonKeyDashboardUserImagesStorage = 'storage';
const String _jsonKeyDashboardUserImagesOriginalImage = 'original_image';
const String _jsonKeyDashboardUserImagesImage_40x40 = 'image_40x40';
const String _jsonKeyDashboardUserImagesImage_128x128 = 'image_128x128';
const String _jsonKeyDashboardUserImagesImage_20x20 = 'image_20x20';
class DashboardUserImages {
/*
{
  "storage": "local",
  "original_image": "images/20220609124026-_staff_17.jpg",
  "image_40x40": "images/20220609124026image_40X40_staff_105.png",
  "image_128x128": "images/20220609124026image_thumbnail_staff_183.png",
  "image_20x20": "images/20220609124026image_20X20_staff_319.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_128x128;
  String? image_20x20;

  DashboardUserImages({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_128x128,
    this.image_20x20,
  });
  DashboardUserImages.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyDashboardUserImagesStorage]?.toString();
    originalImage = json[_jsonKeyDashboardUserImagesOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyDashboardUserImagesImage_40x40]?.toString();
    image_128x128 = json[_jsonKeyDashboardUserImagesImage_128x128]?.toString();
    image_20x20 = json[_jsonKeyDashboardUserImagesImage_20x20]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserImagesStorage] = storage;
    data[_jsonKeyDashboardUserImagesOriginalImage] = originalImage;
    data[_jsonKeyDashboardUserImagesImage_40x40] = image_40x40;
    data[_jsonKeyDashboardUserImagesImage_128x128] = image_128x128;
    data[_jsonKeyDashboardUserImagesImage_20x20] = image_20x20;
    return data;
  }
}

class DashboardUser {
/*
{
  "id": 38,
  "email": "demo@gmail.com",
  "phone": "+1 (272) 905-9622",
  "first_name": "Lisandra",
  "last_name": "Coleman",
  "user_type": "seller",
  "gender": "male",
  "date_of_birth": "2022-06-09",
  "status": "1",
  "is_user_banned": "0",
  "newsletter_enable": "0",
  "otp": "435353",
  "firebase_auth_id": "34CDSCVSFGER464",
  "is_password_set": "1",
  "images": {
    "storage": "local",
    "original_image": "images/20220609124026-_staff_17.jpg",
    "image_40x40": "images/20220609124026image_40X40_staff_105.png",
    "image_128x128": "images/20220609124026image_thumbnail_staff_183.png",
    "image_20x20": "images/20220609124026image_20X20_staff_319.png"
  },
  "last_login": "2022-06-11 17:09:00",
  "last_ip": "",
  "last_password_change": "2022-06-09 11:47:07",
  "image_id": null,
  "role_id": null,
  "pickup_hub_id": null,
  "balance": "0.000",
  "created_at": "2022-05-28T02:44:04.000000Z",
  "updated_at": "2022-06-11T11:09:00.000000Z",
  "profile_image": "https://hurrybuzz.com/public/images/20220609124026image_thumbnail_staff_183.png",
  "user_profile_image": "https://hurrybuzz.com/public/images/20220609124026image_20X20_staff_319.png",
  "full_name": "Lisandra Coleman",
  "shipping_address": {
    "id": 4,
    "user_id": "38",
    "name": "Plan Outs",
    "email": "planouts24@gmail.com",
    "phone_no": "+880 3535 353",
    "address": "Muhammadpur , Dhaka\nDhaka",
    "address_ids": {
      "country_id": "19",
      "state_id": "3",
      "city_id": "1"
    },
    "country": "Bangladesh",
    "state": "Dhaka",
    "city": "Dhaka",
    "latitude": null,
    "longitude": null,
    "postal_code": "1207",
    "default_shipping": "1",
    "default_billing": "1",
    "created_at": "2022-06-09T06:11:11.000000Z",
    "updated_at": "2022-06-09T06:11:11.000000Z"
  },
  "billing_address": {
    "id": 4,
    "user_id": "38",
    "name": "Plan Outs",
    "email": "planouts24@gmail.com",
    "phone_no": "+880 3535 353",
    "address": "Muhammadpur , Dhaka\nDhaka",
    "address_ids": {
      "country_id": "19",
      "state_id": "3",
      "city_id": "1"
    },
    "country": "Bangladesh",
    "state": "Dhaka",
    "city": "Dhaka",
    "latitude": null,
    "longitude": null,
    "postal_code": "1207",
    "default_shipping": "1",
    "default_billing": "1",
    "created_at": "2022-06-09T06:11:11.000000Z",
    "updated_at": "2022-06-09T06:11:11.000000Z"
  },
  "last_recharge": 0,
  "seller_profile": {
    "id": 20,
    "user_id": "38",
    "shop_name": "Wallace Norman",
    "slug": "incididunt-eum-conse",
    "verified_at": "2022-05-28 09:04:37",
    "license_no": "Aliquid deleniti rem",
    "tax_paper": {
      "storage": "local",
      "original_image": "images/20220609124152_original__shop_40.jpg",
      "image_40x40": "images/20220609124152image_40x40_shop_308.png",
      "image_72x72": "images/20220609124152image_72x72_shop_27.png",
      "image_190x230": "images/20220609124152image_190x230_shop_102.png",
      "image_110x122": "images/20220609124152image_110x122_shop_76.png",
      "image_320x320": "images/20220609124152image_300x200_shop_484.png",
      "image_thumbnail": "images/20220609124152image_thumbnail_shop_311.png"
    },
    "logo": {
      "storage": "local",
      "original_image": "images/seller/20220609124152-seller_logo304.jpg",
      "image_100x38": "",
      "image_89x33": "",
      "image_118x45": "",
      "image_48x25": "",
      "image_40x40": "",
      "image_197x152": "images/seller/20220609124152-seller_logo-197x15215.jpg",
      "image_120x80": "images/seller/20220609124152-seller_logo-120x809.jpg",
      "image_82x82": "images/seller/20220609124152-seller_logo-79x7948.jpg",
      "image_617x145": "",
      "image_297x146": "",
      "image_72x72": "images/seller/20220609124152image_small_twoseller_logo250.jpg",
      "image_270x260": "",
      "image_320x320": "images/seller/20220609124152-seller_logo-320x32043.jpg"
    },
    "banner": {
      "storage": "local",
      "original_image": "images/seller/20220609124152-seller_banner4.jpg",
      "image_100x38": "",
      "image_89x33": "",
      "image_118x45": "",
      "image_48x25": "",
      "image_40x40": "",
      "image_197x152": "",
      "image_120x80": "",
      "image_82x82": "",
      "image_617x145": "images/seller/20220609124152-seller_banner-617x14521.png",
      "image_297x146": "images/seller/20220609124152-seller_banner-297x14650.png",
      "image_72x72": "images/seller/20220609124152image_small_twoseller_banner250.jpg",
      "image_270x260": "",
      "image_320x320": ""
    },
    "shop_page_contents": [
      {
        "new_arrival": "1"
      }
    ],
    "shop_banner_id": "151",
    "shop_banner": {
      "storage": "local",
      "original_image": "images/20220609120453_original__media_39.jpg",
      "image_40x40": "images/20220609120453image_40x40_media_243.png",
      "image_72x72": "images/20220609120453image_72x72_media_99.png",
      "image_190x230": "images/20220609120537image_190x230-63.png",
      "image_110x122": "images/20220609120453image_110x122_media_85.png",
      "image_320x320": "images/20220609120453image_300x200_media_50.png",
      "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
      "image_1905x350": "images/20220609124152image_1905x350-71.png"
    },
    "shop_tagline": "shop demo tagline",
    "phone_no": "+1 (631) 788-2122",
    "shop_email": "demo@gmail.com",
    "website": "",
    "address": "Consectetur facere",
    "rating_count": "0",
    "reviews_count": "0",
    "facebook": "https://facebook.com/0xNajmul",
    "google": "https://facebook.com/0xNajmul",
    "twitter": "https://facebook.com/0xNajmul",
    "youtube": "https://facebook.com/0xNajmul",
    "meta_title": "Ut eiusmod consectet",
    "meta_description": "Maxime voluptatem N",
    "state_id": "3",
    "city_id": "1",
    "town_id": "3",
    "latitude": "51.51301544839645",
    "longitude": "-0.013046655273429852",
    "schedule_id": "5",
    "account_type": "Ultimate",
    "shop_type_id": "1",
    "created_at": "2022-05-28T02:44:04.000000Z",
    "updated_at": "2022-06-09T06:41:52.000000Z",
    "image_105x75": "https://hurrybuzz.com/public/images/default/105x75_no_bg.png",
    "image_197x152": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-197x15215.jpg",
    "image_1905x350": "https://hurrybuzz.com/public/images/20220609124152image_1905x350-71.png",
    "image_90x60": "https://hurrybuzz.com/public/images/seller/20220609124152image_small_twoseller_logo250.jpg",
    "image_82x82": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-79x7948.jpg",
    "image_120x80": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-120x809.jpg",
    "image_297x146": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-297x14650.png",
    "image_617x145": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-617x14521.png",
    "start_date": "28 May 2022",
    "image_1920x412": "https://hurrybuzz.com/public/images/default/default-image-1920x412.png"
  }
}
*/

  int? id;
  String? email;
  String? phone;
  String? firstName;
  String? lastName;
  String? userType;
  String? gender;
  String? dateOfBirth;
  String? status;
  String? isUserBanned;
  String? newsletterEnable;
  String? otp;
  String? firebaseAuthId;
  String? isPasswordSet;
  DashboardUserImages? images;
  String? lastLogin;
  String? lastIp;
  String? lastPasswordChange;
  String? imageId;
  String? roleId;
  String? pickupHubId;
  String? balance;
  String? createdAt;
  String? updatedAt;
  String? profileImage;
  String? userProfileImage;
  String? fullName;
  DashboardUserShippingAddress? shippingAddress;
  DashboardUserBillingAddress? billingAddress;
  int? lastRecharge;
  DashboardUserSellerProfile? sellerProfile;

  DashboardUser({
    this.id,
    this.email,
    this.phone,
    this.firstName,
    this.lastName,
    this.userType,
    this.gender,
    this.dateOfBirth,
    this.status,
    this.isUserBanned,
    this.newsletterEnable,
    this.otp,
    this.firebaseAuthId,
    this.isPasswordSet,
    this.images,
    this.lastLogin,
    this.lastIp,
    this.lastPasswordChange,
    this.imageId,
    this.roleId,
    this.pickupHubId,
    this.balance,
    this.createdAt,
    this.updatedAt,
    this.profileImage,
    this.userProfileImage,
    this.fullName,
    this.shippingAddress,
    this.billingAddress,
    this.lastRecharge,
    this.sellerProfile,
  });
  DashboardUser.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyDashboardUserId]?.toInt();
    email = json[_jsonKeyDashboardUserEmail]?.toString();
    phone = json[_jsonKeyDashboardUserPhone]?.toString();
    firstName = json[_jsonKeyDashboardUserFirstName]?.toString();
    lastName = json[_jsonKeyDashboardUserLastName]?.toString();
    userType = json[_jsonKeyDashboardUserUserType]?.toString();
    gender = json[_jsonKeyDashboardUserGender]?.toString();
    dateOfBirth = json[_jsonKeyDashboardUserDateOfBirth]?.toString();
    status = json[_jsonKeyDashboardUserStatus]?.toString();
    isUserBanned = json[_jsonKeyDashboardUserIsUserBanned]?.toString();
    newsletterEnable = json[_jsonKeyDashboardUserNewsletterEnable]?.toString();
    otp = json[_jsonKeyDashboardUserOtp]?.toString();
    firebaseAuthId = json[_jsonKeyDashboardUserFirebaseAuthId]?.toString();
    isPasswordSet = json[_jsonKeyDashboardUserIsPasswordSet]?.toString();
    images = (json[_jsonKeyDashboardUserImages] != null) ? DashboardUserImages.fromJson(json[_jsonKeyDashboardUserImages]) : null;
    lastLogin = json[_jsonKeyDashboardUserLastLogin]?.toString();
    lastIp = json[_jsonKeyDashboardUserLastIp]?.toString();
    lastPasswordChange = json[_jsonKeyDashboardUserLastPasswordChange]?.toString();
    imageId = json[_jsonKeyDashboardUserImageId]?.toString();
    roleId = json[_jsonKeyDashboardUserRoleId]?.toString();
    pickupHubId = json[_jsonKeyDashboardUserPickupHubId]?.toString();
    balance = json[_jsonKeyDashboardUserBalance]?.toString();
    createdAt = json[_jsonKeyDashboardUserCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDashboardUserUpdatedAt]?.toString();
    profileImage = json[_jsonKeyDashboardUserProfileImage]?.toString();
    userProfileImage = json[_jsonKeyDashboardUserUserProfileImage]?.toString();
    fullName = json[_jsonKeyDashboardUserFullName]?.toString();
    shippingAddress = (json[_jsonKeyDashboardUserShippingAddress] != null) ? DashboardUserShippingAddress.fromJson(json[_jsonKeyDashboardUserShippingAddress]) : null;
    billingAddress = (json[_jsonKeyDashboardUserBillingAddress] != null) ? DashboardUserBillingAddress.fromJson(json[_jsonKeyDashboardUserBillingAddress]) : null;
    lastRecharge = json[_jsonKeyDashboardUserLastRecharge]?.toInt();
    sellerProfile = (json[_jsonKeyDashboardUserSellerProfile] != null) ? DashboardUserSellerProfile.fromJson(json[_jsonKeyDashboardUserSellerProfile]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDashboardUserId] = id;
    data[_jsonKeyDashboardUserEmail] = email;
    data[_jsonKeyDashboardUserPhone] = phone;
    data[_jsonKeyDashboardUserFirstName] = firstName;
    data[_jsonKeyDashboardUserLastName] = lastName;
    data[_jsonKeyDashboardUserUserType] = userType;
    data[_jsonKeyDashboardUserGender] = gender;
    data[_jsonKeyDashboardUserDateOfBirth] = dateOfBirth;
    data[_jsonKeyDashboardUserStatus] = status;
    data[_jsonKeyDashboardUserIsUserBanned] = isUserBanned;
    data[_jsonKeyDashboardUserNewsletterEnable] = newsletterEnable;
    data[_jsonKeyDashboardUserOtp] = otp;
    data[_jsonKeyDashboardUserFirebaseAuthId] = firebaseAuthId;
    data[_jsonKeyDashboardUserIsPasswordSet] = isPasswordSet;
    if (images != null) {
      data[_jsonKeyDashboardUserImages] = images!.toJson();
    }
    data[_jsonKeyDashboardUserLastLogin] = lastLogin;
    data[_jsonKeyDashboardUserLastIp] = lastIp;
    data[_jsonKeyDashboardUserLastPasswordChange] = lastPasswordChange;
    data[_jsonKeyDashboardUserImageId] = imageId;
    data[_jsonKeyDashboardUserRoleId] = roleId;
    data[_jsonKeyDashboardUserPickupHubId] = pickupHubId;
    data[_jsonKeyDashboardUserBalance] = balance;
    data[_jsonKeyDashboardUserCreatedAt] = createdAt;
    data[_jsonKeyDashboardUserUpdatedAt] = updatedAt;
    data[_jsonKeyDashboardUserProfileImage] = profileImage;
    data[_jsonKeyDashboardUserUserProfileImage] = userProfileImage;
    data[_jsonKeyDashboardUserFullName] = fullName;
    if (shippingAddress != null) {
      data[_jsonKeyDashboardUserShippingAddress] = shippingAddress!.toJson();
    }
    if (billingAddress != null) {
      data[_jsonKeyDashboardUserBillingAddress] = billingAddress!.toJson();
    }
    data[_jsonKeyDashboardUserLastRecharge] = lastRecharge;
    if (sellerProfile != null) {
      data[_jsonKeyDashboardUserSellerProfile] = sellerProfile!.toJson();
    }
    return data;
  }
}

class Dashboard {
/*
{
  "user": {
    "id": 38,
    "email": "demo@gmail.com",
    "phone": "+1 (272) 905-9622",
    "first_name": "Lisandra",
    "last_name": "Coleman",
    "user_type": "seller",
    "gender": "male",
    "date_of_birth": "2022-06-09",
    "status": "1",
    "is_user_banned": "0",
    "newsletter_enable": "0",
    "otp": "435353",
    "firebase_auth_id": "34CDSCVSFGER464",
    "is_password_set": "1",
    "images": {
      "storage": "local",
      "original_image": "images/20220609124026-_staff_17.jpg",
      "image_40x40": "images/20220609124026image_40X40_staff_105.png",
      "image_128x128": "images/20220609124026image_thumbnail_staff_183.png",
      "image_20x20": "images/20220609124026image_20X20_staff_319.png"
    },
    "last_login": "2022-06-11 17:09:00",
    "last_ip": "",
    "last_password_change": "2022-06-09 11:47:07",
    "image_id": null,
    "role_id": null,
    "pickup_hub_id": null,
    "balance": "0.000",
    "created_at": "2022-05-28T02:44:04.000000Z",
    "updated_at": "2022-06-11T11:09:00.000000Z",
    "profile_image": "https://hurrybuzz.com/public/images/20220609124026image_thumbnail_staff_183.png",
    "user_profile_image": "https://hurrybuzz.com/public/images/20220609124026image_20X20_staff_319.png",
    "full_name": "Lisandra Coleman",
    "shipping_address": {
      "id": 4,
      "user_id": "38",
      "name": "Plan Outs",
      "email": "planouts24@gmail.com",
      "phone_no": "+880 3535 353",
      "address": "Muhammadpur , Dhaka\nDhaka",
      "address_ids": {
        "country_id": "19",
        "state_id": "3",
        "city_id": "1"
      },
      "country": "Bangladesh",
      "state": "Dhaka",
      "city": "Dhaka",
      "latitude": null,
      "longitude": null,
      "postal_code": "1207",
      "default_shipping": "1",
      "default_billing": "1",
      "created_at": "2022-06-09T06:11:11.000000Z",
      "updated_at": "2022-06-09T06:11:11.000000Z"
    },
    "billing_address": {
      "id": 4,
      "user_id": "38",
      "name": "Plan Outs",
      "email": "planouts24@gmail.com",
      "phone_no": "+880 3535 353",
      "address": "Muhammadpur , Dhaka\nDhaka",
      "address_ids": {
        "country_id": "19",
        "state_id": "3",
        "city_id": "1"
      },
      "country": "Bangladesh",
      "state": "Dhaka",
      "city": "Dhaka",
      "latitude": null,
      "longitude": null,
      "postal_code": "1207",
      "default_shipping": "1",
      "default_billing": "1",
      "created_at": "2022-06-09T06:11:11.000000Z",
      "updated_at": "2022-06-09T06:11:11.000000Z"
    },
    "last_recharge": 0,
    "seller_profile": {
      "id": 20,
      "user_id": "38",
      "shop_name": "Wallace Norman",
      "slug": "incididunt-eum-conse",
      "verified_at": "2022-05-28 09:04:37",
      "license_no": "Aliquid deleniti rem",
      "tax_paper": {
        "storage": "local",
        "original_image": "images/20220609124152_original__shop_40.jpg",
        "image_40x40": "images/20220609124152image_40x40_shop_308.png",
        "image_72x72": "images/20220609124152image_72x72_shop_27.png",
        "image_190x230": "images/20220609124152image_190x230_shop_102.png",
        "image_110x122": "images/20220609124152image_110x122_shop_76.png",
        "image_320x320": "images/20220609124152image_300x200_shop_484.png",
        "image_thumbnail": "images/20220609124152image_thumbnail_shop_311.png"
      },
      "logo": {
        "storage": "local",
        "original_image": "images/seller/20220609124152-seller_logo304.jpg",
        "image_100x38": "",
        "image_89x33": "",
        "image_118x45": "",
        "image_48x25": "",
        "image_40x40": "",
        "image_197x152": "images/seller/20220609124152-seller_logo-197x15215.jpg",
        "image_120x80": "images/seller/20220609124152-seller_logo-120x809.jpg",
        "image_82x82": "images/seller/20220609124152-seller_logo-79x7948.jpg",
        "image_617x145": "",
        "image_297x146": "",
        "image_72x72": "images/seller/20220609124152image_small_twoseller_logo250.jpg",
        "image_270x260": "",
        "image_320x320": "images/seller/20220609124152-seller_logo-320x32043.jpg"
      },
      "banner": {
        "storage": "local",
        "original_image": "images/seller/20220609124152-seller_banner4.jpg",
        "image_100x38": "",
        "image_89x33": "",
        "image_118x45": "",
        "image_48x25": "",
        "image_40x40": "",
        "image_197x152": "",
        "image_120x80": "",
        "image_82x82": "",
        "image_617x145": "images/seller/20220609124152-seller_banner-617x14521.png",
        "image_297x146": "images/seller/20220609124152-seller_banner-297x14650.png",
        "image_72x72": "images/seller/20220609124152image_small_twoseller_banner250.jpg",
        "image_270x260": "",
        "image_320x320": ""
      },
      "shop_page_contents": [
        {
          "new_arrival": "1"
        }
      ],
      "shop_banner_id": "151",
      "shop_banner": {
        "storage": "local",
        "original_image": "images/20220609120453_original__media_39.jpg",
        "image_40x40": "images/20220609120453image_40x40_media_243.png",
        "image_72x72": "images/20220609120453image_72x72_media_99.png",
        "image_190x230": "images/20220609120537image_190x230-63.png",
        "image_110x122": "images/20220609120453image_110x122_media_85.png",
        "image_320x320": "images/20220609120453image_300x200_media_50.png",
        "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
        "image_1905x350": "images/20220609124152image_1905x350-71.png"
      },
      "shop_tagline": "shop demo tagline",
      "phone_no": "+1 (631) 788-2122",
      "shop_email": "demo@gmail.com",
      "website": "",
      "address": "Consectetur facere",
      "rating_count": "0",
      "reviews_count": "0",
      "facebook": "https://facebook.com/0xNajmul",
      "google": "https://facebook.com/0xNajmul",
      "twitter": "https://facebook.com/0xNajmul",
      "youtube": "https://facebook.com/0xNajmul",
      "meta_title": "Ut eiusmod consectet",
      "meta_description": "Maxime voluptatem N",
      "state_id": "3",
      "city_id": "1",
      "town_id": "3",
      "latitude": "51.51301544839645",
      "longitude": "-0.013046655273429852",
      "schedule_id": "5",
      "account_type": "Ultimate",
      "shop_type_id": "1",
      "created_at": "2022-05-28T02:44:04.000000Z",
      "updated_at": "2022-06-09T06:41:52.000000Z",
      "image_105x75": "https://hurrybuzz.com/public/images/default/105x75_no_bg.png",
      "image_197x152": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-197x15215.jpg",
      "image_1905x350": "https://hurrybuzz.com/public/images/20220609124152image_1905x350-71.png",
      "image_90x60": "https://hurrybuzz.com/public/images/seller/20220609124152image_small_twoseller_logo250.jpg",
      "image_82x82": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-79x7948.jpg",
      "image_120x80": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_logo-120x809.jpg",
      "image_297x146": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-297x14650.png",
      "image_617x145": "https://hurrybuzz.com/public/images/seller/20220609124152-seller_banner-617x14521.png",
      "start_date": "28 May 2022",
      "image_1920x412": "https://hurrybuzz.com/public/images/default/default-image-1920x412.png"
    }
  },
  "total_orders": 1,
  "total_sales": "৳0.00",
  "total_products": 1,
  "total_campaign": 1,
  "pending_orders": 0,
  "processing_orders": 0,
  "delivered_orders": 0
}
*/

  DashboardUser? user;
  int? totalOrders;
  String? totalSales;
  int? totalProducts;
  int? totalCampaign;
  int? pendingOrders;
  int? processingOrders;
  int? deliveredOrders;

  Dashboard({
    this.user,
    this.totalOrders,
    this.totalSales,
    this.totalProducts,
    this.totalCampaign,
    this.pendingOrders,
    this.processingOrders,
    this.deliveredOrders,
  });
  Dashboard.fromJson(Map<String, dynamic> json) {
    user = (json[_jsonKeyDashboardUser] != null) ? DashboardUser.fromJson(json[_jsonKeyDashboardUser]) : null;
    totalOrders = json[_jsonKeyDashboardTotalOrders]?.toInt();
    totalSales = json[_jsonKeyDashboardTotalSales]?.toString();
    totalProducts = json[_jsonKeyDashboardTotalProducts]?.toInt();
    totalCampaign = json[_jsonKeyDashboardTotalCampaign]?.toInt();
    pendingOrders = json[_jsonKeyDashboardPendingOrders]?.toInt();
    processingOrders = json[_jsonKeyDashboardProcessingOrders]?.toInt();
    deliveredOrders = json[_jsonKeyDashboardDeliveredOrders]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data[_jsonKeyDashboardUser] = user!.toJson();
    }
    data[_jsonKeyDashboardTotalOrders] = totalOrders;
    data[_jsonKeyDashboardTotalSales] = totalSales;
    data[_jsonKeyDashboardTotalProducts] = totalProducts;
    data[_jsonKeyDashboardTotalCampaign] = totalCampaign;
    data[_jsonKeyDashboardPendingOrders] = pendingOrders;
    data[_jsonKeyDashboardProcessingOrders] = processingOrders;
    data[_jsonKeyDashboardDeliveredOrders] = deliveredOrders;
    return data;
  }

static List<Map<String, dynamic>> toJsonList(List<Dashboard> modelList) {
    List<Map<String, dynamic>> _output = modelList.map<Map<String, dynamic>>((item) => item.toJson()).toList();
    return _output;
  }

  static List<Dashboard> fromJsonList(List<dynamic> jsonList) {
    List<Dashboard> _output = jsonList.map<Dashboard>((item) => Dashboard.fromJson(item)).toList();
    return _output;
  }
  //
  // factory Dashboard.fromJsonToData(String str) =>
  //     List<Dashboard>.from(json.decode(str).map((x)=> Dashboard.fromJson(x)).toList();

}
