///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyOrderId = 'id';
const String _jsonKeyOrderSellerId = 'seller_id';
const String _jsonKeyOrderUserId = 'user_id';
const String _jsonKeyOrderDeliveryHeroId = 'delivery_hero_id';
const String _jsonKeyOrderBillingAddress = 'billing_address';
const String _jsonKeyOrderShippingAddress = 'shipping_address';
const String _jsonKeyOrderDeliveryStatus = 'delivery_status';
const String _jsonKeyOrderPaymentType = 'payment_type';
const String _jsonKeyOrderPaymentStatus = 'payment_status';
const String _jsonKeyOrderPaymentDetails = 'payment_details';
const String _jsonKeyOrderSubTotal = 'sub_total';
const String _jsonKeyOrderDiscount = 'discount';
const String _jsonKeyOrderCouponDiscount = 'coupon_discount';
const String _jsonKeyOrderTotalTax = 'total_tax';
const String _jsonKeyOrderTotalAmount = 'total_amount';
const String _jsonKeyOrderShippingCost = 'shipping_cost';
const String _jsonKeyOrderTotalPayable = 'total_payable';
const String _jsonKeyOrderCode = 'code';
const String _jsonKeyOrderDate = 'date';
const String _jsonKeyOrderViewed = 'viewed';
const String _jsonKeyOrderDeliveryViewed = 'delivery_viewed';
const String _jsonKeyOrderPaymentStatusViewed = 'payment_status_viewed';
const String _jsonKeyOrderCommissionCalculated = 'commission_calculated';
const String _jsonKeyOrderIsCancelled = 'is_cancelled';
const String _jsonKeyOrderIsDeleted = 'is_deleted';
const String _jsonKeyOrderTrxId = 'trx_id';
const String _jsonKeyOrderIsMailed = 'is_mailed';
const String _jsonKeyOrderOfflineMethodId = 'offline_method_id';
const String _jsonKeyOrderOfflineMethodFile = 'offline_method_file';
const String _jsonKeyOrderStatus = 'status';
const String _jsonKeyOrderPickupHubId = 'pickup_hub_id';
const String _jsonKeyOrderCancelRequest = 'cancel_request';
const String _jsonKeyOrderCancelRequestAt = 'cancel_request_at';
const String _jsonKeyOrderDeliveryHeroAssignAt = 'delivery_hero_assign_at';
const String _jsonKeyOrderCreatedBy = 'created_by';
const String _jsonKeyOrderCreatedAt = 'created_at';
const String _jsonKeyOrderUpdatedAt = 'updated_at';
const String _jsonKeyOrderOrderDate = 'order_date';
const String _jsonKeyOrderDeliveredDays = 'delivered_days';
const String _jsonKeyOrderOrderDetails = 'order_details';
const String _jsonKeyOrderDeliveredAt = 'delivered_at';
const String _jsonKeyOrderOrderDetailsId = 'id';
const String _jsonKeyOrderOrderDetailsOrderId = 'order_id';
const String _jsonKeyOrderOrderDetailsProductId = 'product_id';
const String _jsonKeyOrderOrderDetailsVariation = 'variation';
const String _jsonKeyOrderOrderDetailsPrice = 'price';
const String _jsonKeyOrderOrderDetailsTax = 'tax';
const String _jsonKeyOrderOrderDetailsDiscount = 'discount';
const String _jsonKeyOrderOrderDetailsCouponDiscount = 'coupon_discount';
const String _jsonKeyOrderOrderDetailsShippingCost = 'shipping_cost';
const String _jsonKeyOrderOrderDetailsQuantity = 'quantity';
const String _jsonKeyOrderOrderDetailsPickupHubId = 'pickup_hub_id';
const String _jsonKeyOrderOrderDetailsProductReferralCode = 'product_referral_code';
const String _jsonKeyOrderOrderDetailsIsRefundable = 'is_refundable';
const String _jsonKeyOrderOrderDetailsCreatedAt = 'created_at';
const String _jsonKeyOrderOrderDetailsUpdatedAt = 'updated_at';
const String _jsonKeyOrderOrderDetailsShippingCostType = 'type';
const String _jsonKeyOrderOrderDetailsShippingCostDependOnQuantity = 'depend_on_quantity';
const String _jsonKeyOrderOrderDetailsShippingCostPerCost = 'per_cost';
const String _jsonKeyOrderOrderDetailsShippingCostTotalCost = 'total_cost';
class OrderOrderDetailsShippingCost {
/*
{
  "type": "",
  "depend_on_quantity": 0,
  "per_cost": 0,
  "total_cost": 0
}
*/

  String? type;
  int? dependOnQuantity;
  int? perCost;
  int? totalCost;

  OrderOrderDetailsShippingCost({
    this.type,
    this.dependOnQuantity,
    this.perCost,
    this.totalCost,
  });
  OrderOrderDetailsShippingCost.fromJson(Map<String, dynamic> json) {
    type = json[_jsonKeyOrderOrderDetailsShippingCostType]?.toString();
    dependOnQuantity = json[_jsonKeyOrderOrderDetailsShippingCostDependOnQuantity]?.toInt();
    perCost = json[_jsonKeyOrderOrderDetailsShippingCostPerCost]?.toInt();
    totalCost = json[_jsonKeyOrderOrderDetailsShippingCostTotalCost]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderOrderDetailsShippingCostType] = type;
    data[_jsonKeyOrderOrderDetailsShippingCostDependOnQuantity] = dependOnQuantity;
    data[_jsonKeyOrderOrderDetailsShippingCostPerCost] = perCost;
    data[_jsonKeyOrderOrderDetailsShippingCostTotalCost] = totalCost;
    return data;
  }
}

const String _jsonKeyOrderOrderDetailsCouponDiscountCode = 'code';
const String _jsonKeyOrderOrderDetailsCouponDiscountDiscount = 'discount';
class OrderOrderDetailsCouponDiscount {
/*
{
  "code": "",
  "discount": 0
}
*/

  String? code;
  int? discount;

  OrderOrderDetailsCouponDiscount({
    this.code,
    this.discount,
  });
  OrderOrderDetailsCouponDiscount.fromJson(Map<String, dynamic> json) {
    code = json[_jsonKeyOrderOrderDetailsCouponDiscountCode]?.toString();
    discount = json[_jsonKeyOrderOrderDetailsCouponDiscountDiscount]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderOrderDetailsCouponDiscountCode] = code;
    data[_jsonKeyOrderOrderDetailsCouponDiscountDiscount] = discount;
    return data;
  }
}

class OrderOrderDetails {
/*
{
  "id": 8,
  "order_id": "8",
  "product_id": "71",
  "variation": "",
  "price": "555.000",
  "tax": "0.000",
  "discount": "0.000",
  "coupon_discount": {
    "code": "",
    "discount": 0
  },
  "shipping_cost": {
    "type": "",
    "depend_on_quantity": 0,
    "per_cost": 0,
    "total_cost": 0
  },
  "quantity": "1",
  "pickup_hub_id": null,
  "product_referral_code": null,
  "is_refundable": "0",
  "created_at": "2022-06-09T06:11:14.000000Z",
  "updated_at": "2022-06-09T06:11:14.000000Z"
}
*/

  int? id;
  String? orderId;
  String? productId;
  String? variation;
  String? price;
  String? tax;
  String? discount;
  OrderOrderDetailsCouponDiscount? couponDiscount;
  OrderOrderDetailsShippingCost? shippingCost;
  String? quantity;
  String? pickupHubId;
  String? productReferralCode;
  String? isRefundable;
  String? createdAt;
  String? updatedAt;

  OrderOrderDetails({
    this.id,
    this.orderId,
    this.productId,
    this.variation,
    this.price,
    this.tax,
    this.discount,
    this.couponDiscount,
    this.shippingCost,
    this.quantity,
    this.pickupHubId,
    this.productReferralCode,
    this.isRefundable,
    this.createdAt,
    this.updatedAt,
  });
  OrderOrderDetails.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyOrderOrderDetailsId]?.toInt();
    orderId = json[_jsonKeyOrderOrderDetailsOrderId]?.toString();
    productId = json[_jsonKeyOrderOrderDetailsProductId]?.toString();
    variation = json[_jsonKeyOrderOrderDetailsVariation]?.toString();
    price = json[_jsonKeyOrderOrderDetailsPrice]?.toString();
    tax = json[_jsonKeyOrderOrderDetailsTax]?.toString();
    discount = json[_jsonKeyOrderOrderDetailsDiscount]?.toString();
    couponDiscount = (json[_jsonKeyOrderOrderDetailsCouponDiscount] != null) ? OrderOrderDetailsCouponDiscount.fromJson(json[_jsonKeyOrderOrderDetailsCouponDiscount]) : null;
    shippingCost = (json[_jsonKeyOrderOrderDetailsShippingCost] != null) ? OrderOrderDetailsShippingCost.fromJson(json[_jsonKeyOrderOrderDetailsShippingCost]) : null;
    quantity = json[_jsonKeyOrderOrderDetailsQuantity]?.toString();
    pickupHubId = json[_jsonKeyOrderOrderDetailsPickupHubId]?.toString();
    productReferralCode = json[_jsonKeyOrderOrderDetailsProductReferralCode]?.toString();
    isRefundable = json[_jsonKeyOrderOrderDetailsIsRefundable]?.toString();
    createdAt = json[_jsonKeyOrderOrderDetailsCreatedAt]?.toString();
    updatedAt = json[_jsonKeyOrderOrderDetailsUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderOrderDetailsId] = id;
    data[_jsonKeyOrderOrderDetailsOrderId] = orderId;
    data[_jsonKeyOrderOrderDetailsProductId] = productId;
    data[_jsonKeyOrderOrderDetailsVariation] = variation;
    data[_jsonKeyOrderOrderDetailsPrice] = price;
    data[_jsonKeyOrderOrderDetailsTax] = tax;
    data[_jsonKeyOrderOrderDetailsDiscount] = discount;
    if (couponDiscount != null) {
      data[_jsonKeyOrderOrderDetailsCouponDiscount] = couponDiscount!.toJson();
    }
    if (shippingCost != null) {
      data[_jsonKeyOrderOrderDetailsShippingCost] = shippingCost!.toJson();
    }
    data[_jsonKeyOrderOrderDetailsQuantity] = quantity;
    data[_jsonKeyOrderOrderDetailsPickupHubId] = pickupHubId;
    data[_jsonKeyOrderOrderDetailsProductReferralCode] = productReferralCode;
    data[_jsonKeyOrderOrderDetailsIsRefundable] = isRefundable;
    data[_jsonKeyOrderOrderDetailsCreatedAt] = createdAt;
    data[_jsonKeyOrderOrderDetailsUpdatedAt] = updatedAt;
    return data;
  }
  static List<OrderOrderDetails> fromJsonList(List<dynamic> jsonList) {
    List<OrderOrderDetails> _output = jsonList.map<OrderOrderDetails>((item) => OrderOrderDetails.fromJson(item)).toList();
    return _output;
  }
}

const String _jsonKeyOrderShippingAddressId = 'id';
const String _jsonKeyOrderShippingAddressUserId = 'user_id';
const String _jsonKeyOrderShippingAddressName = 'name';
const String _jsonKeyOrderShippingAddressEmail = 'email';
const String _jsonKeyOrderShippingAddressPhoneNo = 'phone_no';
const String _jsonKeyOrderShippingAddressAddress = 'address';
const String _jsonKeyOrderShippingAddressAddressIds = 'address_ids';
const String _jsonKeyOrderShippingAddressCountry = 'country';
const String _jsonKeyOrderShippingAddressState = 'state';
const String _jsonKeyOrderShippingAddressCity = 'city';
const String _jsonKeyOrderShippingAddressLatitude = 'latitude';
const String _jsonKeyOrderShippingAddressLongitude = 'longitude';
const String _jsonKeyOrderShippingAddressPostalCode = 'postal_code';
const String _jsonKeyOrderShippingAddressDefaultShipping = 'default_shipping';
const String _jsonKeyOrderShippingAddressDefaultBilling = 'default_billing';
const String _jsonKeyOrderShippingAddressCreatedAt = 'created_at';
const String _jsonKeyOrderShippingAddressUpdatedAt = 'updated_at';
const String _jsonKeyOrderShippingAddressAddressIdsCountryId = 'country_id';
const String _jsonKeyOrderShippingAddressAddressIdsStateId = 'state_id';
const String _jsonKeyOrderShippingAddressAddressIdsCityId = 'city_id';
class OrderShippingAddressAddressIds {
/*
{
  "country_id": "19",
  "state_id": "3",
  "city_id": "1"
}
*/

  String? countryId;
  String? stateId;
  String? cityId;

  OrderShippingAddressAddressIds({
    this.countryId,
    this.stateId,
    this.cityId,
  });
  OrderShippingAddressAddressIds.fromJson(Map<String, dynamic> json) {
    countryId = json[_jsonKeyOrderShippingAddressAddressIdsCountryId]?.toString();
    stateId = json[_jsonKeyOrderShippingAddressAddressIdsStateId]?.toString();
    cityId = json[_jsonKeyOrderShippingAddressAddressIdsCityId]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderShippingAddressAddressIdsCountryId] = countryId;
    data[_jsonKeyOrderShippingAddressAddressIdsStateId] = stateId;
    data[_jsonKeyOrderShippingAddressAddressIdsCityId] = cityId;
    return data;
  }
}

class OrderShippingAddress {
/*
{
  "id": "4",
  "user_id": "38",
  "name": "Plan Outs",
  "email": "planouts24@gmail.com",
  "phone_no": "+880 3535 353",
  "address": "Muhammadpur , Dhaka\nDhaka",
  "address_ids": {
    "country_id": "19",
    "state_id": "3",
    "city_id": "1"
  },
  "country": "Bangladesh",
  "state": "Dhaka",
  "city": "Dhaka",
  "latitude": "",
  "longitude": "",
  "postal_code": "1207",
  "default_shipping": "1",
  "default_billing": "1",
  "created_at": "2022-06-09T06:11:11.000000Z",
  "updated_at": "2022-06-09T06:11:11.000000Z"
}
*/

  String? id;
  String? userId;
  String? name;
  String? email;
  String? phoneNo;
  String? address;
  OrderShippingAddressAddressIds? addressIds;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? postalCode;
  String? defaultShipping;
  String? defaultBilling;
  String? createdAt;
  String? updatedAt;

  OrderShippingAddress({
    this.id,
    this.userId,
    this.name,
    this.email,
    this.phoneNo,
    this.address,
    this.addressIds,
    this.country,
    this.state,
    this.city,
    this.latitude,
    this.longitude,
    this.postalCode,
    this.defaultShipping,
    this.defaultBilling,
    this.createdAt,
    this.updatedAt,
  });
  OrderShippingAddress.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyOrderShippingAddressId]?.toString();
    userId = json[_jsonKeyOrderShippingAddressUserId]?.toString();
    name = json[_jsonKeyOrderShippingAddressName]?.toString();
    email = json[_jsonKeyOrderShippingAddressEmail]?.toString();
    phoneNo = json[_jsonKeyOrderShippingAddressPhoneNo]?.toString();
    address = json[_jsonKeyOrderShippingAddressAddress]?.toString();
    addressIds = (json[_jsonKeyOrderShippingAddressAddressIds] != null) ? OrderShippingAddressAddressIds.fromJson(json[_jsonKeyOrderShippingAddressAddressIds]) : null;
    country = json[_jsonKeyOrderShippingAddressCountry]?.toString();
    state = json[_jsonKeyOrderShippingAddressState]?.toString();
    city = json[_jsonKeyOrderShippingAddressCity]?.toString();
    latitude = json[_jsonKeyOrderShippingAddressLatitude]?.toString();
    longitude = json[_jsonKeyOrderShippingAddressLongitude]?.toString();
    postalCode = json[_jsonKeyOrderShippingAddressPostalCode]?.toString();
    defaultShipping = json[_jsonKeyOrderShippingAddressDefaultShipping]?.toString();
    defaultBilling = json[_jsonKeyOrderShippingAddressDefaultBilling]?.toString();
    createdAt = json[_jsonKeyOrderShippingAddressCreatedAt]?.toString();
    updatedAt = json[_jsonKeyOrderShippingAddressUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderShippingAddressId] = id;
    data[_jsonKeyOrderShippingAddressUserId] = userId;
    data[_jsonKeyOrderShippingAddressName] = name;
    data[_jsonKeyOrderShippingAddressEmail] = email;
    data[_jsonKeyOrderShippingAddressPhoneNo] = phoneNo;
    data[_jsonKeyOrderShippingAddressAddress] = address;
    if (addressIds != null) {
      data[_jsonKeyOrderShippingAddressAddressIds] = addressIds!.toJson();
    }
    data[_jsonKeyOrderShippingAddressCountry] = country;
    data[_jsonKeyOrderShippingAddressState] = state;
    data[_jsonKeyOrderShippingAddressCity] = city;
    data[_jsonKeyOrderShippingAddressLatitude] = latitude;
    data[_jsonKeyOrderShippingAddressLongitude] = longitude;
    data[_jsonKeyOrderShippingAddressPostalCode] = postalCode;
    data[_jsonKeyOrderShippingAddressDefaultShipping] = defaultShipping;
    data[_jsonKeyOrderShippingAddressDefaultBilling] = defaultBilling;
    data[_jsonKeyOrderShippingAddressCreatedAt] = createdAt;
    data[_jsonKeyOrderShippingAddressUpdatedAt] = updatedAt;
    return data;
  }
}

const String _jsonKeyOrderBillingAddressId = 'id';
const String _jsonKeyOrderBillingAddressUserId = 'user_id';
const String _jsonKeyOrderBillingAddressName = 'name';
const String _jsonKeyOrderBillingAddressEmail = 'email';
const String _jsonKeyOrderBillingAddressPhoneNo = 'phone_no';
const String _jsonKeyOrderBillingAddressAddress = 'address';
const String _jsonKeyOrderBillingAddressAddressIds = 'address_ids';
const String _jsonKeyOrderBillingAddressCountry = 'country';
const String _jsonKeyOrderBillingAddressState = 'state';
const String _jsonKeyOrderBillingAddressCity = 'city';
const String _jsonKeyOrderBillingAddressLatitude = 'latitude';
const String _jsonKeyOrderBillingAddressLongitude = 'longitude';
const String _jsonKeyOrderBillingAddressPostalCode = 'postal_code';
const String _jsonKeyOrderBillingAddressDefaultShipping = 'default_shipping';
const String _jsonKeyOrderBillingAddressDefaultBilling = 'default_billing';
const String _jsonKeyOrderBillingAddressCreatedAt = 'created_at';
const String _jsonKeyOrderBillingAddressUpdatedAt = 'updated_at';
const String _jsonKeyOrderBillingAddressAddressIdsCountryId = 'country_id';
const String _jsonKeyOrderBillingAddressAddressIdsStateId = 'state_id';
const String _jsonKeyOrderBillingAddressAddressIdsCityId = 'city_id';
class OrderBillingAddressAddressIds {
/*
{
  "country_id": "19",
  "state_id": "3",
  "city_id": "1"
}
*/

  String? countryId;
  String? stateId;
  String? cityId;

  OrderBillingAddressAddressIds({
    this.countryId,
    this.stateId,
    this.cityId,
  });
  OrderBillingAddressAddressIds.fromJson(Map<String, dynamic> json) {
    countryId = json[_jsonKeyOrderBillingAddressAddressIdsCountryId]?.toString();
    stateId = json[_jsonKeyOrderBillingAddressAddressIdsStateId]?.toString();
    cityId = json[_jsonKeyOrderBillingAddressAddressIdsCityId]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderBillingAddressAddressIdsCountryId] = countryId;
    data[_jsonKeyOrderBillingAddressAddressIdsStateId] = stateId;
    data[_jsonKeyOrderBillingAddressAddressIdsCityId] = cityId;
    return data;
  }
}

class OrderBillingAddress {
/*
{
  "id": "4",
  "user_id": "38",
  "name": "Plan Outs",
  "email": "planouts24@gmail.com",
  "phone_no": "+880 3535 353",
  "address": "Muhammadpur , Dhaka\nDhaka",
  "address_ids": {
    "country_id": "19",
    "state_id": "3",
    "city_id": "1"
  },
  "country": "Bangladesh",
  "state": "Dhaka",
  "city": "Dhaka",
  "latitude": "",
  "longitude": "",
  "postal_code": "1207",
  "default_shipping": "1",
  "default_billing": "1",
  "created_at": "2022-06-09T06:11:11.000000Z",
  "updated_at": "2022-06-09T06:11:11.000000Z"
}
*/

  String? id;
  String? userId;
  String? name;
  String? email;
  String? phoneNo;
  String? address;
  OrderBillingAddressAddressIds? addressIds;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? postalCode;
  String? defaultShipping;
  String? defaultBilling;
  String? createdAt;
  String? updatedAt;

  OrderBillingAddress({
    this.id,
    this.userId,
    this.name,
    this.email,
    this.phoneNo,
    this.address,
    this.addressIds,
    this.country,
    this.state,
    this.city,
    this.latitude,
    this.longitude,
    this.postalCode,
    this.defaultShipping,
    this.defaultBilling,
    this.createdAt,
    this.updatedAt,
  });
  OrderBillingAddress.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyOrderBillingAddressId]?.toString();
    userId = json[_jsonKeyOrderBillingAddressUserId]?.toString();
    name = json[_jsonKeyOrderBillingAddressName]?.toString();
    email = json[_jsonKeyOrderBillingAddressEmail]?.toString();
    phoneNo = json[_jsonKeyOrderBillingAddressPhoneNo]?.toString();
    address = json[_jsonKeyOrderBillingAddressAddress]?.toString();
    addressIds = (json[_jsonKeyOrderBillingAddressAddressIds] != null) ? OrderBillingAddressAddressIds.fromJson(json[_jsonKeyOrderBillingAddressAddressIds]) : null;
    country = json[_jsonKeyOrderBillingAddressCountry]?.toString();
    state = json[_jsonKeyOrderBillingAddressState]?.toString();
    city = json[_jsonKeyOrderBillingAddressCity]?.toString();
    latitude = json[_jsonKeyOrderBillingAddressLatitude]?.toString();
    longitude = json[_jsonKeyOrderBillingAddressLongitude]?.toString();
    postalCode = json[_jsonKeyOrderBillingAddressPostalCode]?.toString();
    defaultShipping = json[_jsonKeyOrderBillingAddressDefaultShipping]?.toString();
    defaultBilling = json[_jsonKeyOrderBillingAddressDefaultBilling]?.toString();
    createdAt = json[_jsonKeyOrderBillingAddressCreatedAt]?.toString();
    updatedAt = json[_jsonKeyOrderBillingAddressUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderBillingAddressId] = id;
    data[_jsonKeyOrderBillingAddressUserId] = userId;
    data[_jsonKeyOrderBillingAddressName] = name;
    data[_jsonKeyOrderBillingAddressEmail] = email;
    data[_jsonKeyOrderBillingAddressPhoneNo] = phoneNo;
    data[_jsonKeyOrderBillingAddressAddress] = address;
    if (addressIds != null) {
      data[_jsonKeyOrderBillingAddressAddressIds] = addressIds!.toJson();
    }
    data[_jsonKeyOrderBillingAddressCountry] = country;
    data[_jsonKeyOrderBillingAddressState] = state;
    data[_jsonKeyOrderBillingAddressCity] = city;
    data[_jsonKeyOrderBillingAddressLatitude] = latitude;
    data[_jsonKeyOrderBillingAddressLongitude] = longitude;
    data[_jsonKeyOrderBillingAddressPostalCode] = postalCode;
    data[_jsonKeyOrderBillingAddressDefaultShipping] = defaultShipping;
    data[_jsonKeyOrderBillingAddressDefaultBilling] = defaultBilling;
    data[_jsonKeyOrderBillingAddressCreatedAt] = createdAt;
    data[_jsonKeyOrderBillingAddressUpdatedAt] = updatedAt;
    return data;
  }
}

class Order {

  int? id;
  String? sellerId;
  String? userId;
  String? deliveryHeroId;
  OrderBillingAddress? billingAddress;
  OrderShippingAddress? shippingAddress;
  String? deliveryStatus;
  String? paymentType;
  String? paymentStatus;
  String? paymentDetails;
  String? subTotal;
  String? discount;
  String? couponDiscount;
  String? totalTax;
  String? totalAmount;
  String? shippingCost;
  String? totalPayable;
  String? code;
  String? date;
  String? viewed;
  String? deliveryViewed;
  String? paymentStatusViewed;
  String? commissionCalculated;
  String? isCancelled;
  String? isDeleted;
  String? trxId;
  String? isMailed;
  String? offlineMethodId;
  String? offlineMethodFile;
  String? status;
  String? pickupHubId;
  String? cancelRequest;
  String? cancelRequestAt;
  String? deliveryHeroAssignAt;
  String? createdBy;
  String? createdAt;
  String? updatedAt;
  String? orderDate;
  String? deliveredDays;
  List<OrderOrderDetails?>? orderDetails;
  String? deliveredAt;

  Order({
    this.id,
    this.sellerId,
    this.userId,
    this.deliveryHeroId,
    this.billingAddress,
    this.shippingAddress,
    this.deliveryStatus,
    this.paymentType,
    this.paymentStatus,
    this.paymentDetails,
    this.subTotal,
    this.discount,
    this.couponDiscount,
    this.totalTax,
    this.totalAmount,
    this.shippingCost,
    this.totalPayable,
    this.code,
    this.date,
    this.viewed,
    this.deliveryViewed,
    this.paymentStatusViewed,
    this.commissionCalculated,
    this.isCancelled,
    this.isDeleted,
    this.trxId,
    this.isMailed,
    this.offlineMethodId,
    this.offlineMethodFile,
    this.status,
    this.pickupHubId,
    this.cancelRequest,
    this.cancelRequestAt,
    this.deliveryHeroAssignAt,
    this.createdBy,
    this.createdAt,
    this.updatedAt,
    this.orderDate,
    this.deliveredDays,
    this.orderDetails,
    this.deliveredAt,
  });
  Order.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyOrderId]?.toInt();
    sellerId = json[_jsonKeyOrderSellerId]?.toString();
    userId = json[_jsonKeyOrderUserId]?.toString();
    deliveryHeroId = json[_jsonKeyOrderDeliveryHeroId]?.toString();
    billingAddress = (json[_jsonKeyOrderBillingAddress] != null) ? OrderBillingAddress.fromJson(json[_jsonKeyOrderBillingAddress]) : null;
    shippingAddress = (json[_jsonKeyOrderShippingAddress] != null) ? OrderShippingAddress.fromJson(json[_jsonKeyOrderShippingAddress]) : null;
    deliveryStatus = json[_jsonKeyOrderDeliveryStatus]?.toString();
    paymentType = json[_jsonKeyOrderPaymentType]?.toString();
    paymentStatus = json[_jsonKeyOrderPaymentStatus]?.toString();
    paymentDetails = json[_jsonKeyOrderPaymentDetails]?.toString();
    subTotal = json[_jsonKeyOrderSubTotal]?.toString();
    discount = json[_jsonKeyOrderDiscount]?.toString();
    couponDiscount = json[_jsonKeyOrderCouponDiscount]?.toString();
    totalTax = json[_jsonKeyOrderTotalTax]?.toString();
    totalAmount = json[_jsonKeyOrderTotalAmount]?.toString();
    shippingCost = json[_jsonKeyOrderShippingCost]?.toString();
    totalPayable = json[_jsonKeyOrderTotalPayable]?.toString();
    code = json[_jsonKeyOrderCode]?.toString();
    date = json[_jsonKeyOrderDate]?.toString();
    viewed = json[_jsonKeyOrderViewed]?.toString();
    deliveryViewed = json[_jsonKeyOrderDeliveryViewed]?.toString();
    paymentStatusViewed = json[_jsonKeyOrderPaymentStatusViewed]?.toString();
    commissionCalculated = json[_jsonKeyOrderCommissionCalculated]?.toString();
    isCancelled = json[_jsonKeyOrderIsCancelled]?.toString();
    isDeleted = json[_jsonKeyOrderIsDeleted]?.toString();
    trxId = json[_jsonKeyOrderTrxId]?.toString();
    isMailed = json[_jsonKeyOrderIsMailed]?.toString();
    offlineMethodId = json[_jsonKeyOrderOfflineMethodId]?.toString();
    offlineMethodFile = json[_jsonKeyOrderOfflineMethodFile]?.toString();
    status = json[_jsonKeyOrderStatus]?.toString();
    pickupHubId = json[_jsonKeyOrderPickupHubId]?.toString();
    cancelRequest = json[_jsonKeyOrderCancelRequest]?.toString();
    cancelRequestAt = json[_jsonKeyOrderCancelRequestAt]?.toString();
    deliveryHeroAssignAt = json[_jsonKeyOrderDeliveryHeroAssignAt]?.toString();
    createdBy = json[_jsonKeyOrderCreatedBy]?.toString();
    createdAt = json[_jsonKeyOrderCreatedAt]?.toString();
    updatedAt = json[_jsonKeyOrderUpdatedAt]?.toString();
    orderDate = json[_jsonKeyOrderOrderDate]?.toString();
    deliveredDays = json[_jsonKeyOrderDeliveredDays]?.toString();
    if (json[_jsonKeyOrderOrderDetails] != null) {
      final v = json[_jsonKeyOrderOrderDetails];
      final arr0 = <OrderOrderDetails>[];
      v.forEach((v) {
        arr0.add(OrderOrderDetails.fromJson(v));
      });
      orderDetails = arr0;
    }
    deliveredAt = json[_jsonKeyOrderDeliveredAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOrderId] = id;
    data[_jsonKeyOrderSellerId] = sellerId;
    data[_jsonKeyOrderUserId] = userId;
    data[_jsonKeyOrderDeliveryHeroId] = deliveryHeroId;
    if (billingAddress != null) {
      data[_jsonKeyOrderBillingAddress] = billingAddress!.toJson();
    }
    if (shippingAddress != null) {
      data[_jsonKeyOrderShippingAddress] = shippingAddress!.toJson();
    }
    data[_jsonKeyOrderDeliveryStatus] = deliveryStatus;
    data[_jsonKeyOrderPaymentType] = paymentType;
    data[_jsonKeyOrderPaymentStatus] = paymentStatus;
    data[_jsonKeyOrderPaymentDetails] = paymentDetails;
    data[_jsonKeyOrderSubTotal] = subTotal;
    data[_jsonKeyOrderDiscount] = discount;
    data[_jsonKeyOrderCouponDiscount] = couponDiscount;
    data[_jsonKeyOrderTotalTax] = totalTax;
    data[_jsonKeyOrderTotalAmount] = totalAmount;
    data[_jsonKeyOrderShippingCost] = shippingCost;
    data[_jsonKeyOrderTotalPayable] = totalPayable;
    data[_jsonKeyOrderCode] = code;
    data[_jsonKeyOrderDate] = date;
    data[_jsonKeyOrderViewed] = viewed;
    data[_jsonKeyOrderDeliveryViewed] = deliveryViewed;
    data[_jsonKeyOrderPaymentStatusViewed] = paymentStatusViewed;
    data[_jsonKeyOrderCommissionCalculated] = commissionCalculated;
    data[_jsonKeyOrderIsCancelled] = isCancelled;
    data[_jsonKeyOrderIsDeleted] = isDeleted;
    data[_jsonKeyOrderTrxId] = trxId;
    data[_jsonKeyOrderIsMailed] = isMailed;
    data[_jsonKeyOrderOfflineMethodId] = offlineMethodId;
    data[_jsonKeyOrderOfflineMethodFile] = offlineMethodFile;
    data[_jsonKeyOrderStatus] = status;
    data[_jsonKeyOrderPickupHubId] = pickupHubId;
    data[_jsonKeyOrderCancelRequest] = cancelRequest;
    data[_jsonKeyOrderCancelRequestAt] = cancelRequestAt;
    data[_jsonKeyOrderDeliveryHeroAssignAt] = deliveryHeroAssignAt;
    data[_jsonKeyOrderCreatedBy] = createdBy;
    data[_jsonKeyOrderCreatedAt] = createdAt;
    data[_jsonKeyOrderUpdatedAt] = updatedAt;
    data[_jsonKeyOrderOrderDate] = orderDate;
    data[_jsonKeyOrderDeliveredDays] = deliveredDays;
    if (orderDetails != null) {
      final v = orderDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyOrderOrderDetails] = arr0;
    }
    data[_jsonKeyOrderDeliveredAt] = deliveredAt;
    return data;
  }


  static List<Map<String, dynamic>> toJsonList(List<Order> modelList) {
    List<Map<String, dynamic>> _output = modelList.map<Map<String, dynamic>>((item) => item.toJson()).toList();
    return _output;
  }

  static List<Order> fromJsonList(List<dynamic> jsonList) {
    List<Order> _output = jsonList.map<Order>((item) => Order.fromJson(item)).toList();
    return _output;
  }
}
