///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyProductId = 'id';
const String _jsonKeyProductSlug = 'slug';
const String _jsonKeyProductTitle = 'title';
const String _jsonKeyProductShortDescription = 'short_description';
const String _jsonKeyProductSpecialDiscountType = 'special_discount_type';
const String _jsonKeyProductSpecialDiscount = 'special_discount';
const String _jsonKeyProductDiscountPrice = 'discount_price';
const String _jsonKeyProductImage = 'image';
const String _jsonKeyProductPrice = 'price';
const String _jsonKeyProductRating = 'rating';
const String _jsonKeyProductTotalReviews = 'total_reviews';
const String _jsonKeyProductCurrentStock = 'current_stock';
const String _jsonKeyProductTotalSale = 'total_sale';
const String _jsonKeyProductReward = 'reward';
const String _jsonKeyProductMinimumOrderQuantity = 'minimum_order_quantity';
class Product {
/*
{
  "id": 70,
  "slug": "pineapple-suvrj",
  "title": "Pineapple",
  "short_description": "",
  "special_discount_type": "",
  "special_discount": 0,
  "discount_price": 0,
  "image": "https://hurrybuzz.com/public/images/20220526074900image_190x230-272.png",
  "price": 500,
  "rating": 0,
  "total_reviews": 0,
  "current_stock": 27,
  "total_sale": 0,
  "reward": 0,
  "minimum_order_quantity": 1
}
*/

  int? id;
  String? slug;
  String? title;
  String? shortDescription;
  String? specialDiscountType;
  int? specialDiscount;
  int? discountPrice;
  String? image;
  int? price;
  int? rating;
  int? totalReviews;
  int? currentStock;
  int? totalSale;
  int? reward;
  int? minimumOrderQuantity;

  Product({
    this.id,
    this.slug,
    this.title,
    this.shortDescription,
    this.specialDiscountType,
    this.specialDiscount,
    this.discountPrice,
    this.image,
    this.price,
    this.rating,
    this.totalReviews,
    this.currentStock,
    this.totalSale,
    this.reward,
    this.minimumOrderQuantity,
  });
  Product.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyProductId]?.toInt();
    slug = json[_jsonKeyProductSlug]?.toString();
    title = json[_jsonKeyProductTitle]?.toString();
    shortDescription = json[_jsonKeyProductShortDescription]?.toString();
    specialDiscountType = json[_jsonKeyProductSpecialDiscountType]?.toString();
    specialDiscount = json[_jsonKeyProductSpecialDiscount]?.toInt();
    discountPrice = json[_jsonKeyProductDiscountPrice]?.toInt();
    image = json[_jsonKeyProductImage]?.toString();
    price = json[_jsonKeyProductPrice]?.toInt();
    rating = json[_jsonKeyProductRating]?.toInt();
    totalReviews = json[_jsonKeyProductTotalReviews]?.toInt();
    currentStock = json[_jsonKeyProductCurrentStock]?.toInt();
    totalSale = json[_jsonKeyProductTotalSale]?.toInt();
    reward = json[_jsonKeyProductReward]?.toInt();
    minimumOrderQuantity = json[_jsonKeyProductMinimumOrderQuantity]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyProductId] = id;
    data[_jsonKeyProductSlug] = slug;
    data[_jsonKeyProductTitle] = title;
    data[_jsonKeyProductShortDescription] = shortDescription;
    data[_jsonKeyProductSpecialDiscountType] = specialDiscountType;
    data[_jsonKeyProductSpecialDiscount] = specialDiscount;
    data[_jsonKeyProductDiscountPrice] = discountPrice;
    data[_jsonKeyProductImage] = image;
    data[_jsonKeyProductPrice] = price;
    data[_jsonKeyProductRating] = rating;
    data[_jsonKeyProductTotalReviews] = totalReviews;
    data[_jsonKeyProductCurrentStock] = currentStock;
    data[_jsonKeyProductTotalSale] = totalSale;
    data[_jsonKeyProductReward] = reward;
    data[_jsonKeyProductMinimumOrderQuantity] = minimumOrderQuantity;
    return data;
  }

  static List<Map<String, dynamic>> toJsonList(List<Product> modelList) {
    List<Map<String, dynamic>> _output = modelList.map<Map<String, dynamic>>((item) => item.toJson()).toList();
    return _output;
  }

  static List<Product> fromJsonList(List<dynamic> jsonList) {
    List<Product> _output = jsonList.map<Product>((item) => Product.fromJson(item)).toList();
    return _output;
  }
}
