///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyShopShopDetails = 'shop_details';
const String _jsonKeyShopShopType = 'shop_type';
const String _jsonKeyShopAllProducts = 'all_products';
const String _jsonKeyShopAllProductsId = 'id';
const String _jsonKeyShopAllProductsBrandId = 'brand_id';
const String _jsonKeyShopAllProductsCategoryId = 'category_id';
const String _jsonKeyShopAllProductsUserId = 'user_id';
const String _jsonKeyShopAllProductsCreatedBy = 'created_by';
const String _jsonKeyShopAllProductsSlug = 'slug';
const String _jsonKeyShopAllProductsPrice = 'price';
const String _jsonKeyShopAllProductsSpecialDiscount = 'special_discount';
const String _jsonKeyShopAllProductsSpecialDiscountType = 'special_discount_type';
const String _jsonKeyShopAllProductsSpecialDiscountStart = 'special_discount_start';
const String _jsonKeyShopAllProductsSpecialDiscountEnd = 'special_discount_end';
const String _jsonKeyShopAllProductsPurchaseCost = 'purchase_cost';
const String _jsonKeyShopAllProductsBarcode = 'barcode';
const String _jsonKeyShopAllProductsVideoProvider = 'video_provider';
const String _jsonKeyShopAllProductsVideoUrl = 'video_url';
const String _jsonKeyShopAllProductsVatTaxes = 'vat_taxes';
const String _jsonKeyShopAllProductsHasVariant = 'has_variant';
const String _jsonKeyShopAllProductsThumbnail = 'thumbnail';
const String _jsonKeyShopAllProductsThumbnailId = 'thumbnail_id';
const String _jsonKeyShopAllProductsImageIds = 'image_ids';
const String _jsonKeyShopAllProductsCurrentStock = 'current_stock';
const String _jsonKeyShopAllProductsMinimumOrderQuantity = 'minimum_order_quantity';
const String _jsonKeyShopAllProductsStockNotification = 'stock_notification';
const String _jsonKeyShopAllProductsLowStockToNotify = 'low_stock_to_notify';
const String _jsonKeyShopAllProductsStockVisibility = 'stock_visibility';
const String _jsonKeyShopAllProductsTotalSale = 'total_sale';
const String _jsonKeyShopAllProductsStatus = 'status';
const String _jsonKeyShopAllProductsIsApproved = 'is_approved';
const String _jsonKeyShopAllProductsIsCatalog = 'is_catalog';
const String _jsonKeyShopAllProductsExternalLink = 'external_link';
const String _jsonKeyShopAllProductsIsFeatured = 'is_featured';
const String _jsonKeyShopAllProductsIsClassified = 'is_classified';
const String _jsonKeyShopAllProductsIsWholesale = 'is_wholesale';
const String _jsonKeyShopAllProductsIsDigital = 'is_digital';
const String _jsonKeyShopAllProductsIsRefundable = 'is_refundable';
const String _jsonKeyShopAllProductsTodaysDeal = 'todays_deal';
const String _jsonKeyShopAllProductsRating = 'rating';
const String _jsonKeyShopAllProductsViewed = 'viewed';
const String _jsonKeyShopAllProductsShippingType = 'shipping_type';
const String _jsonKeyShopAllProductsShippingFee = 'shipping_fee';
const String _jsonKeyShopAllProductsShippingFeeDependOnQuantity = 'shipping_fee_depend_on_quantity';
const String _jsonKeyShopAllProductsEstimatedShippingDays = 'estimated_shipping_days';
const String _jsonKeyShopAllProductsCashOnDelivery = 'cash_on_delivery';
const String _jsonKeyShopAllProductsMetaImage = 'meta_image';
const String _jsonKeyShopAllProductsProductFile = 'product_file';
const String _jsonKeyShopAllProductsProductFileId = 'product_file_id';
const String _jsonKeyShopAllProductsMetaImageId = 'meta_image_id';
const String _jsonKeyShopAllProductsReward = 'reward';
const String _jsonKeyShopAllProductsIsDeleted = 'is_deleted';
const String _jsonKeyShopAllProductsDeletedAt = 'deleted_at';
const String _jsonKeyShopAllProductsCreatedAt = 'created_at';
const String _jsonKeyShopAllProductsUpdatedAt = 'updated_at';
const String _jsonKeyShopAllProductsProductName = 'product_name';
const String _jsonKeyShopAllProductsImage_190x230 = 'image_190x230';
const String _jsonKeyShopAllProductsImage_40x40 = 'image_40x40';
const String _jsonKeyShopAllProductsImage_72x72 = 'image_72x72';
const String _jsonKeyShopAllProductsImage_110x122 = 'image_110x122';
const String _jsonKeyShopAllProductsSpecialDiscountCheck = 'special_discount_check';
const String _jsonKeyShopAllProductsDiscountPercentage = 'discount_percentage';
const String _jsonKeyShopAllProductsProductLanguages = 'product_languages';
const String _jsonKeyShopAllProductsProductLanguagesId = 'id';
const String _jsonKeyShopAllProductsProductLanguagesProductId = 'product_id';
const String _jsonKeyShopAllProductsProductLanguagesLang = 'lang';
const String _jsonKeyShopAllProductsProductLanguagesName = 'name';
const String _jsonKeyShopAllProductsProductLanguagesShortDescription = 'short_description';
const String _jsonKeyShopAllProductsProductLanguagesDescription = 'description';
const String _jsonKeyShopAllProductsProductLanguagesPdfSpecificationId = 'pdf_specification_id';
const String _jsonKeyShopAllProductsProductLanguagesTags = 'tags';
const String _jsonKeyShopAllProductsProductLanguagesUnit = 'unit';
const String _jsonKeyShopAllProductsProductLanguagesMetaTitle = 'meta_title';
const String _jsonKeyShopAllProductsProductLanguagesMetaDescription = 'meta_description';
const String _jsonKeyShopAllProductsProductLanguagesMetaKeywords = 'meta_keywords';
const String _jsonKeyShopAllProductsProductLanguagesCreatedAt = 'created_at';
const String _jsonKeyShopAllProductsProductLanguagesUpdatedAt = 'updated_at';
const String _jsonKeyShopAllProductsProductLanguagesSpecification = 'specification';
class ShopAllProductsProductLanguages {
/*
{
  "id": 71,
  "product_id": "71",
  "lang": "en",
  "name": "test",
  "short_description": "<p>fsgdg</p>",
  "description": "<p>tetete</p>",
  "pdf_specification_id": null,
  "tags": "test",
  "unit": "1",
  "meta_title": "",
  "meta_description": "",
  "meta_keywords": "",
  "created_at": "2022-06-09T06:05:37.000000Z",
  "updated_at": "2022-06-09T06:05:37.000000Z",
  "specification": false
}
*/

  int? id;
  String? productId;
  String? lang;
  String? name;
  String? shortDescription;
  String? description;
  String? pdfSpecificationId;
  String? tags;
  String? unit;
  String? metaTitle;
  String? metaDescription;
  String? metaKeywords;
  String? createdAt;
  String? updatedAt;
  bool? specification;

  ShopAllProductsProductLanguages({
    this.id,
    this.productId,
    this.lang,
    this.name,
    this.shortDescription,
    this.description,
    this.pdfSpecificationId,
    this.tags,
    this.unit,
    this.metaTitle,
    this.metaDescription,
    this.metaKeywords,
    this.createdAt,
    this.updatedAt,
    this.specification,
  });
  ShopAllProductsProductLanguages.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyShopAllProductsProductLanguagesId]?.toInt();
    productId = json[_jsonKeyShopAllProductsProductLanguagesProductId]?.toString();
    lang = json[_jsonKeyShopAllProductsProductLanguagesLang]?.toString();
    name = json[_jsonKeyShopAllProductsProductLanguagesName]?.toString();
    shortDescription = json[_jsonKeyShopAllProductsProductLanguagesShortDescription]?.toString();
    description = json[_jsonKeyShopAllProductsProductLanguagesDescription]?.toString();
    pdfSpecificationId = json[_jsonKeyShopAllProductsProductLanguagesPdfSpecificationId]?.toString();
    tags = json[_jsonKeyShopAllProductsProductLanguagesTags]?.toString();
    unit = json[_jsonKeyShopAllProductsProductLanguagesUnit]?.toString();
    metaTitle = json[_jsonKeyShopAllProductsProductLanguagesMetaTitle]?.toString();
    metaDescription = json[_jsonKeyShopAllProductsProductLanguagesMetaDescription]?.toString();
    metaKeywords = json[_jsonKeyShopAllProductsProductLanguagesMetaKeywords]?.toString();
    createdAt = json[_jsonKeyShopAllProductsProductLanguagesCreatedAt]?.toString();
    updatedAt = json[_jsonKeyShopAllProductsProductLanguagesUpdatedAt]?.toString();
    specification = json[_jsonKeyShopAllProductsProductLanguagesSpecification];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopAllProductsProductLanguagesId] = id;
    data[_jsonKeyShopAllProductsProductLanguagesProductId] = productId;
    data[_jsonKeyShopAllProductsProductLanguagesLang] = lang;
    data[_jsonKeyShopAllProductsProductLanguagesName] = name;
    data[_jsonKeyShopAllProductsProductLanguagesShortDescription] = shortDescription;
    data[_jsonKeyShopAllProductsProductLanguagesDescription] = description;
    data[_jsonKeyShopAllProductsProductLanguagesPdfSpecificationId] = pdfSpecificationId;
    data[_jsonKeyShopAllProductsProductLanguagesTags] = tags;
    data[_jsonKeyShopAllProductsProductLanguagesUnit] = unit;
    data[_jsonKeyShopAllProductsProductLanguagesMetaTitle] = metaTitle;
    data[_jsonKeyShopAllProductsProductLanguagesMetaDescription] = metaDescription;
    data[_jsonKeyShopAllProductsProductLanguagesMetaKeywords] = metaKeywords;
    data[_jsonKeyShopAllProductsProductLanguagesCreatedAt] = createdAt;
    data[_jsonKeyShopAllProductsProductLanguagesUpdatedAt] = updatedAt;
    data[_jsonKeyShopAllProductsProductLanguagesSpecification] = specification;
    return data;
  }
}

const String _jsonKeyShopAllProductsMetaImageStorage = 'storage';
const String _jsonKeyShopAllProductsMetaImageOriginalImage = 'original_image';
const String _jsonKeyShopAllProductsMetaImageImage_40x40 = 'image_40x40';
const String _jsonKeyShopAllProductsMetaImageImage_72x72 = 'image_72x72';
const String _jsonKeyShopAllProductsMetaImageImage_190x230 = 'image_190x230';
const String _jsonKeyShopAllProductsMetaImageImage_110x122 = 'image_110x122';
const String _jsonKeyShopAllProductsMetaImageImage_320x320 = 'image_320x320';
const String _jsonKeyShopAllProductsMetaImageImageThumbnail = 'image_thumbnail';
class ShopAllProductsMetaImage {
/*
{
  "storage": "local",
  "original_image": "images/20220609120453_original__media_39.jpg",
  "image_40x40": "images/20220609120453image_40x40_media_243.png",
  "image_72x72": "images/20220609120453image_72x72_media_99.png",
  "image_190x230": "images/20220609120537image_190x230-63.png",
  "image_110x122": "images/20220609120453image_110x122_media_85.png",
  "image_320x320": "images/20220609120453image_300x200_media_50.png",
  "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;

  ShopAllProductsMetaImage({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
  });
  ShopAllProductsMetaImage.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyShopAllProductsMetaImageStorage]?.toString();
    originalImage = json[_jsonKeyShopAllProductsMetaImageOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyShopAllProductsMetaImageImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyShopAllProductsMetaImageImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyShopAllProductsMetaImageImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyShopAllProductsMetaImageImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyShopAllProductsMetaImageImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyShopAllProductsMetaImageImageThumbnail]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopAllProductsMetaImageStorage] = storage;
    data[_jsonKeyShopAllProductsMetaImageOriginalImage] = originalImage;
    data[_jsonKeyShopAllProductsMetaImageImage_40x40] = image_40x40;
    data[_jsonKeyShopAllProductsMetaImageImage_72x72] = image_72x72;
    data[_jsonKeyShopAllProductsMetaImageImage_190x230] = image_190x230;
    data[_jsonKeyShopAllProductsMetaImageImage_110x122] = image_110x122;
    data[_jsonKeyShopAllProductsMetaImageImage_320x320] = image_320x320;
    data[_jsonKeyShopAllProductsMetaImageImageThumbnail] = imageThumbnail;
    return data;
  }
}

const String _jsonKeyShopAllProductsThumbnailStorage = 'storage';
const String _jsonKeyShopAllProductsThumbnailOriginalImage = 'original_image';
const String _jsonKeyShopAllProductsThumbnailImage_40x40 = 'image_40x40';
const String _jsonKeyShopAllProductsThumbnailImage_72x72 = 'image_72x72';
const String _jsonKeyShopAllProductsThumbnailImage_190x230 = 'image_190x230';
const String _jsonKeyShopAllProductsThumbnailImage_110x122 = 'image_110x122';
const String _jsonKeyShopAllProductsThumbnailImage_320x320 = 'image_320x320';
const String _jsonKeyShopAllProductsThumbnailImageThumbnail = 'image_thumbnail';
class ShopAllProductsThumbnail {
/*
{
  "storage": "local",
  "original_image": "images/20220609120453_original__media_39.jpg",
  "image_40x40": "images/20220609120453image_40x40_media_243.png",
  "image_72x72": "images/20220609120453image_72x72_media_99.png",
  "image_190x230": "images/20220609120537image_190x230-63.png",
  "image_110x122": "images/20220609120453image_110x122_media_85.png",
  "image_320x320": "images/20220609120453image_300x200_media_50.png",
  "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;

  ShopAllProductsThumbnail({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
  });
  ShopAllProductsThumbnail.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyShopAllProductsThumbnailStorage]?.toString();
    originalImage = json[_jsonKeyShopAllProductsThumbnailOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyShopAllProductsThumbnailImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyShopAllProductsThumbnailImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyShopAllProductsThumbnailImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyShopAllProductsThumbnailImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyShopAllProductsThumbnailImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyShopAllProductsThumbnailImageThumbnail]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopAllProductsThumbnailStorage] = storage;
    data[_jsonKeyShopAllProductsThumbnailOriginalImage] = originalImage;
    data[_jsonKeyShopAllProductsThumbnailImage_40x40] = image_40x40;
    data[_jsonKeyShopAllProductsThumbnailImage_72x72] = image_72x72;
    data[_jsonKeyShopAllProductsThumbnailImage_190x230] = image_190x230;
    data[_jsonKeyShopAllProductsThumbnailImage_110x122] = image_110x122;
    data[_jsonKeyShopAllProductsThumbnailImage_320x320] = image_320x320;
    data[_jsonKeyShopAllProductsThumbnailImageThumbnail] = imageThumbnail;
    return data;
  }
}

class ShopAllProducts {

  int? id;
  String? brandId;
  String? categoryId;
  String? userId;
  String? createdBy;
  String? slug;
  String? price;
  String? specialDiscount;
  String? specialDiscountType;
  String? specialDiscountStart;
  String? specialDiscountEnd;
  String? purchaseCost;
  String? barcode;
  String? videoProvider;
  String? videoUrl;
  String? vatTaxes;
  String? hasVariant;
  ShopAllProductsThumbnail? thumbnail;
  String? thumbnailId;
  String? imageIds;
  String? currentStock;
  String? minimumOrderQuantity;
  String? stockNotification;
  String? lowStockToNotify;
  String? stockVisibility;
  String? totalSale;
  String? status;
  String? isApproved;
  String? isCatalog;
  String? externalLink;
  String? isFeatured;
  String? isClassified;
  String? isWholesale;
  String? isDigital;
  String? isRefundable;
  String? todaysDeal;
  int? rating;
  String? viewed;
  String? shippingType;
  String? shippingFee;
  String? shippingFeeDependOnQuantity;
  String? estimatedShippingDays;
  String? cashOnDelivery;
  ShopAllProductsMetaImage? metaImage;
  String? productFile;
  String? productFileId;
  String? metaImageId;
  String? reward;
  String? isDeleted;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;
  String? productName;
  String? image_190x230;
  String? image_40x40;
  String? image_72x72;
  String? image_110x122;
  int? specialDiscountCheck;
  int? discountPercentage;
  List<ShopAllProductsProductLanguages?>? productLanguages;

  ShopAllProducts({
    this.id,
    this.brandId,
    this.categoryId,
    this.userId,
    this.createdBy,
    this.slug,
    this.price,
    this.specialDiscount,
    this.specialDiscountType,
    this.specialDiscountStart,
    this.specialDiscountEnd,
    this.purchaseCost,
    this.barcode,
    this.videoProvider,
    this.videoUrl,
    this.vatTaxes,
    this.hasVariant,
    this.thumbnail,
    this.thumbnailId,
    this.imageIds,
    this.currentStock,
    this.minimumOrderQuantity,
    this.stockNotification,
    this.lowStockToNotify,
    this.stockVisibility,
    this.totalSale,
    this.status,
    this.isApproved,
    this.isCatalog,
    this.externalLink,
    this.isFeatured,
    this.isClassified,
    this.isWholesale,
    this.isDigital,
    this.isRefundable,
    this.todaysDeal,
    this.rating,
    this.viewed,
    this.shippingType,
    this.shippingFee,
    this.shippingFeeDependOnQuantity,
    this.estimatedShippingDays,
    this.cashOnDelivery,
    this.metaImage,
    this.productFile,
    this.productFileId,
    this.metaImageId,
    this.reward,
    this.isDeleted,
    this.deletedAt,
    this.createdAt,
    this.updatedAt,
    this.productName,
    this.image_190x230,
    this.image_40x40,
    this.image_72x72,
    this.image_110x122,
    this.specialDiscountCheck,
    this.discountPercentage,
    this.productLanguages,
  });
  ShopAllProducts.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyShopAllProductsId]?.toInt();
    brandId = json[_jsonKeyShopAllProductsBrandId]?.toString();
    categoryId = json[_jsonKeyShopAllProductsCategoryId]?.toString();
    userId = json[_jsonKeyShopAllProductsUserId]?.toString();
    createdBy = json[_jsonKeyShopAllProductsCreatedBy]?.toString();
    slug = json[_jsonKeyShopAllProductsSlug]?.toString();
    price = json[_jsonKeyShopAllProductsPrice]?.toString();
    specialDiscount = json[_jsonKeyShopAllProductsSpecialDiscount]?.toString();
    specialDiscountType = json[_jsonKeyShopAllProductsSpecialDiscountType]?.toString();
    specialDiscountStart = json[_jsonKeyShopAllProductsSpecialDiscountStart]?.toString();
    specialDiscountEnd = json[_jsonKeyShopAllProductsSpecialDiscountEnd]?.toString();
    purchaseCost = json[_jsonKeyShopAllProductsPurchaseCost]?.toString();
    barcode = json[_jsonKeyShopAllProductsBarcode]?.toString();
    videoProvider = json[_jsonKeyShopAllProductsVideoProvider]?.toString();
    videoUrl = json[_jsonKeyShopAllProductsVideoUrl]?.toString();
    vatTaxes = json[_jsonKeyShopAllProductsVatTaxes]?.toString();
    hasVariant = json[_jsonKeyShopAllProductsHasVariant]?.toString();
    thumbnail = (json[_jsonKeyShopAllProductsThumbnail] != null) ? ShopAllProductsThumbnail.fromJson(json[_jsonKeyShopAllProductsThumbnail]) : null;
    thumbnailId = json[_jsonKeyShopAllProductsThumbnailId]?.toString();
    imageIds = json[_jsonKeyShopAllProductsImageIds]?.toString();
    currentStock = json[_jsonKeyShopAllProductsCurrentStock]?.toString();
    minimumOrderQuantity = json[_jsonKeyShopAllProductsMinimumOrderQuantity]?.toString();
    stockNotification = json[_jsonKeyShopAllProductsStockNotification]?.toString();
    lowStockToNotify = json[_jsonKeyShopAllProductsLowStockToNotify]?.toString();
    stockVisibility = json[_jsonKeyShopAllProductsStockVisibility]?.toString();
    totalSale = json[_jsonKeyShopAllProductsTotalSale]?.toString();
    status = json[_jsonKeyShopAllProductsStatus]?.toString();
    isApproved = json[_jsonKeyShopAllProductsIsApproved]?.toString();
    isCatalog = json[_jsonKeyShopAllProductsIsCatalog]?.toString();
    externalLink = json[_jsonKeyShopAllProductsExternalLink]?.toString();
    isFeatured = json[_jsonKeyShopAllProductsIsFeatured]?.toString();
    isClassified = json[_jsonKeyShopAllProductsIsClassified]?.toString();
    isWholesale = json[_jsonKeyShopAllProductsIsWholesale]?.toString();
    isDigital = json[_jsonKeyShopAllProductsIsDigital]?.toString();
    isRefundable = json[_jsonKeyShopAllProductsIsRefundable]?.toString();
    todaysDeal = json[_jsonKeyShopAllProductsTodaysDeal]?.toString();
    rating = json[_jsonKeyShopAllProductsRating]?.toInt();
    viewed = json[_jsonKeyShopAllProductsViewed]?.toString();
    shippingType = json[_jsonKeyShopAllProductsShippingType]?.toString();
    shippingFee = json[_jsonKeyShopAllProductsShippingFee]?.toString();
    shippingFeeDependOnQuantity = json[_jsonKeyShopAllProductsShippingFeeDependOnQuantity]?.toString();
    estimatedShippingDays = json[_jsonKeyShopAllProductsEstimatedShippingDays]?.toString();
    cashOnDelivery = json[_jsonKeyShopAllProductsCashOnDelivery]?.toString();
    metaImage = (json[_jsonKeyShopAllProductsMetaImage] != null) ? ShopAllProductsMetaImage.fromJson(json[_jsonKeyShopAllProductsMetaImage]) : null;
    productFile = json[_jsonKeyShopAllProductsProductFile]?.toString();
    productFileId = json[_jsonKeyShopAllProductsProductFileId]?.toString();
    metaImageId = json[_jsonKeyShopAllProductsMetaImageId]?.toString();
    reward = json[_jsonKeyShopAllProductsReward]?.toString();
    isDeleted = json[_jsonKeyShopAllProductsIsDeleted]?.toString();
    deletedAt = json[_jsonKeyShopAllProductsDeletedAt]?.toString();
    createdAt = json[_jsonKeyShopAllProductsCreatedAt]?.toString();
    updatedAt = json[_jsonKeyShopAllProductsUpdatedAt]?.toString();
    productName = json[_jsonKeyShopAllProductsProductName]?.toString();
    image_190x230 = json[_jsonKeyShopAllProductsImage_190x230]?.toString();
    image_40x40 = json[_jsonKeyShopAllProductsImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyShopAllProductsImage_72x72]?.toString();
    image_110x122 = json[_jsonKeyShopAllProductsImage_110x122]?.toString();
    specialDiscountCheck = json[_jsonKeyShopAllProductsSpecialDiscountCheck]?.toInt();
    discountPercentage = json[_jsonKeyShopAllProductsDiscountPercentage]?.toInt();
    if (json[_jsonKeyShopAllProductsProductLanguages] != null) {
      final v = json[_jsonKeyShopAllProductsProductLanguages];
      final arr0 = <ShopAllProductsProductLanguages>[];
      v.forEach((v) {
        arr0.add(ShopAllProductsProductLanguages.fromJson(v));
      });
      productLanguages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopAllProductsId] = id;
    data[_jsonKeyShopAllProductsBrandId] = brandId;
    data[_jsonKeyShopAllProductsCategoryId] = categoryId;
    data[_jsonKeyShopAllProductsUserId] = userId;
    data[_jsonKeyShopAllProductsCreatedBy] = createdBy;
    data[_jsonKeyShopAllProductsSlug] = slug;
    data[_jsonKeyShopAllProductsPrice] = price;
    data[_jsonKeyShopAllProductsSpecialDiscount] = specialDiscount;
    data[_jsonKeyShopAllProductsSpecialDiscountType] = specialDiscountType;
    data[_jsonKeyShopAllProductsSpecialDiscountStart] = specialDiscountStart;
    data[_jsonKeyShopAllProductsSpecialDiscountEnd] = specialDiscountEnd;
    data[_jsonKeyShopAllProductsPurchaseCost] = purchaseCost;
    data[_jsonKeyShopAllProductsBarcode] = barcode;
    data[_jsonKeyShopAllProductsVideoProvider] = videoProvider;
    data[_jsonKeyShopAllProductsVideoUrl] = videoUrl;
    data[_jsonKeyShopAllProductsVatTaxes] = vatTaxes;
    data[_jsonKeyShopAllProductsHasVariant] = hasVariant;
    if (thumbnail != null) {
      data[_jsonKeyShopAllProductsThumbnail] = thumbnail!.toJson();
    }
    data[_jsonKeyShopAllProductsThumbnailId] = thumbnailId;
    data[_jsonKeyShopAllProductsImageIds] = imageIds;
    data[_jsonKeyShopAllProductsCurrentStock] = currentStock;
    data[_jsonKeyShopAllProductsMinimumOrderQuantity] = minimumOrderQuantity;
    data[_jsonKeyShopAllProductsStockNotification] = stockNotification;
    data[_jsonKeyShopAllProductsLowStockToNotify] = lowStockToNotify;
    data[_jsonKeyShopAllProductsStockVisibility] = stockVisibility;
    data[_jsonKeyShopAllProductsTotalSale] = totalSale;
    data[_jsonKeyShopAllProductsStatus] = status;
    data[_jsonKeyShopAllProductsIsApproved] = isApproved;
    data[_jsonKeyShopAllProductsIsCatalog] = isCatalog;
    data[_jsonKeyShopAllProductsExternalLink] = externalLink;
    data[_jsonKeyShopAllProductsIsFeatured] = isFeatured;
    data[_jsonKeyShopAllProductsIsClassified] = isClassified;
    data[_jsonKeyShopAllProductsIsWholesale] = isWholesale;
    data[_jsonKeyShopAllProductsIsDigital] = isDigital;
    data[_jsonKeyShopAllProductsIsRefundable] = isRefundable;
    data[_jsonKeyShopAllProductsTodaysDeal] = todaysDeal;
    data[_jsonKeyShopAllProductsRating] = rating;
    data[_jsonKeyShopAllProductsViewed] = viewed;
    data[_jsonKeyShopAllProductsShippingType] = shippingType;
    data[_jsonKeyShopAllProductsShippingFee] = shippingFee;
    data[_jsonKeyShopAllProductsShippingFeeDependOnQuantity] = shippingFeeDependOnQuantity;
    data[_jsonKeyShopAllProductsEstimatedShippingDays] = estimatedShippingDays;
    data[_jsonKeyShopAllProductsCashOnDelivery] = cashOnDelivery;
    if (metaImage != null) {
      data[_jsonKeyShopAllProductsMetaImage] = metaImage!.toJson();
    }
    data[_jsonKeyShopAllProductsProductFile] = productFile;
    data[_jsonKeyShopAllProductsProductFileId] = productFileId;
    data[_jsonKeyShopAllProductsMetaImageId] = metaImageId;
    data[_jsonKeyShopAllProductsReward] = reward;
    data[_jsonKeyShopAllProductsIsDeleted] = isDeleted;
    data[_jsonKeyShopAllProductsDeletedAt] = deletedAt;
    data[_jsonKeyShopAllProductsCreatedAt] = createdAt;
    data[_jsonKeyShopAllProductsUpdatedAt] = updatedAt;
    data[_jsonKeyShopAllProductsProductName] = productName;
    data[_jsonKeyShopAllProductsImage_190x230] = image_190x230;
    data[_jsonKeyShopAllProductsImage_40x40] = image_40x40;
    data[_jsonKeyShopAllProductsImage_72x72] = image_72x72;
    data[_jsonKeyShopAllProductsImage_110x122] = image_110x122;
    data[_jsonKeyShopAllProductsSpecialDiscountCheck] = specialDiscountCheck;
    data[_jsonKeyShopAllProductsDiscountPercentage] = discountPercentage;
    if (productLanguages != null) {
      final v = productLanguages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyShopAllProductsProductLanguages] = arr0;
    }
    return data;
  }

  static List<ShopAllProducts> fromJsonList(List<dynamic> jsonList) {
    List<ShopAllProducts> _output = jsonList.map<ShopAllProducts>((item) => ShopAllProducts.fromJson(item)).toList();
    return _output;
  }
}




const String _jsonKeyShopShopDetailsId = 'id';
const String _jsonKeyShopShopDetailsUserId = 'user_id';
const String _jsonKeyShopShopDetailsShopName = 'shop_name';
const String _jsonKeyShopShopDetailsSlug = 'slug';
const String _jsonKeyShopShopDetailsVerifiedAt = 'verified_at';
const String _jsonKeyShopShopDetailsLicenseNo = 'license_no';
const String _jsonKeyShopShopDetailsTaxPaper = 'tax_paper';
const String _jsonKeyShopShopDetailsLogo = 'logo';
const String _jsonKeyShopShopDetailsBanner = 'banner';
const String _jsonKeyShopShopDetailsShopPageContents = 'shop_page_contents';
const String _jsonKeyShopShopDetailsShopBannerId = 'shop_banner_id';
const String _jsonKeyShopShopDetailsShopBanner = 'shop_banner';
const String _jsonKeyShopShopDetailsShopTagline = 'shop_tagline';
const String _jsonKeyShopShopDetailsPhoneNo = 'phone_no';
const String _jsonKeyShopShopDetailsShopEmail = 'shop_email';
const String _jsonKeyShopShopDetailsWebsite = 'website';
const String _jsonKeyShopShopDetailsAddress = 'address';
const String _jsonKeyShopShopDetailsRatingCount = 'rating_count';
const String _jsonKeyShopShopDetailsReviewsCount = 'reviews_count';
const String _jsonKeyShopShopDetailsFacebook = 'facebook';
const String _jsonKeyShopShopDetailsGoogle = 'google';
const String _jsonKeyShopShopDetailsTwitter = 'twitter';
const String _jsonKeyShopShopDetailsYoutube = 'youtube';
const String _jsonKeyShopShopDetailsMetaTitle = 'meta_title';
const String _jsonKeyShopShopDetailsMetaDescription = 'meta_description';
const String _jsonKeyShopShopDetailsStateId = 'state_id';
const String _jsonKeyShopShopDetailsCityId = 'city_id';
const String _jsonKeyShopShopDetailsTownId = 'town_id';
const String _jsonKeyShopShopDetailsLatitude = 'latitude';
const String _jsonKeyShopShopDetailsLongitude = 'longitude';
const String _jsonKeyShopShopDetailsScheduleId = 'schedule_id';
const String _jsonKeyShopShopDetailsAccountType = 'account_type';
const String _jsonKeyShopShopDetailsShopTypeId = 'shop_type_id';
const String _jsonKeyShopShopDetailsCreatedAt = 'created_at';
const String _jsonKeyShopShopDetailsUpdatedAt = 'updated_at';
const String _jsonKeyShopShopDetailsImage_105x75 = 'image_105x75';
const String _jsonKeyShopShopDetailsImage_197x152 = 'image_197x152';
const String _jsonKeyShopShopDetailsImage_1905x350 = 'image_1905x350';
const String _jsonKeyShopShopDetailsImage_90x60 = 'image_90x60';
const String _jsonKeyShopShopDetailsImage_82x82 = 'image_82x82';
const String _jsonKeyShopShopDetailsImage_120x80 = 'image_120x80';
const String _jsonKeyShopShopDetailsImage_297x146 = 'image_297x146';
const String _jsonKeyShopShopDetailsImage_617x145 = 'image_617x145';
const String _jsonKeyShopShopDetailsStartDate = 'start_date';
const String _jsonKeyShopShopDetailsImage_1920x412 = 'image_1920x412';
const String _jsonKeyShopShopDetailsShopBannerStorage = 'storage';
const String _jsonKeyShopShopDetailsShopBannerOriginalImage = 'original_image';
const String _jsonKeyShopShopDetailsShopBannerImage_40x40 = 'image_40x40';
const String _jsonKeyShopShopDetailsShopBannerImage_72x72 = 'image_72x72';
const String _jsonKeyShopShopDetailsShopBannerImage_190x230 = 'image_190x230';
const String _jsonKeyShopShopDetailsShopBannerImage_110x122 = 'image_110x122';
const String _jsonKeyShopShopDetailsShopBannerImage_320x320 = 'image_320x320';
const String _jsonKeyShopShopDetailsShopBannerImageThumbnail = 'image_thumbnail';
const String _jsonKeyShopShopDetailsShopBannerImage_1905x350 = 'image_1905x350';
class ShopShopDetailsShopBanner {
/*
{
  "storage": "local",
  "original_image": "images/20220609120453_original__media_39.jpg",
  "image_40x40": "images/20220609120453image_40x40_media_243.png",
  "image_72x72": "images/20220609120453image_72x72_media_99.png",
  "image_190x230": "images/20220609120537image_190x230-63.png",
  "image_110x122": "images/20220609120453image_110x122_media_85.png",
  "image_320x320": "images/20220609120453image_300x200_media_50.png",
  "image_thumbnail": "images/20220609120453image_thumbnail_media_399.png",
  "image_1905x350": "images/20220609124152image_1905x350-71.png"
}
*/

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;
  String? image_1905x350;

  ShopShopDetailsShopBanner({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
    this.image_1905x350,
  });
  ShopShopDetailsShopBanner.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyShopShopDetailsShopBannerStorage]?.toString();
    originalImage = json[_jsonKeyShopShopDetailsShopBannerOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyShopShopDetailsShopBannerImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyShopShopDetailsShopBannerImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyShopShopDetailsShopBannerImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyShopShopDetailsShopBannerImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyShopShopDetailsShopBannerImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyShopShopDetailsShopBannerImageThumbnail]?.toString();
    image_1905x350 = json[_jsonKeyShopShopDetailsShopBannerImage_1905x350]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopShopDetailsShopBannerStorage] = storage;
    data[_jsonKeyShopShopDetailsShopBannerOriginalImage] = originalImage;
    data[_jsonKeyShopShopDetailsShopBannerImage_40x40] = image_40x40;
    data[_jsonKeyShopShopDetailsShopBannerImage_72x72] = image_72x72;
    data[_jsonKeyShopShopDetailsShopBannerImage_190x230] = image_190x230;
    data[_jsonKeyShopShopDetailsShopBannerImage_110x122] = image_110x122;
    data[_jsonKeyShopShopDetailsShopBannerImage_320x320] = image_320x320;
    data[_jsonKeyShopShopDetailsShopBannerImageThumbnail] = imageThumbnail;
    data[_jsonKeyShopShopDetailsShopBannerImage_1905x350] = image_1905x350;
    return data;
  }
}

const String _jsonKeyShopShopDetailsShopPageContentsNewArrival = 'new_arrival';
class ShopShopDetailsShopPageContents {
/*
{
  "new_arrival": "1"
}
*/

  String? newArrival;

  ShopShopDetailsShopPageContents({
    this.newArrival,
  });
  ShopShopDetailsShopPageContents.fromJson(Map<String, dynamic> json) {
    newArrival = json[_jsonKeyShopShopDetailsShopPageContentsNewArrival]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopShopDetailsShopPageContentsNewArrival] = newArrival;
    return data;
  }
}

const String _jsonKeyShopShopDetailsBannerStorage = 'storage';
const String _jsonKeyShopShopDetailsBannerOriginalImage = 'original_image';
const String _jsonKeyShopShopDetailsBannerImage_100x38 = 'image_100x38';
const String _jsonKeyShopShopDetailsBannerImage_89x33 = 'image_89x33';
const String _jsonKeyShopShopDetailsBannerImage_118x45 = 'image_118x45';
const String _jsonKeyShopShopDetailsBannerImage_48x25 = 'image_48x25';
const String _jsonKeyShopShopDetailsBannerImage_40x40 = 'image_40x40';
const String _jsonKeyShopShopDetailsBannerImage_197x152 = 'image_197x152';
const String _jsonKeyShopShopDetailsBannerImage_120x80 = 'image_120x80';
const String _jsonKeyShopShopDetailsBannerImage_82x82 = 'image_82x82';
const String _jsonKeyShopShopDetailsBannerImage_617x145 = 'image_617x145';
const String _jsonKeyShopShopDetailsBannerImage_297x146 = 'image_297x146';
const String _jsonKeyShopShopDetailsBannerImage_72x72 = 'image_72x72';
const String _jsonKeyShopShopDetailsBannerImage_270x260 = 'image_270x260';
const String _jsonKeyShopShopDetailsBannerImage_320x320 = 'image_320x320';
class ShopShopDetailsBanner {

  String? storage;
  String? originalImage;
  String? image_100x38;
  String? image_89x33;
  String? image_118x45;
  String? image_48x25;
  String? image_40x40;
  String? image_197x152;
  String? image_120x80;
  String? image_82x82;
  String? image_617x145;
  String? image_297x146;
  String? image_72x72;
  String? image_270x260;
  String? image_320x320;

  ShopShopDetailsBanner({
    this.storage,
    this.originalImage,
    this.image_100x38,
    this.image_89x33,
    this.image_118x45,
    this.image_48x25,
    this.image_40x40,
    this.image_197x152,
    this.image_120x80,
    this.image_82x82,
    this.image_617x145,
    this.image_297x146,
    this.image_72x72,
    this.image_270x260,
    this.image_320x320,
  });
  ShopShopDetailsBanner.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyShopShopDetailsBannerStorage]?.toString();
    originalImage = json[_jsonKeyShopShopDetailsBannerOriginalImage]?.toString();
    image_100x38 = json[_jsonKeyShopShopDetailsBannerImage_100x38]?.toString();
    image_89x33 = json[_jsonKeyShopShopDetailsBannerImage_89x33]?.toString();
    image_118x45 = json[_jsonKeyShopShopDetailsBannerImage_118x45]?.toString();
    image_48x25 = json[_jsonKeyShopShopDetailsBannerImage_48x25]?.toString();
    image_40x40 = json[_jsonKeyShopShopDetailsBannerImage_40x40]?.toString();
    image_197x152 = json[_jsonKeyShopShopDetailsBannerImage_197x152]?.toString();
    image_120x80 = json[_jsonKeyShopShopDetailsBannerImage_120x80]?.toString();
    image_82x82 = json[_jsonKeyShopShopDetailsBannerImage_82x82]?.toString();
    image_617x145 = json[_jsonKeyShopShopDetailsBannerImage_617x145]?.toString();
    image_297x146 = json[_jsonKeyShopShopDetailsBannerImage_297x146]?.toString();
    image_72x72 = json[_jsonKeyShopShopDetailsBannerImage_72x72]?.toString();
    image_270x260 = json[_jsonKeyShopShopDetailsBannerImage_270x260]?.toString();
    image_320x320 = json[_jsonKeyShopShopDetailsBannerImage_320x320]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopShopDetailsBannerStorage] = storage;
    data[_jsonKeyShopShopDetailsBannerOriginalImage] = originalImage;
    data[_jsonKeyShopShopDetailsBannerImage_100x38] = image_100x38;
    data[_jsonKeyShopShopDetailsBannerImage_89x33] = image_89x33;
    data[_jsonKeyShopShopDetailsBannerImage_118x45] = image_118x45;
    data[_jsonKeyShopShopDetailsBannerImage_48x25] = image_48x25;
    data[_jsonKeyShopShopDetailsBannerImage_40x40] = image_40x40;
    data[_jsonKeyShopShopDetailsBannerImage_197x152] = image_197x152;
    data[_jsonKeyShopShopDetailsBannerImage_120x80] = image_120x80;
    data[_jsonKeyShopShopDetailsBannerImage_82x82] = image_82x82;
    data[_jsonKeyShopShopDetailsBannerImage_617x145] = image_617x145;
    data[_jsonKeyShopShopDetailsBannerImage_297x146] = image_297x146;
    data[_jsonKeyShopShopDetailsBannerImage_72x72] = image_72x72;
    data[_jsonKeyShopShopDetailsBannerImage_270x260] = image_270x260;
    data[_jsonKeyShopShopDetailsBannerImage_320x320] = image_320x320;
    return data;
  }
}

const String _jsonKeyShopShopDetailsLogoStorage = 'storage';
const String _jsonKeyShopShopDetailsLogoOriginalImage = 'original_image';
const String _jsonKeyShopShopDetailsLogoImage_100x38 = 'image_100x38';
const String _jsonKeyShopShopDetailsLogoImage_89x33 = 'image_89x33';
const String _jsonKeyShopShopDetailsLogoImage_118x45 = 'image_118x45';
const String _jsonKeyShopShopDetailsLogoImage_48x25 = 'image_48x25';
const String _jsonKeyShopShopDetailsLogoImage_40x40 = 'image_40x40';
const String _jsonKeyShopShopDetailsLogoImage_197x152 = 'image_197x152';
const String _jsonKeyShopShopDetailsLogoImage_120x80 = 'image_120x80';
const String _jsonKeyShopShopDetailsLogoImage_82x82 = 'image_82x82';
const String _jsonKeyShopShopDetailsLogoImage_617x145 = 'image_617x145';
const String _jsonKeyShopShopDetailsLogoImage_297x146 = 'image_297x146';
const String _jsonKeyShopShopDetailsLogoImage_72x72 = 'image_72x72';
const String _jsonKeyShopShopDetailsLogoImage_270x260 = 'image_270x260';
const String _jsonKeyShopShopDetailsLogoImage_320x320 = 'image_320x320';
class ShopShopDetailsLogo {

  String? storage;
  String? originalImage;
  String? image_100x38;
  String? image_89x33;
  String? image_118x45;
  String? image_48x25;
  String? image_40x40;
  String? image_197x152;
  String? image_120x80;
  String? image_82x82;
  String? image_617x145;
  String? image_297x146;
  String? image_72x72;
  String? image_270x260;
  String? image_320x320;

  ShopShopDetailsLogo({
    this.storage,
    this.originalImage,
    this.image_100x38,
    this.image_89x33,
    this.image_118x45,
    this.image_48x25,
    this.image_40x40,
    this.image_197x152,
    this.image_120x80,
    this.image_82x82,
    this.image_617x145,
    this.image_297x146,
    this.image_72x72,
    this.image_270x260,
    this.image_320x320,
  });
  ShopShopDetailsLogo.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyShopShopDetailsLogoStorage]?.toString();
    originalImage = json[_jsonKeyShopShopDetailsLogoOriginalImage]?.toString();
    image_100x38 = json[_jsonKeyShopShopDetailsLogoImage_100x38]?.toString();
    image_89x33 = json[_jsonKeyShopShopDetailsLogoImage_89x33]?.toString();
    image_118x45 = json[_jsonKeyShopShopDetailsLogoImage_118x45]?.toString();
    image_48x25 = json[_jsonKeyShopShopDetailsLogoImage_48x25]?.toString();
    image_40x40 = json[_jsonKeyShopShopDetailsLogoImage_40x40]?.toString();
    image_197x152 = json[_jsonKeyShopShopDetailsLogoImage_197x152]?.toString();
    image_120x80 = json[_jsonKeyShopShopDetailsLogoImage_120x80]?.toString();
    image_82x82 = json[_jsonKeyShopShopDetailsLogoImage_82x82]?.toString();
    image_617x145 = json[_jsonKeyShopShopDetailsLogoImage_617x145]?.toString();
    image_297x146 = json[_jsonKeyShopShopDetailsLogoImage_297x146]?.toString();
    image_72x72 = json[_jsonKeyShopShopDetailsLogoImage_72x72]?.toString();
    image_270x260 = json[_jsonKeyShopShopDetailsLogoImage_270x260]?.toString();
    image_320x320 = json[_jsonKeyShopShopDetailsLogoImage_320x320]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopShopDetailsLogoStorage] = storage;
    data[_jsonKeyShopShopDetailsLogoOriginalImage] = originalImage;
    data[_jsonKeyShopShopDetailsLogoImage_100x38] = image_100x38;
    data[_jsonKeyShopShopDetailsLogoImage_89x33] = image_89x33;
    data[_jsonKeyShopShopDetailsLogoImage_118x45] = image_118x45;
    data[_jsonKeyShopShopDetailsLogoImage_48x25] = image_48x25;
    data[_jsonKeyShopShopDetailsLogoImage_40x40] = image_40x40;
    data[_jsonKeyShopShopDetailsLogoImage_197x152] = image_197x152;
    data[_jsonKeyShopShopDetailsLogoImage_120x80] = image_120x80;
    data[_jsonKeyShopShopDetailsLogoImage_82x82] = image_82x82;
    data[_jsonKeyShopShopDetailsLogoImage_617x145] = image_617x145;
    data[_jsonKeyShopShopDetailsLogoImage_297x146] = image_297x146;
    data[_jsonKeyShopShopDetailsLogoImage_72x72] = image_72x72;
    data[_jsonKeyShopShopDetailsLogoImage_270x260] = image_270x260;
    data[_jsonKeyShopShopDetailsLogoImage_320x320] = image_320x320;
    return data;
  }
}

const String _jsonKeyShopShopDetailsTaxPaperStorage = 'storage';
const String _jsonKeyShopShopDetailsTaxPaperOriginalImage = 'original_image';
const String _jsonKeyShopShopDetailsTaxPaperImage_40x40 = 'image_40x40';
const String _jsonKeyShopShopDetailsTaxPaperImage_72x72 = 'image_72x72';
const String _jsonKeyShopShopDetailsTaxPaperImage_190x230 = 'image_190x230';
const String _jsonKeyShopShopDetailsTaxPaperImage_110x122 = 'image_110x122';
const String _jsonKeyShopShopDetailsTaxPaperImage_320x320 = 'image_320x320';
const String _jsonKeyShopShopDetailsTaxPaperImageThumbnail = 'image_thumbnail';
class ShopShopDetailsTaxPaper {

  String? storage;
  String? originalImage;
  String? image_40x40;
  String? image_72x72;
  String? image_190x230;
  String? image_110x122;
  String? image_320x320;
  String? imageThumbnail;

  ShopShopDetailsTaxPaper({
    this.storage,
    this.originalImage,
    this.image_40x40,
    this.image_72x72,
    this.image_190x230,
    this.image_110x122,
    this.image_320x320,
    this.imageThumbnail,
  });
  ShopShopDetailsTaxPaper.fromJson(Map<String, dynamic> json) {
    storage = json[_jsonKeyShopShopDetailsTaxPaperStorage]?.toString();
    originalImage = json[_jsonKeyShopShopDetailsTaxPaperOriginalImage]?.toString();
    image_40x40 = json[_jsonKeyShopShopDetailsTaxPaperImage_40x40]?.toString();
    image_72x72 = json[_jsonKeyShopShopDetailsTaxPaperImage_72x72]?.toString();
    image_190x230 = json[_jsonKeyShopShopDetailsTaxPaperImage_190x230]?.toString();
    image_110x122 = json[_jsonKeyShopShopDetailsTaxPaperImage_110x122]?.toString();
    image_320x320 = json[_jsonKeyShopShopDetailsTaxPaperImage_320x320]?.toString();
    imageThumbnail = json[_jsonKeyShopShopDetailsTaxPaperImageThumbnail]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopShopDetailsTaxPaperStorage] = storage;
    data[_jsonKeyShopShopDetailsTaxPaperOriginalImage] = originalImage;
    data[_jsonKeyShopShopDetailsTaxPaperImage_40x40] = image_40x40;
    data[_jsonKeyShopShopDetailsTaxPaperImage_72x72] = image_72x72;
    data[_jsonKeyShopShopDetailsTaxPaperImage_190x230] = image_190x230;
    data[_jsonKeyShopShopDetailsTaxPaperImage_110x122] = image_110x122;
    data[_jsonKeyShopShopDetailsTaxPaperImage_320x320] = image_320x320;
    data[_jsonKeyShopShopDetailsTaxPaperImageThumbnail] = imageThumbnail;
    return data;
  }
}

class ShopShopDetails {

  int? id;
  String? userId;
  String? shopName;
  String? slug;
  String? verifiedAt;
  String? licenseNo;
  ShopShopDetailsTaxPaper? taxPaper;
  ShopShopDetailsLogo? logo;
  ShopShopDetailsBanner? banner;
  List<ShopShopDetailsShopPageContents?>? shopPageContents;
  String? shopBannerId;
  ShopShopDetailsShopBanner? shopBanner;
  String? shopTagline;
  String? phoneNo;
  String? shopEmail;
  String? website;
  String? address;
  String? ratingCount;
  String? reviewsCount;
  String? facebook;
  String? google;
  String? twitter;
  String? youtube;
  String? metaTitle;
  String? metaDescription;
  String? stateId;
  String? cityId;
  String? townId;
  String? latitude;
  String? longitude;
  String? scheduleId;
  String? accountType;
  String? shopTypeId;
  String? createdAt;
  String? updatedAt;
  String? image_105x75;
  String? image_197x152;
  String? image_1905x350;
  String? image_90x60;
  String? image_82x82;
  String? image_120x80;
  String? image_297x146;
  String? image_617x145;
  String? startDate;
  String? image_1920x412;

  ShopShopDetails({
    this.id,
    this.userId,
    this.shopName,
    this.slug,
    this.verifiedAt,
    this.licenseNo,
    this.taxPaper,
    this.logo,
    this.banner,
    this.shopPageContents,
    this.shopBannerId,
    this.shopBanner,
    this.shopTagline,
    this.phoneNo,
    this.shopEmail,
    this.website,
    this.address,
    this.ratingCount,
    this.reviewsCount,
    this.facebook,
    this.google,
    this.twitter,
    this.youtube,
    this.metaTitle,
    this.metaDescription,
    this.stateId,
    this.cityId,
    this.townId,
    this.latitude,
    this.longitude,
    this.scheduleId,
    this.accountType,
    this.shopTypeId,
    this.createdAt,
    this.updatedAt,
    this.image_105x75,
    this.image_197x152,
    this.image_1905x350,
    this.image_90x60,
    this.image_82x82,
    this.image_120x80,
    this.image_297x146,
    this.image_617x145,
    this.startDate,
    this.image_1920x412,
  });
  ShopShopDetails.fromJson(Map<String, dynamic> json) {
    id = json[_jsonKeyShopShopDetailsId]?.toInt();
    userId = json[_jsonKeyShopShopDetailsUserId]?.toString();
    shopName = json[_jsonKeyShopShopDetailsShopName]?.toString();
    slug = json[_jsonKeyShopShopDetailsSlug]?.toString();
    verifiedAt = json[_jsonKeyShopShopDetailsVerifiedAt]?.toString();
    licenseNo = json[_jsonKeyShopShopDetailsLicenseNo]?.toString();
    taxPaper = (json[_jsonKeyShopShopDetailsTaxPaper] != null) ? ShopShopDetailsTaxPaper.fromJson(json[_jsonKeyShopShopDetailsTaxPaper]) : null;
    logo = (json[_jsonKeyShopShopDetailsLogo] != null) ? ShopShopDetailsLogo.fromJson(json[_jsonKeyShopShopDetailsLogo]) : null;
    banner = (json[_jsonKeyShopShopDetailsBanner] != null) ? ShopShopDetailsBanner.fromJson(json[_jsonKeyShopShopDetailsBanner]) : null;
    if (json[_jsonKeyShopShopDetailsShopPageContents] != null) {
      final v = json[_jsonKeyShopShopDetailsShopPageContents];
      final arr0 = <ShopShopDetailsShopPageContents>[];
      v.forEach((v) {
        arr0.add(ShopShopDetailsShopPageContents.fromJson(v));
      });
      shopPageContents = arr0;
    }
    shopBannerId = json[_jsonKeyShopShopDetailsShopBannerId]?.toString();
    shopBanner = (json[_jsonKeyShopShopDetailsShopBanner] != null) ? ShopShopDetailsShopBanner.fromJson(json[_jsonKeyShopShopDetailsShopBanner]) : null;
    shopTagline = json[_jsonKeyShopShopDetailsShopTagline]?.toString();
    phoneNo = json[_jsonKeyShopShopDetailsPhoneNo]?.toString();
    shopEmail = json[_jsonKeyShopShopDetailsShopEmail]?.toString();
    website = json[_jsonKeyShopShopDetailsWebsite]?.toString();
    address = json[_jsonKeyShopShopDetailsAddress]?.toString();
    ratingCount = json[_jsonKeyShopShopDetailsRatingCount]?.toString();
    reviewsCount = json[_jsonKeyShopShopDetailsReviewsCount]?.toString();
    facebook = json[_jsonKeyShopShopDetailsFacebook]?.toString();
    google = json[_jsonKeyShopShopDetailsGoogle]?.toString();
    twitter = json[_jsonKeyShopShopDetailsTwitter]?.toString();
    youtube = json[_jsonKeyShopShopDetailsYoutube]?.toString();
    metaTitle = json[_jsonKeyShopShopDetailsMetaTitle]?.toString();
    metaDescription = json[_jsonKeyShopShopDetailsMetaDescription]?.toString();
    stateId = json[_jsonKeyShopShopDetailsStateId]?.toString();
    cityId = json[_jsonKeyShopShopDetailsCityId]?.toString();
    townId = json[_jsonKeyShopShopDetailsTownId]?.toString();
    latitude = json[_jsonKeyShopShopDetailsLatitude]?.toString();
    longitude = json[_jsonKeyShopShopDetailsLongitude]?.toString();
    scheduleId = json[_jsonKeyShopShopDetailsScheduleId]?.toString();
    accountType = json[_jsonKeyShopShopDetailsAccountType]?.toString();
    shopTypeId = json[_jsonKeyShopShopDetailsShopTypeId]?.toString();
    createdAt = json[_jsonKeyShopShopDetailsCreatedAt]?.toString();
    updatedAt = json[_jsonKeyShopShopDetailsUpdatedAt]?.toString();
    image_105x75 = json[_jsonKeyShopShopDetailsImage_105x75]?.toString();
    image_197x152 = json[_jsonKeyShopShopDetailsImage_197x152]?.toString();
    image_1905x350 = json[_jsonKeyShopShopDetailsImage_1905x350]?.toString();
    image_90x60 = json[_jsonKeyShopShopDetailsImage_90x60]?.toString();
    image_82x82 = json[_jsonKeyShopShopDetailsImage_82x82]?.toString();
    image_120x80 = json[_jsonKeyShopShopDetailsImage_120x80]?.toString();
    image_297x146 = json[_jsonKeyShopShopDetailsImage_297x146]?.toString();
    image_617x145 = json[_jsonKeyShopShopDetailsImage_617x145]?.toString();
    startDate = json[_jsonKeyShopShopDetailsStartDate]?.toString();
    image_1920x412 = json[_jsonKeyShopShopDetailsImage_1920x412]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShopShopDetailsId] = id;
    data[_jsonKeyShopShopDetailsUserId] = userId;
    data[_jsonKeyShopShopDetailsShopName] = shopName;
    data[_jsonKeyShopShopDetailsSlug] = slug;
    data[_jsonKeyShopShopDetailsVerifiedAt] = verifiedAt;
    data[_jsonKeyShopShopDetailsLicenseNo] = licenseNo;
    if (taxPaper != null) {
      data[_jsonKeyShopShopDetailsTaxPaper] = taxPaper!.toJson();
    }
    if (logo != null) {
      data[_jsonKeyShopShopDetailsLogo] = logo!.toJson();
    }
    if (banner != null) {
      data[_jsonKeyShopShopDetailsBanner] = banner!.toJson();
    }
    if (shopPageContents != null) {
      final v = shopPageContents;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyShopShopDetailsShopPageContents] = arr0;
    }
    data[_jsonKeyShopShopDetailsShopBannerId] = shopBannerId;
    if (shopBanner != null) {
      data[_jsonKeyShopShopDetailsShopBanner] = shopBanner!.toJson();
    }
    data[_jsonKeyShopShopDetailsShopTagline] = shopTagline;
    data[_jsonKeyShopShopDetailsPhoneNo] = phoneNo;
    data[_jsonKeyShopShopDetailsShopEmail] = shopEmail;
    data[_jsonKeyShopShopDetailsWebsite] = website;
    data[_jsonKeyShopShopDetailsAddress] = address;
    data[_jsonKeyShopShopDetailsRatingCount] = ratingCount;
    data[_jsonKeyShopShopDetailsReviewsCount] = reviewsCount;
    data[_jsonKeyShopShopDetailsFacebook] = facebook;
    data[_jsonKeyShopShopDetailsGoogle] = google;
    data[_jsonKeyShopShopDetailsTwitter] = twitter;
    data[_jsonKeyShopShopDetailsYoutube] = youtube;
    data[_jsonKeyShopShopDetailsMetaTitle] = metaTitle;
    data[_jsonKeyShopShopDetailsMetaDescription] = metaDescription;
    data[_jsonKeyShopShopDetailsStateId] = stateId;
    data[_jsonKeyShopShopDetailsCityId] = cityId;
    data[_jsonKeyShopShopDetailsTownId] = townId;
    data[_jsonKeyShopShopDetailsLatitude] = latitude;
    data[_jsonKeyShopShopDetailsLongitude] = longitude;
    data[_jsonKeyShopShopDetailsScheduleId] = scheduleId;
    data[_jsonKeyShopShopDetailsAccountType] = accountType;
    data[_jsonKeyShopShopDetailsShopTypeId] = shopTypeId;
    data[_jsonKeyShopShopDetailsCreatedAt] = createdAt;
    data[_jsonKeyShopShopDetailsUpdatedAt] = updatedAt;
    data[_jsonKeyShopShopDetailsImage_105x75] = image_105x75;
    data[_jsonKeyShopShopDetailsImage_197x152] = image_197x152;
    data[_jsonKeyShopShopDetailsImage_1905x350] = image_1905x350;
    data[_jsonKeyShopShopDetailsImage_90x60] = image_90x60;
    data[_jsonKeyShopShopDetailsImage_82x82] = image_82x82;
    data[_jsonKeyShopShopDetailsImage_120x80] = image_120x80;
    data[_jsonKeyShopShopDetailsImage_297x146] = image_297x146;
    data[_jsonKeyShopShopDetailsImage_617x145] = image_617x145;
    data[_jsonKeyShopShopDetailsStartDate] = startDate;
    data[_jsonKeyShopShopDetailsImage_1920x412] = image_1920x412;
    return data;
  }
}

class Shop {

  ShopShopDetails? shopDetails;
  String? shopType;
  List<ShopAllProducts?>? allProducts;

  Shop({
    this.shopDetails,
    this.shopType,
    this.allProducts,
  });
  Shop.fromJson(Map<String, dynamic> json) {
    shopDetails = (json[_jsonKeyShopShopDetails] != null) ? ShopShopDetails.fromJson(json[_jsonKeyShopShopDetails]) : null;
    shopType = json[_jsonKeyShopShopType]?.toString();
    if (json[_jsonKeyShopAllProducts] != null) {
      final v = json[_jsonKeyShopAllProducts];
      final arr0 = <ShopAllProducts>[];
      v.forEach((v) {
        arr0.add(ShopAllProducts.fromJson(v));
      });
      allProducts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (shopDetails != null) {
      data[_jsonKeyShopShopDetails] = shopDetails!.toJson();
    }
    data[_jsonKeyShopShopType] = shopType;
    if (allProducts != null) {
      final v = allProducts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyShopAllProducts] = arr0;
    }
    return data;
  }

}
